### PR TITLE
use legacy_lookup_table to avoid thatch_reed problem

### LINKED ISSUE #3529: Can't load Build 20 save: unknown ware type "thatch_reed"
- Affected savegame: [215.wgf](https://www.widelands.org/forum/attachment/570041fdadfb373fde9ee7402e3230d679be8330/)

Trying to load this savegame (saved in Build 20) results in the following error:
```
Game data error
buildings: unknown ware type "thatch_reed"
```
Likely related to the following commits:

777771e9ed Renamed thatch reed to reed.
c7e8e09267 Fix savegame compatibility for reed, buildings, players view and economy requests.

 - OS: Manjaro Linux
 - Widelands Version: Current master (9f6391ed7e)

### PR DESCRIPTION
**Pull request by jmoerschbach**
also extend legacy_lookup_table to have consistent code

fixes #3529

### CODE REVIEW

File: src/map_io/tribes_legacy_lookup_table.cc [hunk 1]
```diff
@@ -38,7 +38,12 @@ TribesLegacyLookupTable::TribesLegacyLookupTable()
...
         {"reed_tiny", "reedfield_tiny"},
         {"reed_ripe", "reedfield_ripe"},
-     } {
+     },
+	 // Buildings
+     buildings_{},
+	 // Ships
+	 ships_{}
+     {
 }
```
Comment (stonerl) [inline src/map_io/tribes_legacy_lookup_table.cc]: Are you sure about this opening bracket? Remove the closing on instead.

**Review by stonerl — CHANGES_REQUESTED** [review]

File: src/map_io/tribes_legacy_lookup_table.cc (hunk 1 above)
Comment (jmoerschbach) [reply src/map_io/tribes_legacy_lookup_table.cc]: actually I am quite sure since those are the opening/closing brackets of the constructor body after the initialization list (which is a bit long)  ;)

**Comment by jmoerschbach** [comment]
the travis check failed because all but the very last build succeeded.
RELEASE: macOS10.12 witch Xcode 8.3 timed out.
Can anybody restart it (It seems I do not have the rights to do so)?

File: src/map_io/tribes_legacy_lookup_table.cc (hunk 1 above)
Comment (stonerl) [reply src/map_io/tribes_legacy_lookup_table.cc]: You're completely right. Should check my 👓  😃

**Review by stonerl — DISMISSED** [review]

**Comment by stonerl** [comment]
It seems you're on a Windows machine and all line breaks have been replaced with \r\n by clang-format.

I wonder why? Not your fault, though. I need to investigate as to why this happened.

**Comment by jmoerschbach** [comment]
yeah, i'm on windows. I'm not quite sure who to blame actually. might be even git, right?
https://stackoverflow.com/questions/52262866/clang-format-normalized-line-endings

when git can enforce unix endings, it surely can also enforce windows ending, which might be the case on my system. I'll check the ending on my machine after clang-format ran when I'm home...

**Comment by stonerl** [comment]
I added a .gitattributes to the repo which should take care of such occurrences in the future.

**Comment by jmoerschbach** [comment]
Hi @stonerl @gunchleoc 

is there anything missing/I can do to get this merged into master? :)

**Review by stonerl — APPROVED** [review]
LGTM, but I'd like to test some older save games before merging this into master.
