### PR TITLE
SDL_PumpEvents must be called from the main Thread on macOS only

### LINKED ISSUE #5655: macOS: tutorial results in crash "nextEventMatchingMask should only be called from the Main Thread!'"
**Describe the bug**
Hello team,

every time I start a game of tutorial, it crashes after clicking OK in the following window (see below)

**To Reproduce**
1. Download game via curl mentioned here https://www.widelands.org/wiki/Download/ (for Arm / Apple Silicon Builds)
2. Mount image, move game to the applications folder
3. Run the game from applications folder
4. Start tutorial
5. Click OK in the window shown below
6. See error

**Expected behavior**
No error.

**Screenshots**

bugwindow

**Version:**

> Version: 1.1 Release  
> Operating System: macOS Monterey 12.6 M1 Pro
> Compiled with SDL version: 2.24.1  
> SDL video driver: cocoa  
> Locale: en  
> Home Directory: /Users/ojanas/.widelands  
> Configuration File: /Users/ojanas/.widelands/config  
> Data Directory: /Applications/Widelands.app/Contents/MacOS/data  
> Locale Directory: /Applications/Widelands.app/Contents/MacOS/data/locale  
> Executable Directory: /Applications/Widelands.app/Contents/MacOS/  

**Additional context**
File with traceback attached. This error happens every time.

[traceback.txt](https://github.com/widelands/widelands/files/9996989/traceback.txt)

Thank you very much for looking into this.

### PR DESCRIPTION
**Pull request by klaus-halfmann**
Fixes #5655 by wrapping SDL_PumpEvents

@Noordfrees should this be for macOS only?

I Will try to play the complete Tutorial, but this is the only call to `PumpEvents` I could find.

### CODE REVIEW

**Comment by klaus-halfmann** [comment]
When testing this I am hit by #5652 on the second tutorial ...

**Review by Noordfrees — COMMENTED** [review]
Looks good to me, but maybe you want to move the other two SDL calls into the lambda function as well just to be sure?

This should definitely not be MacOS-specific.

**Comment by klaus-halfmann** [comment]
For now I found only #5652 and some unrelated Bug, once the Build is finished we may ask the original reporter to test it?

**Comment by klaus-halfmann** [comment]
@Noordfrees this is ok for me, i played all tutorials now and all where so far so fine.
Can you merge this into 1.1 branch and I will derive another branch for a new 1.1.1?

File: src/wlapplication.cc [hunk 1]
```diff
@@ -1074,7 +1074,8 @@ void WLApplication::warp_mouse(const Vector2i position) {
 		SDL_Window* sdl_window = g_gr->get_sdlwindow();
 		if (sdl_window != nullptr) {
 			if (!mouse_locked_) {
-				SDL_PumpEvents();
+				// Fix for #5655, TODO(klaus.halfmmann): shall we do this for macOS only?
+				NoteThreadSafeFunction::instantiate([]() { SDL_PumpEvents(); }, true);
 				SDL_FlushEvent(SDL_MOUSEMOTION);
 				SDL_WarpMouseInWindow(sdl_window, position.x, position.y);
```
Comment (Noordfrees) [inline src/wlapplication.cc]: Please move the other SDL calls into the lambda as well. And remove the TODO – this is not mac-specific. Then this can be merged. I'll take care of backporting to 1.1 afterwards.

**Review by Noordfrees — CHANGES_REQUESTED** [review]

File: src/wlapplication.cc (hunk 1 above)
Comment (hillierdani) [reply src/wlapplication.cc]: Thanks for locating the bug and fix, I am eager to test on macOS.

Comment (klaus-halfmann) [reply src/wlapplication.cc]: Sorry I can only continue working / arguing with @Noordfrees next year. 
For me this fix is complete so please test it. Wrapping other SDL functions will only slow down the Game.
We need to merge this into 1.1 and then get the brew formular going.

@hillierdani  do you have time/resources to support us?

**Comment by klaus-halfmann** [comment]
@Noordfrees this works as is, why do you want me to  "move the other SDL calls into the lambda", too?
This would only slow don issues even more.

Can we ave a short call in https://meet.ffmuc.net/WidelandsChat please? 

I have finally have some few day of I want to spend for widelands

File: src/wlapplication.cc [hunk 2]
```diff
@@ -1066,7 +1066,8 @@ void WLApplication::warp_mouse(const Vector2i position) {
...
```
Comment (Noordfrees) [inline src/wlapplication.cc]: I meant not to move each call to a separate lambda but to move all three of them into the same lambda, instead of moving just the first and leaving the other two outside: 

```suggestion
				NoteThreadSafeFunction::instantiate([]() {
					SDL_PumpEvents();
					SDL_FlushEvent(SDL_MOUSEMOTION);
					SDL_WarpMouseInWindow(sdl_window, position.x, position.y);
				}, true);
```

This shouldn't cause any slowdown?

**Comment by Noordfrees** [comment]
> Can we ave a short call in [meet.ffmuc.net/WidelandsChat](https://meet.ffmuc.net/WidelandsChat) please?

Ok, I have time this evening, just write what time will fit for you

**Comment by klaus-halfmann** [comment]
Short Test is fine, ready to go?

**Review by Noordfrees — APPROVED** [review]
LGTM, works fine.

Later today I'll merge this and make the v1.1 backport and update the release with the new Mac binaries.

**Comment by Noordfrees** [comment]
Deployed to the https://github.com/widelands/widelands/tree/release-1.1 branch and to the release as https://github.com/widelands/widelands/releases/download/v1.1/Widelands-1.1-MacOS11.dmg

@klaus-halfmann Could you perhaps create an updated Arm M1 package from the branch as well?

**Comment by hillierdani** [comment]
Hi, Thank you so much for working on this issue. I just downloaded the backport, replaced the old App, started the one-player first tutorial and it segfaulted at the first instruction window.
 MacOS Big Sur 11.7
[widelands crash.txt](https://github.com/widelands/widelands/files/10333497/widelands.crash.txt)

**Comment by Noordfrees** [comment]
:(

Could you please try downloading the debug version of the same build and post the crashreport you get with that one? 
https://github.com/widelands/widelands/suites/10144936333/artifacts/495644292

**Comment by hillierdani** [comment]
Of course, thanks for pointing me to the debug binary. This is the very least I can do to support this amazing game, thanks again for your efforts!
Here is the log, it now segfaulted at the third message window.
[widelands_debug_log.txt](https://github.com/widelands/widelands/files/10333528/widelands_debug_log.txt)

**Comment by klaus-halfmann** [comment]
@hillierdani looks like you found a followup bug for https://github.com/widelands/widelands/issues/5655 :-(
`BUG IN CLIENT OF LIBDISPATCH: Assertion failed: Block was expected to execute on queue [com.apple.main-thread]`
called from
`libSDL2-2.0.0.dylib           	0x000000010f9f0894 SDL_StopTextInput_REAL + 30`
Please try the same on the Debug Build you can find in the Artifacts for this pull request:
https://github.com/widelands/widelands/suites/10140031401/artifacts/495351068
Since I am on a) Apple Silicon and b) macOs Ventura 13.1 I may not be able to reproduce this. 
@Noordfrees I will close the original #5665 but will create a new One for LIBDISPATCH before doing so.
Shall we close this PR or recyle it for the followup bug?
I will not build a new ARM Image for 1.1 until I could reproduces this.

Thanks @hillierdani for being patient with us.

**Comment by hillierdani** [comment]
Hi, I tested https://github.com/widelands/widelands/suites/10140031401/artifacts/495351068 and still get the same behaviour. I am happy to continue to test as a modest contribution for fixing this, thanks for all your efforts!

[widelands_debug_log.txt](https://github.com/widelands/widelands/files/10335210/widelands_debug_log.txt)

**Comment by klaus-halfmann** [comment]
@hillierdani I found some other bug in 1.1 but not your one, Do you have a screenshot,just before it happend for us?
As of the logmessage there should be some textinput but I see none in the tutorial?

**Comment by hillierdani** [comment]
@klaus-halfmann Good idea! Here is the screenshot. The segfault happens when the first tutorial goes through the visibility options (setting e.g. free building places visible or invisible). If I let the tutorial walk through, without moving the mouse, there is no segfault. Only when I try to interact it segfaults when the sequence of highlighting the options (from bottom to top) ends. Not sure it is clear enough what I try to describe, let me know if you prefer a screencast.

Screenshot 2023-01-03 at 10 12 36

**Comment by klaus-halfmann** [comment]
Thanks @hillierdani Just tried this on some x86 Mac nearby and did not get it.
Just for the Record: Which Language settings are you using?
For a Bug Report normally en is better unless its language related (Which I do not assume for this one)
I will try to reproduces this as you described

**Comment by klaus-halfmann** [comment]
Sorry @hillierdani I was unable to reproduce that bug. I tried master and release-1.1. Can you work through the tutorials despite this bug? Did ou try to move the "Menubar" to the bottom? Else please send me some screencast/video of your interaction. Are you still on macOS Monterey 12.6?

**Comment by hillierdani** [comment]
I can definitely live with the bug, I decided to skip the tutorials and learn the game from the manuals. The freezing occurs much less often during a longer play in a campaign mode. The position of the menubar has no role, when I first tried the game it was still in the default (bottom) position. Here is a screencast showing that I move the mouse while the tutorial sequences through the menu and at the last item segfaults.

https://user-images.githubusercontent.com/121829/210371071-d670e589-efee-43b3-a416-43df1619ef60.mp4

**Comment by klaus-halfmann** [comment]
@hillierdani OK lets leave it "as is" unless someone can reproduce it (I checked your video, but still can not reproduce it)
Tip: you can (not macOS like :-) close many widelands windows with a right click. Yo can los move the Ma while holding right mouse. And please ry all kind of cliks (e.g. roadbuilding) wth ctrl- or shift- . We could only switch most keyboard shortcuts to use CMD. Sometimes You can find me in the internet lobby and we might have a training game. Pleas watch oout for the next tournament game, we will have this when 1.2 is going final.

@Noordfrees I will build an "official" M1 version tomorrow ...

**Comment by klaus-halfmann** [comment]
@Noordfrees New release is here https://github.com/widelands/widelands/releases/download/v1.1/Widelands-1.1-MacOS12-Arm.dmg
