### PR TITLE
Skip timestamp-only POT changes during translations update

### LINKED ISSUE #5936: Re-enable filtering of pot generation times?
Direct commit https://github.com/widelands/widelands/commit/16b8c5495fb31ab7314d13404db3654318f7036f by @Noordfrees disabled the filtering of single line changes in the translation update script. Now every run produces new files with only the pot generation time changing.

As the change hadn't been discussed in advance, I'd like to ask what problem it was meant to solve. As far as I can see, the current behaviour is only a major regression.

In general, I understand that the filtering was rather simplistic, because it assumed that all single line changes were pot generation time changes. So we could add another check to make sure it is so.

What I noticed as a problem with transifex po file dates is that the last translator/date line gets reverted to some old commit when off-line translations are pushed through the command line client. But I don't think this is solved by the above change.

### PR DESCRIPTION
**Pull request by tothxa**
**Type of change**
Bugfix / Refactoring

**Issue(s) closed**
Fixes #5936

**Possible regressions**
Translation updates

**Additional context**
I made it only check the templates. PO files shouldn't have timestamp-only updates of their own, but if something slips through, they should be in sync with the template anyway.

### CODE REVIEW

File: utils/merge_and_push_translations.sh [hunk 1]
```diff
@@ -96,30 +96,16 @@ fi
...
 
-# Undo one-liner diffs in po directory - these are pure timestamps with no other content
-if false; then  # Currently disabled due to TX no longer updating timestamps reliably
+# Undo one-liner diffs of pure timestamps with no other content
 set +x
-nrAdded=""
-nrDeleted=""
-for entry in $(git diff --numstat po); do
-  if [ -z "$nrAdded" ]
+for entry in $(git diff --numstat po/*/*.pot | sed -En '/^1\t1\t/s/^1\t1\t(.*)/\1/p'); do
```
Comment (tothxa) [inline utils/merge_and_push_translations.sh]: I don't really like this `sed` command, but I don't know if it could be simplified. Other alternative would be `grep` and `cut`, but `sed` at least does it all at once.

Comment (tothxa) [reply utils/merge_and_push_translations.sh]: OK, didn't know `p` at the end is not another command, but a flag of `s`, and it only prints if there was a substitution. Now I do. :)

File: utils/merge_and_push_translations.sh [hunk 2]
```diff
@@ -96,30 +96,16 @@ fi
...
-# Undo one-liner diffs in po directory - these are pure timestamps with no other content
-if false; then  # Currently disabled due to TX no longer updating timestamps reliably
+# Undo one-liner diffs of pure timestamps with no other content
 set +x
-nrAdded=""
-nrDeleted=""
-for entry in $(git diff --numstat po); do
-  if [ -z "$nrAdded" ]
+for entry in $(git diff --numstat po/*/*.pot | sed -En 's/^1\t1\t//p'); do
+  if [ -z "$(git diff "$entry" | grep '^[+-][^+-]' | grep -v '^[+-]"POT-Creation-Date:')" ]
```
Comment (tothxa) [inline utils/merge_and_push_translations.sh:102]: or
```
sed -En -e '/^[^+-]/d' -e '/^[+-]([+-]|"POT-Creation-Date:)/d' -e p -e q
```
instead of the 2 greps, but I'm not sure if it's better

**Comment by Noordfrees** [comment]
I think PO files should also be skipped if they're timestamp-only updates – consider e.g. the most recent commit:
```
commit 8eadff95265b0cf1fd7204d82b692e381c5509e8
Author: The Widelands Translations Bot <bunnybot@widelands.org>
Date:   Mon Jun 5 02:59:55 2023 +0000

    Fetched translations and updated catalogs.

2	2	data/i18n/translation_stats.conf
1	1	po/map_along_the_river.wmf/cs.po
1	1	po/map_along_the_river.wmf/map_along_the_river.wmf.pot
1	1	po/map_the_green_plateau.wmf/ar.po
1	1	po/map_the_green_plateau.wmf/bg.po
1	1	po/map_the_green_plateau.wmf/br.po
1	1	po/map_the_green_plateau.wmf/ca.po
1	1	po/map_the_green_plateau.wmf/cs.po
1	1	po/map_the_green_plateau.wmf/da.po
1	1	po/map_the_green_plateau.wmf/de.po
1	1	po/map_the_green_plateau.wmf/el.po
1	1	po/map_the_green_plateau.wmf/en_GB.po
1	1	po/map_the_green_plateau.wmf/en_US.po
1	1	po/map_the_green_plateau.wmf/eo.po
1	1	po/map_the_green_plateau.wmf/es.po
1	1	po/map_the_green_plateau.wmf/eu.po
1	1	po/map_the_green_plateau.wmf/fa.po
1	1	po/map_the_green_plateau.wmf/fi.po
1	1	po/map_the_green_plateau.wmf/fr.po
1	1	po/map_the_green_plateau.wmf/fy.po
1	1	po/map_the_green_plateau.wmf/ga.po
1	1	po/map_the_green_plateau.wmf/gd.po
1	1	po/map_the_green_plateau.wmf/gl.po
1	1	po/map_the_green_plateau.wmf/he.po
1	1	po/map_the_green_plateau.wmf/hi.po
1	1	po/map_the_green_plateau.wmf/hr.po
1	1	po/map_the_green_plateau.wmf/id.po
1	1	po/map_the_green_plateau.wmf/ig.po
1	1	po/map_the_green_plateau.wmf/it.po
1	1	po/map_the_green_plateau.wmf/ja.po
1	1	po/map_the_green_plateau.wmf/ka.po
1	1	po/map_the_green_plateau.wmf/ko.po
1	1	po/map_the_green_plateau.wmf/krl.po
1	1	po/map_the_green_plateau.wmf/la.po
1	1	po/map_the_green_plateau.wmf/lt.po
1	1	po/map_the_green_plateau.wmf/map_the_green_plateau.wmf.pot
1	1	po/map_the_green_plateau.wmf/ms.po
1	1	po/map_the_green_plateau.wmf/nb.po
1	1	po/map_the_green_plateau.wmf/nds.po
1	1	po/map_the_green_plateau.wmf/nl.po
1	1	po/map_the_green_plateau.wmf/nn.po
1	1	po/map_the_green_plateau.wmf/pl.po
1	1	po/map_the_green_plateau.wmf/pt.po
1	1	po/map_the_green_plateau.wmf/pt_BR.po
1	1	po/map_the_green_plateau.wmf/ro.po
1	1	po/map_the_green_plateau.wmf/sk.po
1	1	po/map_the_green_plateau.wmf/sl.po
1	1	po/map_the_green_plateau.wmf/sr.po
1	1	po/map_the_green_plateau.wmf/sr_RS.po
1	1	po/map_the_green_plateau.wmf/sv.po
1	1	po/map_the_green_plateau.wmf/tr.po
1	1	po/map_the_green_plateau.wmf/uk.po
1	1	po/map_the_green_plateau.wmf/zh_CN.po
1	1	po/map_the_green_plateau.wmf/zh_TW.po
1	1	po/maps/ar.po
1	1	po/maps/bg.po
1	1	po/maps/br.po
1	1	po/maps/ca.po
1	1	po/maps/cs.po
1	1	po/maps/da.po
1	1	po/maps/de.po
1	1	po/maps/el.po
1	1	po/maps/en_GB.po
1	1	po/maps/en_US.po
1	1	po/maps/eo.po
1	1	po/maps/es.po
1	1	po/maps/eu.po
1	1	po/maps/fa.po
1	1	po/maps/fi.po
1	1	po/maps/fr.po
1	1	po/maps/fy.po
1	1	po/maps/ga.po
1	1	po/maps/gd.po
1	1	po/maps/gl.po
1	1	po/maps/he.po
1	1	po/maps/hi.po
1	1	po/maps/hr.po
1	1	po/maps/id.po
1	1	po/maps/ig.po
1	1	po/maps/it.po
1	1	po/maps/ja.po
1	1	po/maps/ka.po
1	1	po/maps/ko.po
1	1	po/maps/krl.po
1	1	po/maps/la.po
1	1	po/maps/lt.po
1	1	po/maps/maps.pot
1	1	po/maps/ms.po
1	1	po/maps/nb.po
1	1	po/maps/nds.po
1	1	po/maps/nl.po
1	1	po/maps/nn.po
1	1	po/maps/pl.po
1	1	po/maps/pt.po
1	1	po/maps/pt_BR.po
1	1	po/maps/ro.po
1	1	po/maps/sk.po
1	1	po/maps/sl.po
1	1	po/maps/sr.po
1	1	po/maps/sr_RS.po
1	1	po/maps/sv.po
1	1	po/maps/tr.po
1	1	po/maps/uk.po
1	1	po/maps/zh_CN.po
1	1	po/maps/zh_TW.po
1	1	po/mp_scenario_island_hopping.wmf/ar.po
1	1	po/mp_scenario_island_hopping.wmf/bg.po
1	1	po/mp_scenario_island_hopping.wmf/br.po
1	1	po/mp_scenario_island_hopping.wmf/ca.po
1	1	po/mp_scenario_island_hopping.wmf/cs.po
1	1	po/mp_scenario_island_hopping.wmf/da.po
1	1	po/mp_scenario_island_hopping.wmf/de.po
1	1	po/mp_scenario_island_hopping.wmf/el.po
1	1	po/mp_scenario_island_hopping.wmf/en_GB.po
1	1	po/mp_scenario_island_hopping.wmf/en_US.po
1	1	po/mp_scenario_island_hopping.wmf/eo.po
1	1	po/mp_scenario_island_hopping.wmf/es.po
1	1	po/mp_scenario_island_hopping.wmf/eu.po
1	1	po/mp_scenario_island_hopping.wmf/fa.po
1	1	po/mp_scenario_island_hopping.wmf/fi.po
1	1	po/mp_scenario_island_hopping.wmf/fr.po
1	1	po/mp_scenario_island_hopping.wmf/fy.po
1	1	po/mp_scenario_island_hopping.wmf/ga.po
1	1	po/mp_scenario_island_hopping.wmf/gd.po
1	1	po/mp_scenario_island_hopping.wmf/gl.po
1	1	po/mp_scenario_island_hopping.wmf/he.po
1	1	po/mp_scenario_island_hopping.wmf/hi.po
1	1	po/mp_scenario_island_hopping.wmf/hr.po
1	1	po/mp_scenario_island_hopping.wmf/id.po
1	1	po/mp_scenario_island_hopping.wmf/ig.po
1	1	po/mp_scenario_island_hopping.wmf/it.po
1	1	po/mp_scenario_island_hopping.wmf/ja.po
1	1	po/mp_scenario_island_hopping.wmf/ka.po
1	1	po/mp_scenario_island_hopping.wmf/ko.po
1	1	po/mp_scenario_island_hopping.wmf/krl.po
1	1	po/mp_scenario_island_hopping.wmf/la.po
1	1	po/mp_scenario_island_hopping.wmf/lt.po
1	1	po/mp_scenario_island_hopping.wmf/mp_scenario_island_hopping.wmf.pot
1	1	po/mp_scenario_island_hopping.wmf/ms.po
1	1	po/mp_scenario_island_hopping.wmf/nb.po
1	1	po/mp_scenario_island_hopping.wmf/nds.po
1	1	po/mp_scenario_island_hopping.wmf/nl.po
1	1	po/mp_scenario_island_hopping.wmf/nn.po
1	1	po/mp_scenario_island_hopping.wmf/pl.po
1	1	po/mp_scenario_island_hopping.wmf/pt.po
1	1	po/mp_scenario_island_hopping.wmf/pt_BR.po
1	1	po/mp_scenario_island_hopping.wmf/ro.po
1	1	po/mp_scenario_island_hopping.wmf/sk.po
1	1	po/mp_scenario_island_hopping.wmf/sl.po
1	1	po/mp_scenario_island_hopping.wmf/sr.po
1	1	po/mp_scenario_island_hopping.wmf/sr_RS.po
1	1	po/mp_scenario_island_hopping.wmf/tr.po
1	1	po/mp_scenario_island_hopping.wmf/uk.po
1	1	po/mp_scenario_island_hopping.wmf/zh_CN.po
1	1	po/mp_scenario_island_hopping.wmf/zh_TW.po
1	1	po/mp_scenario_smugglers.wmf/ar.po
1	1	po/mp_scenario_smugglers.wmf/bg.po
1	1	po/mp_scenario_smugglers.wmf/br.po
1	1	po/mp_scenario_smugglers.wmf/ca.po
1	1	po/mp_scenario_smugglers.wmf/cs.po
1	1	po/mp_scenario_smugglers.wmf/da.po
1	1	po/mp_scenario_smugglers.wmf/de.po
1	1	po/mp_scenario_smugglers.wmf/el.po
1	1	po/mp_scenario_smugglers.wmf/en_GB.po
1	1	po/mp_scenario_smugglers.wmf/en_US.po
1	1	po/mp_scenario_smugglers.wmf/eo.po
1	1	po/mp_scenario_smugglers.wmf/es.po
1	1	po/mp_scenario_smugglers.wmf/eu.po
1	1	po/mp_scenario_smugglers.wmf/fa.po
1	1	po/mp_scenario_smugglers.wmf/fi.po
1	1	po/mp_scenario_smugglers.wmf/fr.po
1	1	po/mp_scenario_smugglers.wmf/fy.po
1	1	po/mp_scenario_smugglers.wmf/ga.po
1	1	po/mp_scenario_smugglers.wmf/gd.po
1	1	po/mp_scenario_smugglers.wmf/gl.po
1	1	po/mp_scenario_smugglers.wmf/he.po
1	1	po/mp_scenario_smugglers.wmf/hi.po
1	1	po/mp_scenario_smugglers.wmf/hr.po
1	1	po/mp_scenario_smugglers.wmf/hu.po
1	1	po/mp_scenario_smugglers.wmf/id.po
1	1	po/mp_scenario_smugglers.wmf/ig.po
1	1	po/mp_scenario_smugglers.wmf/it.po
1	1	po/mp_scenario_smugglers.wmf/ja.po
1	1	po/mp_scenario_smugglers.wmf/ka.po
1	1	po/mp_scenario_smugglers.wmf/ko.po
1	1	po/mp_scenario_smugglers.wmf/krl.po
1	1	po/mp_scenario_smugglers.wmf/la.po
1	1	po/mp_scenario_smugglers.wmf/lt.po
1	1	po/mp_scenario_smugglers.wmf/mp_scenario_smugglers.wmf.pot
1	1	po/mp_scenario_smugglers.wmf/ms.po
1	1	po/mp_scenario_smugglers.wmf/nb.po
1	1	po/mp_scenario_smugglers.wmf/nds.po
1	1	po/mp_scenario_smugglers.wmf/nl.po
1	1	po/mp_scenario_smugglers.wmf/nn.po
1	1	po/mp_scenario_smugglers.wmf/pl.po
1	1	po/mp_scenario_smugglers.wmf/pt.po
1	1	po/mp_scenario_smugglers.wmf/pt_BR.po
1	1	po/mp_scenario_smugglers.wmf/ro.po
1	1	po/mp_scenario_smugglers.wmf/ru.po
1	1	po/mp_scenario_smugglers.wmf/sk.po
1	1	po/mp_scenario_smugglers.wmf/sl.po
1	1	po/mp_scenario_smugglers.wmf/sr.po
1	1	po/mp_scenario_smugglers.wmf/sr_RS.po
1	1	po/mp_scenario_smugglers.wmf/sv.po
1	1	po/mp_scenario_smugglers.wmf/tr.po
1	1	po/mp_scenario_smugglers.wmf/uk.po
1	1	po/mp_scenario_smugglers.wmf/zh_CN.po
1	1	po/mp_scenario_smugglers.wmf/zh_TW.po
1	1	po/scenario_atl01.wmf/ar.po
1	1	po/scenario_atl01.wmf/bg.po
1	1	po/scenario_atl01.wmf/br.po
1	1	po/scenario_atl01.wmf/ca.po
1	1	po/scenario_atl01.wmf/cs.po
1	1	po/scenario_atl01.wmf/da.po
1	1	po/scenario_atl01.wmf/de.po
1	1	po/scenario_atl01.wmf/el.po
1	1	po/scenario_atl01.wmf/en_US.po
1	1	po/scenario_atl01.wmf/eo.po
1	1	po/scenario_atl01.wmf/es.po
1	1	po/scenario_atl01.wmf/eu.po
1	1	po/scenario_atl01.wmf/fa.po
1	1	po/scenario_atl01.wmf/fi.po
1	1	po/scenario_atl01.wmf/fr.po
1	1	po/scenario_atl01.wmf/fy.po
1	1	po/scenario_atl01.wmf/ga.po
1	1	po/scenario_atl01.wmf/gd.po
1	1	po/scenario_atl01.wmf/gl.po
1	1	po/scenario_atl01.wmf/he.po
1	1	po/scenario_atl01.wmf/hi.po
1	1	po/scenario_atl01.wmf/hr.po
1	1	po/scenario_atl01.wmf/hu.po
1	1	po/scenario_atl01.wmf/id.po
1	1	po/scenario_atl01.wmf/ig.po
1	1	po/scenario_atl01.wmf/it.po
1	1	po/scenario_atl01.wmf/ja.po
1	1	po/scenario_atl01.wmf/ka.po
1	1	po/scenario_atl01.wmf/ko.po
1	1	po/scenario_atl01.wmf/krl.po
1	1	po/scenario_atl01.wmf/la.po
1	1	po/scenario_atl01.wmf/lt.po
1	1	po/scenario_atl01.wmf/ms.po
1	1	po/scenario_atl01.wmf/nb.po
1	1	po/scenario_atl01.wmf/nds.po
1	1	po/scenario_atl01.wmf/nl.po
1	1	po/scenario_atl01.wmf/nn.po
1	1	po/scenario_atl01.wmf/pl.po
1	1	po/scenario_atl01.wmf/pt.po
1	1	po/scenario_atl01.wmf/pt_BR.po
1	1	po/scenario_atl01.wmf/ro.po
1	1	po/scenario_atl01.wmf/ru.po
1	1	po/scenario_atl01.wmf/scenario_atl01.wmf.pot
1	1	po/scenario_atl01.wmf/sk.po
1	1	po/scenario_atl01.wmf/sl.po
1	1	po/scenario_atl01.wmf/sr.po
1	1	po/scenario_atl01.wmf/sr_RS.po
1	1	po/scenario_atl01.wmf/tr.po
1	1	po/scenario_atl01.wmf/uk.po
1	1	po/scenario_atl01.wmf/zh_CN.po
1	1	po/scenario_atl01.wmf/zh_TW.po
1	1	po/scenario_atl02.wmf/scenario_atl02.wmf.pot
1	1	po/scenario_bar01.wmf/ar.po
1	1	po/scenario_bar01.wmf/bg.po
1	1	po/scenario_bar01.wmf/br.po
1	1	po/scenario_bar01.wmf/ca.po
1	1	po/scenario_bar01.wmf/cs.po
1	1	po/scenario_bar01.wmf/da.po
1	1	po/scenario_bar01.wmf/de.po
1	1	po/scenario_bar01.wmf/el.po
1	1	po/scenario_bar01.wmf/en_US.po
1	1	po/scenario_bar01.wmf/eo.po
1	1	po/scenario_bar01.wmf/es.po
1	1	po/scenario_bar01.wmf/eu.po
1	1	po/scenario_bar01.wmf/fa.po
1	1	po/scenario_bar01.wmf/fi.po
1	1	po/scenario_bar01.wmf/fr.po
1	1	po/scenario_bar01.wmf/fy.po
1	1	po/scenario_bar01.wmf/ga.po
1	1	po/scenario_bar01.wmf/gd.po
1	1	po/scenario_bar01.wmf/gl.po
1	1	po/scenario_bar01.wmf/he.po
1	1	po/scenario_bar01.wmf/hi.po
1	1	po/scenario_bar01.wmf/hr.po
1	1	po/scenario_bar01.wmf/hu.po
1	1	po/scenario_bar01.wmf/id.po
1	1	po/scenario_bar01.wmf/ig.po
1	1	po/scenario_bar01.wmf/it.po
1	1	po/scenario_bar01.wmf/ja.po
1	1	po/scenario_bar01.wmf/ka.po
1	1	po/scenario_bar01.wmf/ko.po
1	1	po/scenario_bar01.wmf/krl.po
1	1	po/scenario_bar01.wmf/la.po
1	1	po/scenario_bar01.wmf/lt.po
1	1	po/scenario_bar01.wmf/ms.po
1	1	po/scenario_bar01.wmf/nb.po
1	1	po/scenario_bar01.wmf/nds.po
1	1	po/scenario_bar01.wmf/nl.po
1	1	po/scenario_bar01.wmf/nn.po
1	1	po/scenario_bar01.wmf/pl.po
1	1	po/scenario_bar01.wmf/pt.po
1	1	po/scenario_bar01.wmf/pt_BR.po
1	1	po/scenario_bar01.wmf/ro.po
1	1	po/scenario_bar01.wmf/ru.po
1	1	po/scenario_bar01.wmf/scenario_bar01.wmf.pot
1	1	po/scenario_bar01.wmf/sk.po
1	1	po/scenario_bar01.wmf/sl.po
1	1	po/scenario_bar01.wmf/sr.po
1	1	po/scenario_bar01.wmf/sr_RS.po
1	1	po/scenario_bar01.wmf/sv.po
1	1	po/scenario_bar01.wmf/tr.po
1	1	po/scenario_bar01.wmf/uk.po
1	1	po/scenario_bar01.wmf/zh_CN.po
1	1	po/scenario_bar01.wmf/zh_TW.po
1	1	po/scenario_bar02.wmf/ar.po
1	1	po/scenario_bar02.wmf/bg.po
1	1	po/scenario_bar02.wmf/br.po
1	1	po/scenario_bar02.wmf/ca.po
1	1	po/scenario_bar02.wmf/cs.po
1	1	po/scenario_bar02.wmf/da.po
1	1	po/scenario_bar02.wmf/de.po
1	1	po/scenario_bar02.wmf/el.po
1	1	po/scenario_bar02.wmf/en_GB.po
1	1	po/scenario_bar02.wmf/en_US.po
1	1	po/scenario_bar02.wmf/eo.po
1	1	po/scenario_bar02.wmf/es.po
1	1	po/scenario_bar02.wmf/eu.po
1	1	po/scenario_bar02.wmf/fa.po
1	1	po/scenario_bar02.wmf/fi.po
1	1	po/scenario_bar02.wmf/fr.po
1	1	po/scenario_bar02.wmf/fy.po
1	1	po/scenario_bar02.wmf/ga.po
1	1	po/scenario_bar02.wmf/gd.po
1	1	po/scenario_bar02.wmf/gl.po
1	1	po/scenario_bar02.wmf/he.po
1	1	po/scenario_bar02.wmf/hi.po
1	1	po/scenario_bar02.wmf/hr.po
1	1	po/scenario_bar02.wmf/hu.po
1	1	po/scenario_bar02.wmf/id.po
1	1	po/scenario_bar02.wmf/ig.po
1	1	po/scenario_bar02.wmf/it.po
1	1	po/scenario_bar02.wmf/ja.po
1	1	po/scenario_bar02.wmf/ka.po
1	1	po/scenario_bar02.wmf/ko.po
1	1	po/scenario_bar02.wmf/krl.po
1	1	po/scenario_bar02.wmf/la.po
1	1	po/scenario_bar02.wmf/lt.po
1	1	po/scenario_bar02.wmf/ms.po
1	1	po/scenario_bar02.wmf/nb.po
1	1	po/scenario_bar02.wmf/nds.po
1	1	po/scenario_bar02.wmf/nl.po
1	1	po/scenario_bar02.wmf/nn.po
1	1	po/scenario_bar02.wmf/pl.po
1	1	po/scenario_bar02.wmf/pt.po
1	1	po/scenario_bar02.wmf/pt_BR.po
1	1	po/scenario_bar02.wmf/ro.po
1	1	po/scenario_bar02.wmf/ru.po
1	1	po/scenario_bar02.wmf/scenario_bar02.wmf.pot
1	1	po/scenario_bar02.wmf/sk.po
1	1	po/scenario_bar02.wmf/sl.po
1	1	po/scenario_bar02.wmf/sr.po
1	1	po/scenario_bar02.wmf/sr_RS.po
1	1	po/scenario_bar02.wmf/sv.po
1	1	po/scenario_bar02.wmf/tr.po
1	1	po/scenario_bar02.wmf/uk.po
1	1	po/scenario_bar02.wmf/zh_CN.po
1	1	po/scenario_bar02.wmf/zh_TW.po
1	1	po/scenario_dummy.wmf/ar.po
1	1	po/scenario_dummy.wmf/bg.po
1	1	po/scenario_dummy.wmf/br.po
1	1	po/scenario_dummy.wmf/ca.po
1	1	po/scenario_dummy.wmf/cs.po
1	1	po/scenario_dummy.wmf/da.po
1	1	po/scenario_dummy.wmf/de.po
1	1	po/scenario_dummy.wmf/el.po
1	1	po/scenario_dummy.wmf/en_GB.po
1	1	po/scenario_dummy.wmf/en_US.po
1	1	po/scenario_dummy.wmf/eo.po
1	1	po/scenario_dummy.wmf/es.po
1	1	po/scenario_dummy.wmf/eu.po
1	1	po/scenario_dummy.wmf/fa.po
1	1	po/scenario_dummy.wmf/fi.po
1	1	po/scenario_dummy.wmf/fr.po
1	1	po/scenario_dummy.wmf/fy.po
1	1	po/scenario_dummy.wmf/ga.po
1	1	po/scenario_dummy.wmf/gd.po
1	1	po/scenario_dummy.wmf/gl.po
1	1	po/scenario_dummy.wmf/he.po
1	1	po/scenario_dummy.wmf/hi.po
1	1	po/scenario_dummy.wmf/hr.po
1	1	po/scenario_dummy.wmf/hu.po
1	1	po/scenario_dummy.wmf/id.po
1	1	po/scenario_dummy.wmf/ig.po
1	1	po/scenario_dummy.wmf/it.po
1	1	po/scenario_dummy.wmf/ja.po
1	1	po/scenario_dummy.wmf/ka.po
1	1	po/scenario_dummy.wmf/ko.po
1	1	po/scenario_dummy.wmf/krl.po
1	1	po/scenario_dummy.wmf/la.po
1	1	po/scenario_dummy.wmf/lt.po
1	1	po/scenario_dummy.wmf/ms.po
1	1	po/scenario_dummy.wmf/nb.po
1	1	po/scenario_dummy.wmf/nds.po
1	1	po/scenario_dummy.wmf/nl.po
1	1	po/scenario_dummy.wmf/nn.po
1	1	po/scenario_dummy.wmf/pl.po
1	1	po/scenario_dummy.wmf/pt.po
1	1	po/scenario_dummy.wmf/pt_BR.po
1	1	po/scenario_dummy.wmf/ro.po
1	1	po/scenario_dummy.wmf/ru.po
1	1	po/scenario_dummy.wmf/scenario_dummy.wmf.pot
1	1	po/scenario_dummy.wmf/sk.po
1	1	po/scenario_dummy.wmf/sl.po
1	1	po/scenario_dummy.wmf/sr.po
1	1	po/scenario_dummy.wmf/sr_RS.po
1	1	po/scenario_dummy.wmf/sv.po
1	1	po/scenario_dummy.wmf/tr.po
1	1	po/scenario_dummy.wmf/uk.po
1	1	po/scenario_dummy.wmf/zh_CN.po
1	1	po/scenario_dummy.wmf/zh_TW.po
1	1	po/scenario_emp01.wmf/ar.po
1	1	po/scenario_emp01.wmf/bg.po
1	1	po/scenario_emp01.wmf/br.po
1	1	po/scenario_emp01.wmf/ca.po
1	1	po/scenario_emp01.wmf/cs.po
1	1	po/scenario_emp01.wmf/da.po
1	1	po/scenario_emp01.wmf/de.po
1	1	po/scenario_emp01.wmf/el.po
1	1	po/scenario_emp01.wmf/en_GB.po
1	1	po/scenario_emp01.wmf/en_US.po
1	1	po/scenario_emp01.wmf/eo.po
1	1	po/scenario_emp01.wmf/es.po
1	1	po/scenario_emp01.wmf/eu.po
1	1	po/scenario_emp01.wmf/fa.po
1	1	po/scenario_emp01.wmf/fi.po
1	1	po/scenario_emp01.wmf/fr.po
1	1	po/scenario_emp01.wmf/fy.po
1	1	po/scenario_emp01.wmf/ga.po
1	1	po/scenario_emp01.wmf/gd.po
1	1	po/scenario_emp01.wmf/gl.po
1	1	po/scenario_emp01.wmf/he.po
1	1	po/scenario_emp01.wmf/hi.po
1	1	po/scenario_emp01.wmf/hr.po
1	1	po/scenario_emp01.wmf/hu.po
1	1	po/scenario_emp01.wmf/id.po
1	1	po/scenario_emp01.wmf/ig.po
1	1	po/scenario_emp01.wmf/it.po
1	1	po/scenario_emp01.wmf/ja.po
1	1	po/scenario_emp01.wmf/ka.po
1	1	po/scenario_emp01.wmf/ko.po
1	1	po/scenario_emp01.wmf/krl.po
1	1	po/scenario_emp01.wmf/la.po
1	1	po/scenario_emp01.wmf/lt.po
1	1	po/scenario_emp01.wmf/ms.po
1	1	po/scenario_emp01.wmf/nb.po
1	1	po/scenario_emp01.wmf/nds.po
1	1	po/scenario_emp01.wmf/nl.po
1	1	po/scenario_emp01.wmf/nn.po
1	1	po/scenario_emp01.wmf/pl.po
1	1	po/scenario_emp01.wmf/pt.po
1	1	po/scenario_emp01.wmf/pt_BR.po
1	1	po/scenario_emp01.wmf/ro.po
1	1	po/scenario_emp01.wmf/ru.po
1	1	po/scenario_emp01.wmf/scenario_emp01.wmf.pot
1	1	po/scenario_emp01.wmf/sk.po
1	1	po/scenario_emp01.wmf/sl.po
1	1	po/scenario_emp01.wmf/sr.po
1	1	po/scenario_emp01.wmf/sr_RS.po
1	1	po/scenario_emp01.wmf/tr.po
1	1	po/scenario_emp01.wmf/uk.po
1	1	po/scenario_emp01.wmf/zh_CN.po
1	1	po/scenario_emp01.wmf/zh_TW.po
1	1	po/scenario_emp02.wmf/ar.po
1	1	po/scenario_emp02.wmf/bg.po
1	1	po/scenario_emp02.wmf/br.po
1	1	po/scenario_emp02.wmf/ca.po
1	1	po/scenario_emp02.wmf/cs.po
1	1	po/scenario_emp02.wmf/da.po
1	1	po/scenario_emp02.wmf/de.po
1	1	po/scenario_emp02.wmf/el.po
1	1	po/scenario_emp02.wmf/en_GB.po
1	1	po/scenario_emp02.wmf/en_US.po
1	1	po/scenario_emp02.wmf/eo.po
1	1	po/scenario_emp02.wmf/es.po
1	1	po/scenario_emp02.wmf/eu.po
1	1	po/scenario_emp02.wmf/fa.po
1	1	po/scenario_emp02.wmf/fi.po
1	1	po/scenario_emp02.wmf/fr.po
1	1	po/scenario_emp02.wmf/fy.po
1	1	po/scenario_emp02.wmf/ga.po
1	1	po/scenario_emp02.wmf/gd.po
1	1	po/scenario_emp02.wmf/gl.po
1	1	po/scenario_emp02.wmf/he.po
1	1	po/scenario_emp02.wmf/hi.po
1	1	po/scenario_emp02.wmf/hr.po
1	1	po/scenario_emp02.wmf/hu.po
1	1	po/scenario_emp02.wmf/id.po
1	1	po/scenario_emp02.wmf/ig.po
1	1	po/scenario_emp02.wmf/it.po
1	1	po/scenario_emp02.wmf/ja.po
1	1	po/scenario_emp02.wmf/ka.po
1	1	po/scenario_emp02.wmf/ko.po
1	1	po/scenario_emp02.wmf/krl.po
1	1	po/scenario_emp02.wmf/la.po
1	1	po/scenario_emp02.wmf/lt.po
1	1	po/scenario_emp02.wmf/ms.po
1	1	po/scenario_emp02.wmf/nb.po
1	1	po/scenario_emp02.wmf/nds.po
1	1	po/scenario_emp02.wmf/nl.po
1	1	po/scenario_emp02.wmf/nn.po
1	1	po/scenario_emp02.wmf/pl.po
1	1	po/scenario_emp02.wmf/pt.po
1	1	po/scenario_emp02.wmf/pt_BR.po
1	1	po/scenario_emp02.wmf/ro.po
1	1	po/scenario_emp02.wmf/ru.po
1	1	po/scenario_emp02.wmf/scenario_emp02.wmf.pot
1	1	po/scenario_emp02.wmf/sk.po
1	1	po/scenario_emp02.wmf/sl.po
1	1	po/scenario_emp02.wmf/sr.po
1	1	po/scenario_emp02.wmf/sr_RS.po
1	1	po/scenario_emp02.wmf/sv.po
1	1	po/scenario_emp02.wmf/tr.po
1	1	po/scenario_emp02.wmf/uk.po
1	1	po/scenario_emp02.wmf/zh_CN.po
1	1	po/scenario_emp02.wmf/zh_TW.po
1	1	po/scenario_emp03.wmf/ar.po
1	1	po/scenario_emp03.wmf/bg.po
1	1	po/scenario_emp03.wmf/br.po
1	1	po/scenario_emp03.wmf/ca.po
1	1	po/scenario_emp03.wmf/cs.po
1	1	po/scenario_emp03.wmf/da.po
1	1	po/scenario_emp03.wmf/de.po
1	1	po/scenario_emp03.wmf/el.po
1	1	po/scenario_emp03.wmf/en_GB.po
1	1	po/scenario_emp03.wmf/en_US.po
1	1	po/scenario_emp03.wmf/eo.po
1	1	po/scenario_emp03.wmf/es.po
1	1	po/scenario_emp03.wmf/eu.po
1	1	po/scenario_emp03.wmf/fa.po
1	1	po/scenario_emp03.wmf/fi.po
1	1	po/scenario_emp03.wmf/fy.po
1	1	po/scenario_emp03.wmf/ga.po
1	1	po/scenario_emp03.wmf/gd.po
1	1	po/scenario_emp03.wmf/gl.po
1	1	po/scenario_emp03.wmf/he.po
1	1	po/scenario_emp03.wmf/hi.po
1	1	po/scenario_emp03.wmf/hr.po
1	1	po/scenario_emp03.wmf/hu.po
1	1	po/scenario_emp03.wmf/id.po
1	1	po/scenario_emp03.wmf/ig.po
1	1	po/scenario_emp03.wmf/it.po
1	1	po/scenario_emp03.wmf/ja.po
1	1	po/scenario_emp03.wmf/ka.po
1	1	po/scenario_emp03.wmf/ko.po
1	1	po/scenario_emp03.wmf/krl.po
1	1	po/scenario_emp03.wmf/la.po
1	1	po/scenario_emp03.wmf/lt.po
1	1	po/scenario_emp03.wmf/ms.po
1	1	po/scenario_emp03.wmf/nb.po
1	1	po/scenario_emp03.wmf/nds.po
1	1	po/scenario_emp03.wmf/nl.po
1	1	po/scenario_emp03.wmf/nn.po
1	1	po/scenario_emp03.wmf/pl.po
1	1	po/scenario_emp03.wmf/pt.po
1	1	po/scenario_emp03.wmf/pt_BR.po
1	1	po/scenario_emp03.wmf/ro.po
1	1	po/scenario_emp03.wmf/ru.po
1	1	po/scenario_emp03.wmf/scenario_emp03.wmf.pot
1	1	po/scenario_emp03.wmf/sk.po
1	1	po/scenario_emp03.wmf/sl.po
1	1	po/scenario_emp03.wmf/sr.po
1	1	po/scenario_emp03.wmf/sr_RS.po
1	1	po/scenario_emp03.wmf/tr.po
1	1	po/scenario_emp03.wmf/uk.po
1	1	po/scenario_emp03.wmf/zh_CN.po
1	1	po/scenario_emp03.wmf/zh_TW.po
1	1	po/scenario_emp04.wmf/ar.po
1	1	po/scenario_emp04.wmf/bg.po
1	1	po/scenario_emp04.wmf/br.po
1	1	po/scenario_emp04.wmf/ca.po
1	1	po/scenario_emp04.wmf/cs.po
1	1	po/scenario_emp04.wmf/da.po
1	1	po/scenario_emp04.wmf/de.po
1	1	po/scenario_emp04.wmf/el.po
1	1	po/scenario_emp04.wmf/en_GB.po
1	1	po/scenario_emp04.wmf/en_US.po
1	1	po/scenario_emp04.wmf/eo.po
1	1	po/scenario_emp04.wmf/es.po
1	1	po/scenario_emp04.wmf/eu.po
1	1	po/scenario_emp04.wmf/fa.po
1	1	po/scenario_emp04.wmf/fi.po
1	1	po/scenario_emp04.wmf/fr.po
1	1	po/scenario_emp04.wmf/fy.po
1	1	po/scenario_emp04.wmf/ga.po
1	1	po/scenario_emp04.wmf/gd.po
1	1	po/scenario_emp04.wmf/gl.po
1	1	po/scenario_emp04.wmf/he.po
1	1	po/scenario_emp04.wmf/hi.po
1	1	po/scenario_emp04.wmf/hr.po
1	1	po/scenario_emp04.wmf/hu.po
1	1	po/scenario_emp04.wmf/id.po
1	1	po/scenario_emp04.wmf/ig.po
1	1	po/scenario_emp04.wmf/it.po
1	1	po/scenario_emp04.wmf/ja.po
1	1	po/scenario_emp04.wmf/ka.po
1	1	po/scenario_emp04.wmf/ko.po
1	1	po/scenario_emp04.wmf/krl.po
1	1	po/scenario_emp04.wmf/la.po
1	1	po/scenario_emp04.wmf/lt.po
1	1	po/scenario_emp04.wmf/ms.po
1	1	po/scenario_emp04.wmf/nb.po
1	1	po/scenario_emp04.wmf/nds.po
1	1	po/scenario_emp04.wmf/nl.po
1	1	po/scenario_emp04.wmf/nn.po
1	1	po/scenario_emp04.wmf/pl.po
1	1	po/scenario_emp04.wmf/pt.po
1	1	po/scenario_emp04.wmf/pt_BR.po
1	1	po/scenario_emp04.wmf/ro.po
1	1	po/scenario_emp04.wmf/ru.po
1	1	po/scenario_emp04.wmf/scenario_emp04.wmf.pot
1	1	po/scenario_emp04.wmf/sk.po
1	1	po/scenario_emp04.wmf/sl.po
1	1	po/scenario_emp04.wmf/sr.po
1	1	po/scenario_emp04.wmf/sr_RS.po
1	1	po/scenario_emp04.wmf/sv.po
1	1	po/scenario_emp04.wmf/tr.po
1	1	po/scenario_emp04.wmf/uk.po
1	1	po/scenario_emp04.wmf/zh_CN.po
1	1	po/scenario_emp04.wmf/zh_TW.po
1	1	po/scenario_fri01.wmf/scenario_fri01.wmf.pot
1	1	po/scenario_fri02.wmf/scenario_fri02.wmf.pot
1	1	po/scenario_fri03.wmf/scenario_fri03.wmf.pot
1	1	po/scenario_fri04.wmf/ar.po
1	1	po/scenario_fri04.wmf/bg.po
1	1	po/scenario_fri04.wmf/br.po
1	1	po/scenario_fri04.wmf/ca.po
1	1	po/scenario_fri04.wmf/cs.po
1	1	po/scenario_fri04.wmf/da.po
1	1	po/scenario_fri04.wmf/de.po
1	1	po/scenario_fri04.wmf/el.po
1	1	po/scenario_fri04.wmf/en_GB.po
1	1	po/scenario_fri04.wmf/en_US.po
1	1	po/scenario_fri04.wmf/eo.po
1	1	po/scenario_fri04.wmf/es.po
1	1	po/scenario_fri04.wmf/eu.po
1	1	po/scenario_fri04.wmf/fa.po
1	1	po/scenario_fri04.wmf/fi.po
1	1	po/scenario_fri04.wmf/fr.po
1	1	po/scenario_fri04.wmf/fy.po
1	1	po/scenario_fri04.wmf/ga.po
1	1	po/scenario_fri04.wmf/gd.po
1	1	po/scenario_fri04.wmf/gl.po
1	1	po/scenario_fri04.wmf/he.po
1	1	po/scenario_fri04.wmf/hi.po
1	1	po/scenario_fri04.wmf/hr.po
1	1	po/scenario_fri04.wmf/hu.po
1	1	po/scenario_fri04.wmf/id.po
1	1	po/scenario_fri04.wmf/ig.po
1	1	po/scenario_fri04.wmf/it.po
1	1	po/scenario_fri04.wmf/ja.po
1	1	po/scenario_fri04.wmf/ka.po
1	1	po/scenario_fri04.wmf/ko.po
1	1	po/scenario_fri04.wmf/krl.po
1	1	po/scenario_fri04.wmf/la.po
1	1	po/scenario_fri04.wmf/lt.po
1	1	po/scenario_fri04.wmf/ms.po
1	1	po/scenario_fri04.wmf/nb.po
1	1	po/scenario_fri04.wmf/nds.po
1	1	po/scenario_fri04.wmf/nl.po
1	1	po/scenario_fri04.wmf/nn.po
1	1	po/scenario_fri04.wmf/pl.po
1	1	po/scenario_fri04.wmf/pt.po
1	1	po/scenario_fri04.wmf/pt_BR.po
1	1	po/scenario_fri04.wmf/ro.po
1	1	po/scenario_fri04.wmf/ru.po
1	1	po/scenario_fri04.wmf/scenario_fri04.wmf.pot
1	1	po/scenario_fri04.wmf/sk.po
1	1	po/scenario_fri04.wmf/sl.po
1	1	po/scenario_fri04.wmf/sr.po
1	1	po/scenario_fri04.wmf/sr_RS.po
1	1	po/scenario_fri04.wmf/sv.po
1	1	po/scenario_fri04.wmf/tr.po
1	1	po/scenario_fri04.wmf/uk.po
1	1	po/scenario_fri04.wmf/zh_CN.po
1	1	po/scenario_fri04.wmf/zh_TW.po
1	1	po/scenario_fri05.wmf/scenario_fri05.wmf.pot
1	1	po/scenario_tutorial01_basic_control.wmf/ar.po
1	1	po/scenario_tutorial01_basic_control.wmf/bg.po
1	1	po/scenario_tutorial01_basic_control.wmf/br.po
1	1	po/scenario_tutorial01_basic_control.wmf/ca.po
1	1	po/scenario_tutorial01_basic_control.wmf/cs.po
1	1	po/scenario_tutorial01_basic_control.wmf/da.po
1	1	po/scenario_tutorial01_basic_control.wmf/el.po
1	1	po/scenario_tutorial01_basic_control.wmf/en_GB.po
1	1	po/scenario_tutorial01_basic_control.wmf/en_US.po
1	1	po/scenario_tutorial01_basic_control.wmf/eo.po
1	1	po/scenario_tutorial01_basic_control.wmf/es.po
1	1	po/scenario_tutorial01_basic_control.wmf/eu.po
1	1	po/scenario_tutorial01_basic_control.wmf/fa.po
1	1	po/scenario_tutorial01_basic_control.wmf/fi.po
1	1	po/scenario_tutorial01_basic_control.wmf/fr.po
1	1	po/scenario_tutorial01_basic_control.wmf/fy.po
1	1	po/scenario_tutorial01_basic_control.wmf/ga.po
1	1	po/scenario_tutorial01_basic_control.wmf/gd.po
1	1	po/scenario_tutorial01_basic_control.wmf/gl.po
1	1	po/scenario_tutorial01_basic_control.wmf/he.po
1	1	po/scenario_tutorial01_basic_control.wmf/hi.po
1	1	po/scenario_tutorial01_basic_control.wmf/hr.po
1	1	po/scenario_tutorial01_basic_control.wmf/id.po
1	1	po/scenario_tutorial01_basic_control.wmf/ig.po
1	1	po/scenario_tutorial01_basic_control.wmf/it.po
1	1	po/scenario_tutorial01_basic_control.wmf/ja.po
1	1	po/scenario_tutorial01_basic_control.wmf/ka.po
1	1	po/scenario_tutorial01_basic_control.wmf/ko.po
1	1	po/scenario_tutorial01_basic_control.wmf/krl.po
1	1	po/scenario_tutorial01_basic_control.wmf/la.po
1	1	po/scenario_tutorial01_basic_control.wmf/lt.po
1	1	po/scenario_tutorial01_basic_control.wmf/ms.po
1	1	po/scenario_tutorial01_basic_control.wmf/nb.po
1	1	po/scenario_tutorial01_basic_control.wmf/nds.po
1	1	po/scenario_tutorial01_basic_control.wmf/nl.po
1	1	po/scenario_tutorial01_basic_control.wmf/nn.po
1	1	po/scenario_tutorial01_basic_control.wmf/pl.po
1	1	po/scenario_tutorial01_basic_control.wmf/pt.po
1	1	po/scenario_tutorial01_basic_control.wmf/pt_BR.po
1	1	po/scenario_tutorial01_basic_control.wmf/ro.po
1	1	po/scenario_tutorial01_basic_control.wmf/scenario_tutorial01_basic_control.wmf.pot
1	1	po/scenario_tutorial01_basic_control.wmf/sk.po
1	1	po/scenario_tutorial01_basic_control.wmf/sl.po
1	1	po/scenario_tutorial01_basic_control.wmf/sr.po
1	1	po/scenario_tutorial01_basic_control.wmf/sr_RS.po
1	1	po/scenario_tutorial01_basic_control.wmf/sv.po
1	1	po/scenario_tutorial01_basic_control.wmf/tr.po
1	1	po/scenario_tutorial01_basic_control.wmf/uk.po
1	1	po/scenario_tutorial01_basic_control.wmf/zh_CN.po
1	1	po/scenario_tutorial01_basic_control.wmf/zh_TW.po
1	1	po/scenario_tutorial02_warfare.wmf/ar.po
1	1	po/scenario_tutorial02_warfare.wmf/bg.po
1	1	po/scenario_tutorial02_warfare.wmf/br.po
1	1	po/scenario_tutorial02_warfare.wmf/ca.po
1	1	po/scenario_tutorial02_warfare.wmf/da.po
1	1	po/scenario_tutorial02_warfare.wmf/de.po
1	1	po/scenario_tutorial02_warfare.wmf/el.po
1	1	po/scenario_tutorial02_warfare.wmf/en_GB.po
1	1	po/scenario_tutorial02_warfare.wmf/en_US.po
1	1	po/scenario_tutorial02_warfare.wmf/eo.po
1	1	po/scenario_tutorial02_warfare.wmf/es.po
1	1	po/scenario_tutorial02_warfare.wmf/eu.po
1	1	po/scenario_tutorial02_warfare.wmf/fa.po
1	1	po/scenario_tutorial02_warfare.wmf/fi.po
1	1	po/scenario_tutorial02_warfare.wmf/fy.po
1	1	po/scenario_tutorial02_warfare.wmf/ga.po
1	1	po/scenario_tutorial02_warfare.wmf/gd.po
1	1	po/scenario_tutorial02_warfare.wmf/gl.po
1	1	po/scenario_tutorial02_warfare.wmf/he.po
1	1	po/scenario_tutorial02_warfare.wmf/hi.po
1	1	po/scenario_tutorial02_warfare.wmf/hr.po
1	1	po/scenario_tutorial02_warfare.wmf/id.po
1	1	po/scenario_tutorial02_warfare.wmf/ig.po
1	1	po/scenario_tutorial02_warfare.wmf/it.po
1	1	po/scenario_tutorial02_warfare.wmf/ja.po
1	1	po/scenario_tutorial02_warfare.wmf/ka.po
1	1	po/scenario_tutorial02_warfare.wmf/ko.po
1	1	po/scenario_tutorial02_warfare.wmf/krl.po
1	1	po/scenario_tutorial02_warfare.wmf/la.po
1	1	po/scenario_tutorial02_warfare.wmf/lt.po
1	1	po/scenario_tutorial02_warfare.wmf/ms.po
1	1	po/scenario_tutorial02_warfare.wmf/nb.po
1	1	po/scenario_tutorial02_warfare.wmf/nds.po
1	1	po/scenario_tutorial02_warfare.wmf/nl.po
1	1	po/scenario_tutorial02_warfare.wmf/nn.po
1	1	po/scenario_tutorial02_warfare.wmf/pl.po
1	1	po/scenario_tutorial02_warfare.wmf/pt.po
1	1	po/scenario_tutorial02_warfare.wmf/pt_BR.po
1	1	po/scenario_tutorial02_warfare.wmf/ro.po
1	1	po/scenario_tutorial02_warfare.wmf/scenario_tutorial02_warfare.wmf.pot
1	1	po/scenario_tutorial02_warfare.wmf/sk.po
1	1	po/scenario_tutorial02_warfare.wmf/sl.po
1	1	po/scenario_tutorial02_warfare.wmf/sr.po
1	1	po/scenario_tutorial02_warfare.wmf/sr_RS.po
1	1	po/scenario_tutorial02_warfare.wmf/tr.po
1	1	po/scenario_tutorial02_warfare.wmf/uk.po
1	1	po/scenario_tutorial02_warfare.wmf/zh_CN.po
1	1	po/scenario_tutorial02_warfare.wmf/zh_TW.po
1	1	po/scenario_tutorial03_seafaring.wmf/ar.po
1	1	po/scenario_tutorial03_seafaring.wmf/bg.po
1	1	po/scenario_tutorial03_seafaring.wmf/br.po
1	1	po/scenario_tutorial03_seafaring.wmf/ca.po
1	1	po/scenario_tutorial03_seafaring.wmf/da.po
1	1	po/scenario_tutorial03_seafaring.wmf/de.po
1	1	po/scenario_tutorial03_seafaring.wmf/el.po
1	1	po/scenario_tutorial03_seafaring.wmf/en_GB.po
1	1	po/scenario_tutorial03_seafaring.wmf/en_US.po
1	1	po/scenario_tutorial03_seafaring.wmf/eo.po
1	1	po/scenario_tutorial03_seafaring.wmf/es.po
1	1	po/scenario_tutorial03_seafaring.wmf/eu.po
1	1	po/scenario_tutorial03_seafaring.wmf/fa.po
1	1	po/scenario_tutorial03_seafaring.wmf/fy.po
1	1	po/scenario_tutorial03_seafaring.wmf/ga.po
1	1	po/scenario_tutorial03_seafaring.wmf/gd.po
1	1	po/scenario_tutorial03_seafaring.wmf/gl.po
1	1	po/scenario_tutorial03_seafaring.wmf/he.po
1	1	po/scenario_tutorial03_seafaring.wmf/hi.po
1	1	po/scenario_tutorial03_seafaring.wmf/hr.po
1	1	po/scenario_tutorial03_seafaring.wmf/hu.po
1	1	po/scenario_tutorial03_seafaring.wmf/id.po
1	1	po/scenario_tutorial03_seafaring.wmf/ig.po
1	1	po/scenario_tutorial03_seafaring.wmf/it.po
1	1	po/scenario_tutorial03_seafaring.wmf/ja.po
1	1	po/scenario_tutorial03_seafaring.wmf/ka.po
1	1	po/scenario_tutorial03_seafaring.wmf/ko.po
1	1	po/scenario_tutorial03_seafaring.wmf/krl.po
1	1	po/scenario_tutorial03_seafaring.wmf/la.po
1	1	po/scenario_tutorial03_seafaring.wmf/lt.po
1	1	po/scenario_tutorial03_seafaring.wmf/ms.po
1	1	po/scenario_tutorial03_seafaring.wmf/nb.po
1	1	po/scenario_tutorial03_seafaring.wmf/nds.po
1	1	po/scenario_tutorial03_seafaring.wmf/nn.po
1	1	po/scenario_tutorial03_seafaring.wmf/pl.po
1	1	po/scenario_tutorial03_seafaring.wmf/pt.po
1	1	po/scenario_tutorial03_seafaring.wmf/pt_BR.po
1	1	po/scenario_tutorial03_seafaring.wmf/ro.po
1	1	po/scenario_tutorial03_seafaring.wmf/ru.po
1	1	po/scenario_tutorial03_seafaring.wmf/scenario_tutorial03_seafaring.wmf.pot
1	1	po/scenario_tutorial03_seafaring.wmf/sk.po
1	1	po/scenario_tutorial03_seafaring.wmf/sl.po
1	1	po/scenario_tutorial03_seafaring.wmf/sr.po
1	1	po/scenario_tutorial03_seafaring.wmf/sr_RS.po
1	1	po/scenario_tutorial03_seafaring.wmf/sv.po
1	1	po/scenario_tutorial03_seafaring.wmf/tr.po
1	1	po/scenario_tutorial03_seafaring.wmf/uk.po
1	1	po/scenario_tutorial03_seafaring.wmf/zh_CN.po
1	1	po/scenario_tutorial03_seafaring.wmf/zh_TW.po
1	1	po/scenario_tutorial04_economy.wmf/ar.po
1	1	po/scenario_tutorial04_economy.wmf/bg.po
1	1	po/scenario_tutorial04_economy.wmf/br.po
1	1	po/scenario_tutorial04_economy.wmf/ca.po
1	1	po/scenario_tutorial04_economy.wmf/da.po
1	1	po/scenario_tutorial04_economy.wmf/de.po
1	1	po/scenario_tutorial04_economy.wmf/el.po
1	1	po/scenario_tutorial04_economy.wmf/en_GB.po
1	1	po/scenario_tutorial04_economy.wmf/en_US.po
1	1	po/scenario_tutorial04_economy.wmf/eo.po
1	1	po/scenario_tutorial04_economy.wmf/es.po
1	1	po/scenario_tutorial04_economy.wmf/eu.po
1	1	po/scenario_tutorial04_economy.wmf/fa.po
1	1	po/scenario_tutorial04_economy.wmf/fi.po
1	1	po/scenario_tutorial04_economy.wmf/fr.po
1	1	po/scenario_tutorial04_economy.wmf/fy.po
1	1	po/scenario_tutorial04_economy.wmf/ga.po
1	1	po/scenario_tutorial04_economy.wmf/gd.po
1	1	po/scenario_tutorial04_economy.wmf/gl.po
1	1	po/scenario_tutorial04_economy.wmf/he.po
1	1	po/scenario_tutorial04_economy.wmf/hi.po
1	1	po/scenario_tutorial04_economy.wmf/hr.po
1	1	po/scenario_tutorial04_economy.wmf/hu.po
1	1	po/scenario_tutorial04_economy.wmf/id.po
1	1	po/scenario_tutorial04_economy.wmf/ig.po
1	1	po/scenario_tutorial04_economy.wmf/it.po
1	1	po/scenario_tutorial04_economy.wmf/ja.po
1	1	po/scenario_tutorial04_economy.wmf/ka.po
1	1	po/scenario_tutorial04_economy.wmf/ko.po
1	1	po/scenario_tutorial04_economy.wmf/krl.po
1	1	po/scenario_tutorial04_economy.wmf/la.po
1	1	po/scenario_tutorial04_economy.wmf/lt.po
1	1	po/scenario_tutorial04_economy.wmf/ms.po
1	1	po/scenario_tutorial04_economy.wmf/nb.po
1	1	po/scenario_tutorial04_economy.wmf/nds.po
1	1	po/scenario_tutorial04_economy.wmf/nl.po
1	1	po/scenario_tutorial04_economy.wmf/nn.po
1	1	po/scenario_tutorial04_economy.wmf/pl.po
1	1	po/scenario_tutorial04_economy.wmf/pt.po
1	1	po/scenario_tutorial04_economy.wmf/pt_BR.po
1	1	po/scenario_tutorial04_economy.wmf/ro.po
1	1	po/scenario_tutorial04_economy.wmf/scenario_tutorial04_economy.wmf.pot
1	1	po/scenario_tutorial04_economy.wmf/sk.po
1	1	po/scenario_tutorial04_economy.wmf/sl.po
1	1	po/scenario_tutorial04_economy.wmf/sr.po
1	1	po/scenario_tutorial04_economy.wmf/sr_RS.po
1	1	po/scenario_tutorial04_economy.wmf/sv.po
1	1	po/scenario_tutorial04_economy.wmf/tr.po
1	1	po/scenario_tutorial04_economy.wmf/uk.po
1	1	po/scenario_tutorial04_economy.wmf/zh_CN.po
1	1	po/scenario_tutorial04_economy.wmf/zh_TW.po
1	1	po/texts/nds.po
1	1	po/texts/texts.pot
1	1	po/training_wheels/ar.po
1	1	po/training_wheels/bg.po
1	1	po/training_wheels/br.po
1	1	po/training_wheels/ca.po
1	1	po/training_wheels/da.po
1	1	po/training_wheels/de.po
1	1	po/training_wheels/el.po
1	1	po/training_wheels/en_GB.po
1	1	po/training_wheels/en_US.po
1	1	po/training_wheels/eo.po
1	1	po/training_wheels/es.po
1	1	po/training_wheels/eu.po
1	1	po/training_wheels/fa.po
1	1	po/training_wheels/fi.po
1	1	po/training_wheels/fr.po
1	1	po/training_wheels/fy.po
1	1	po/training_wheels/ga.po
1	1	po/training_wheels/gd.po
1	1	po/training_wheels/gl.po
1	1	po/training_wheels/he.po
1	1	po/training_wheels/hi.po
1	1	po/training_wheels/hr.po
1	1	po/training_wheels/hu.po
1	1	po/training_wheels/id.po
1	1	po/training_wheels/ig.po
1	1	po/training_wheels/it.po
1	1	po/training_wheels/ja.po
1	1	po/training_wheels/ka.po
1	1	po/training_wheels/ko.po
1	1	po/training_wheels/krl.po
1	1	po/training_wheels/la.po
1	1	po/training_wheels/lt.po
1	1	po/training_wheels/ms.po
1	1	po/training_wheels/nb.po
1	1	po/training_wheels/nds.po
1	1	po/training_wheels/nl.po
1	1	po/training_wheels/nn.po
1	1	po/training_wheels/pl.po
1	1	po/training_wheels/pt.po
1	1	po/training_wheels/pt_BR.po
1	1	po/training_wheels/ro.po
1	1	po/training_wheels/sk.po
1	1	po/training_wheels/sl.po
1	1	po/training_wheels/sr.po
1	1	po/training_wheels/sr_RS.po
1	1	po/training_wheels/sv.po
1	1	po/training_wheels/tr.po
1	1	po/training_wheels/training_wheels.pot
1	1	po/training_wheels/uk.po
1	1	po/training_wheels/zh_CN.po
1	1	po/training_wheels/zh_TW.po
60	60	po/tribes/it.po
1	1	po/tribes/tribes.pot
1	1	po/tribes_encyclopedia/tribes_encyclopedia.pot
2	2	po/widelands/de.po
38	23	po/widelands/widelands.pot
1	1	po/widelands_console/ar.po
1	1	po/widelands_console/bg.po
1	1	po/widelands_console/br.po
1	1	po/widelands_console/ca.po
1	1	po/widelands_console/cs.po
1	1	po/widelands_console/da.po
1	1	po/widelands_console/de.po
1	1	po/widelands_console/el.po
1	1	po/widelands_console/en_GB.po
1	1	po/widelands_console/en_US.po
1	1	po/widelands_console/eo.po
1	1	po/widelands_console/es.po
1	1	po/widelands_console/eu.po
1	1	po/widelands_console/fa.po
1	1	po/widelands_console/fi.po
1	1	po/widelands_console/fr.po
1	1	po/widelands_console/fy.po
1	1	po/widelands_console/ga.po
1	1	po/widelands_console/gd.po
1	1	po/widelands_console/gl.po
1	1	po/widelands_console/he.po
1	1	po/widelands_console/hi.po
1	1	po/widelands_console/hr.po
1	1	po/widelands_console/hu.po
1	1	po/widelands_console/id.po
1	1	po/widelands_console/ig.po
1	1	po/widelands_console/it.po
1	1	po/widelands_console/ja.po
1	1	po/widelands_console/ka.po
1	1	po/widelands_console/ko.po
1	1	po/widelands_console/krl.po
1	1	po/widelands_console/la.po
1	1	po/widelands_console/lt.po
1	1	po/widelands_console/ms.po
1	1	po/widelands_console/nb.po
1	1	po/widelands_console/nds.po
1	1	po/widelands_console/nl.po
1	1	po/widelands_console/nn.po
1	1	po/widelands_console/pl.po
1	1	po/widelands_console/pt.po
1	1	po/widelands_console/pt_BR.po
1	1	po/widelands_console/ro.po
1	1	po/widelands_console/sk.po
1	1	po/widelands_console/sl.po
1	1	po/widelands_console/sr.po
1	1	po/widelands_console/sr_RS.po
1	1	po/widelands_console/tr.po
1	1	po/widelands_console/uk.po
1	1	po/widelands_console/widelands_console.pot
1	1	po/widelands_console/zh_CN.po
1	1	po/widelands_console/zh_TW.po
1	1	po/widelands_editor/widelands_editor.pot
1	1	po/win_conditions/ar.po
1	1	po/win_conditions/bg.po
1	1	po/win_conditions/br.po
1	1	po/win_conditions/ca.po
1	1	po/win_conditions/cs.po
1	1	po/win_conditions/da.po
1	1	po/win_conditions/de.po
1	1	po/win_conditions/el.po
1	1	po/win_conditions/en_GB.po
1	1	po/win_conditions/en_US.po
1	1	po/win_conditions/eo.po
1	1	po/win_conditions/es.po
1	1	po/win_conditions/eu.po
1	1	po/win_conditions/fa.po
1	1	po/win_conditions/fi.po
1	1	po/win_conditions/fr.po
1	1	po/win_conditions/fy.po
1	1	po/win_conditions/ga.po
1	1	po/win_conditions/gd.po
1	1	po/win_conditions/gl.po
1	1	po/win_conditions/he.po
1	1	po/win_conditions/hi.po
1	1	po/win_conditions/hr.po
1	1	po/win_conditions/hu.po
1	1	po/win_conditions/id.po
1	1	po/win_conditions/ig.po
1	1	po/win_conditions/ja.po
1	1	po/win_conditions/ka.po
1	1	po/win_conditions/ko.po
1	1	po/win_conditions/krl.po
1	1	po/win_conditions/la.po
1	1	po/win_conditions/lt.po
1	1	po/win_conditions/ms.po
1	1	po/win_conditions/nb.po
1	1	po/win_conditions/nds.po
1	1	po/win_conditions/nl.po
1	1	po/win_conditions/nn.po
1	1	po/win_conditions/pl.po
1	1	po/win_conditions/pt.po
1	1	po/win_conditions/pt_BR.po
1	1	po/win_conditions/ro.po
1	1	po/win_conditions/ru.po
1	1	po/win_conditions/sk.po
1	1	po/win_conditions/sl.po
1	1	po/win_conditions/sr.po
1	1	po/win_conditions/sr_RS.po
1	1	po/win_conditions/tr.po
1	1	po/win_conditions/uk.po
1	1	po/win_conditions/win_conditions.pot
1	1	po/win_conditions/zh_CN.po
1	1	po/win_conditions/zh_TW.po
1	1	po/world/ar.po
1	1	po/world/bg.po
1	1	po/world/br.po
1	1	po/world/ca.po
1	1	po/world/cs.po
1	1	po/world/da.po
1	1	po/world/de.po
1	1	po/world/el.po
1	1	po/world/en_GB.po
1	1	po/world/en_US.po
1	1	po/world/eo.po
1	1	po/world/es.po
1	1	po/world/eu.po
1	1	po/world/fa.po
1	1	po/world/fi.po
1	1	po/world/fr.po
1	1	po/world/fy.po
1	1	po/world/ga.po
1	1	po/world/gd.po
1	1	po/world/gl.po
1	1	po/world/he.po
1	1	po/world/hi.po
1	1	po/world/hr.po
1	1	po/world/hu.po
1	1	po/world/id.po
1	1	po/world/ig.po
1	1	po/world/it.po
1	1	po/world/ja.po
1	1	po/world/ka.po
1	1	po/world/ko.po
1	1	po/world/krl.po
1	1	po/world/la.po
1	1	po/world/lt.po
1	1	po/world/ms.po
1	1	po/world/nb.po
1	1	po/world/nds.po
1	1	po/world/nl.po
1	1	po/world/nn.po
1	1	po/world/pl.po
1	1	po/world/pt.po
1	1	po/world/pt_BR.po
1	1	po/world/ro.po
1	1	po/world/ru.po
1	1	po/world/sk.po
1	1	po/world/sl.po
1	1	po/world/sr.po
1	1	po/world/sr_RS.po
1	1	po/world/sv.po
1	1	po/world/tr.po
1	1	po/world/uk.po
1	1	po/world/world.pot
1	1	po/world/zh_CN.po
1	1	po/world/zh_TW.po
```
Preventing such vast, unreadable, useless diffs is the main point of skipping these changes.

**Comment by tothxa** [comment]
> I think PO files should also be skipped if they're timestamp-only updates – consider e.g. the most recent commit

That's syncing up with the previous POT update. I think it's better to do it if the POT slipped through to show that the PO is for the current POT, but shouldn't happen any more if POTs don't get such updates. (only the first time afterwards to get the last such POT change – *edit: though that can be prevented by manually pushing the POT file versions matching the PO timestamps in master to transifex before the next automatic run*)

**Review by Noordfrees — APPROVED** [review]
Ok let's have it then :)

File: utils/merge_and_push_translations.sh (hunk 2 above)
Comment (Noordfrees) [reply utils/merge_and_push_translations.sh:102]: IMHO `grep`s are far more readable than `sed` commands

**Comment by tothxa** [comment]
> [POT-Creation-Date updates in PO files should only happen] the first time [after merging] to get the last such POT change

Oops, now tx (or git, or something else in the script?) plays tricks on us, and does the updates in parts… The updates on the 1st and 5th June changed about a thousand files each (there are 1700 all together in `po`), but on the 8th only 370 and today (10th) 97. So there are still about 1100 PO files needing update. If the next one doesn't do near 1000 of them then I'll make the script skip PO files too.
