### PR TITLE
Track descriptions instances

### LINKED ISSUE #4676: SoundHandler: Sound effect xy does not exist!
When saving a map the console prints endlessly:
~~~~
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 12 does not exist!
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 11 does not exist!
[00:54:08.273 real] ERROR: SoundHandler: Sound effect 9 does not exist!
[...]
~~~~

**To Reproduce**
1. Start editor and load map Kings and Queens
2. Save it

I got this endless prints also if i had create a new map and placed some critters, but i can't reproduce it this way.

**Version:**
 - OS: archlinux
 - Widelands Version: [ddcc509@3849_win_conditions] (Debug)

**Additional context**
A similar bugreport was #4258 but this was after saving a game.

### PR DESCRIPTION
**Pull request by matthiakl**
Fixes #4676 
Now hopefully without regression.

### CODE REVIEW

File: src/logic/map_objects/descriptions.cc [hunk 1]
```diff
@@ -117,7 +121,11 @@ Descriptions::Descriptions(LuaInterface* lua, const std::vector<AddOns::AddOnInf
 }
 
 Descriptions::~Descriptions() {
-	if (g_sh != nullptr) {
+	// We might have multiple Descriptions instances
+	// so the sounds should only go with the last one
+	// to prevent "Sound effect does not exist" errors
+	instances_--;
```
Comment (Noordfrees) [inline src/logic/map_objects/descriptions.cc:128]:
```suggestion
	assert(instances_ > 0);
	instances_--;
```

File: src/logic/map_objects/descriptions.h [hunk 2]
```diff
@@ -211,6 +211,8 @@ class Descriptions {
 	LuaInterface* lua_;  // Not owned
 	std::unique_ptr<DescriptionManager> description_manager_;
 	DISALLOW_COPY_AND_ASSIGN(Descriptions);
+
+	static int32_t instances_;
```
Comment (Noordfrees) [inline src/logic/map_objects/descriptions.h]:
```suggestion
	static uint32_t instances_;
```

**Review by Noordfrees — COMMENTED** [review]
Fix confirmed :)

**Review by Noordfrees — APPROVED** [review]

**Comment by Noordfrees** [comment]
Transient build failure, unrelated
