### PR TITLE
Fix segfault in multiselect editor tools

### LINKED ISSUE #5707: segfaults in the editor
**Describe the bug**
The editor is practically unusable because it segfaults on changing terrain or setting immovables or animals
(found while testing last commit to #5705, but comes from master)

**To Reproduce**
1. Start editor
2. Select Terrain, Immovable or Animals tool
3. Select item to use
4. (to make sure crash happens immediately, increase toolsize e.g to 8)
5. Start placing item
6. See error

**Expected behavior**
Terrain/immovable/animal should be placed

**Version:**
 - OS: antix/Debian buster + backports
 - Widelands Version: 1.2~git25974 (0fc809d@master) Debug

**Crash logs:**
 - [asan_log_animal.txt](https://github.com/widelands/widelands/files/10203334/asan_log_animal.txt)
 - [asan_log_immovable.txt](https://github.com/widelands/widelands/files/10203335/asan_log_immovable.txt)
 - [asan_log_terrain.txt](https://github.com/widelands/widelands/files/10203336/asan_log_terrain.txt)
 - [dbglog_animals.txt](https://github.com/widelands/widelands/files/10203337/dbglog_animals.txt)
 - [dbglog_immovable.txt](https://github.com/widelands/widelands/files/10203338/dbglog_immovable.txt)
 - [dbglog_terrain.txt](https://github.com/widelands/widelands/files/10203339/dbglog_terrain.txt)

### PR DESCRIPTION
**Pull request by Noordfrees**
Fixes #5707

### CODE REVIEW

File: src/editor/tools/multi_select.h [hunk 1]
```diff
@@ -52,17 +52,12 @@ struct MultiSelect {
...
-				return item;
-			}
-			--rand_value;
+		if (get_nr_enabled() < 1) {
+			return -1;
 		}
-
-		return -1;
+		auto it = enabled_.begin();
+		std::advance(it, RNG::static_rand(get_nr_enabled()));
```
Comment (hessenfarmer) [inline src/editor/tools/multi_select.h:59]: as the result of static_rand is exclusive of the number of elements, I am not sure if the last element of all enabled elements will ever be picked.

**Review by hessenfarmer — APPROVED** [review]
Code LGTM. 
However one question / possible issue inline

File: src/editor/tools/multi_select.h (hunk 1 above)
Comment (Noordfrees) [reply src/editor/tools/multi_select.h:59]: Yes because indices are zero-based. If for example there are 5 elements, they are indexed 0,1,2,3,4. `static_rand` returns `(random number) % 5` which generates the numbers 0,1,2,3,4.
