### PR TITLE
Fix player end status handling

### LINKED ISSUE #5667: `PlayersManager::add_player_end_status` fails when player slots are closed
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check: __n (which is 3) >= this->size() (which is 3)
> Abgebrochen (Speicherabzug geschrieben)
> 

What could cause that? Occurs only in release build. In debug build, this error doesn't accour.

I use Multplayer game, with only AI players (Empire, Barbarians and Europeans) and me as Observer. Game mode is landlord.

I use parameter --ai_training and --auto_speed.

### LINKED ISSUE #5809: Assertion failed when destroying opponent HQ in multiplayer
Tested with 1.2~git26073 (e082880@master) Debug on Ubuntu 20.04 and Windows 10. Save game and reply attached.

When the yellow player's HQ at coordinates 142,182,4 is destroyed in a multiplayer game, the game crashes. Sometimes the server, other times the client.

`../src/logic/playersmanager.cc:97: void Widelands::PlayersManager::add_player_end_status(const Widelands::PlayerEndStatus&, bool): Assertion 'status.player > 0 && status.player <= number_of_players_' failed.`

**To reproduce**
1. [Download](https://www.widelands.org/maps/new-england/) the "New England" map.
1. Start a LAN/direct multiplayer game with the attached save. You do not need additional players to join.
2. The yellow HQ has been (or will soon be) destroyed. Wait for 10 seconds or so.
3. Game crashes.
[assertion_failed_bug.zip](https://github.com/widelands/widelands/files/10947337/assertion_failed_bug.zip)

### PR DESCRIPTION
**Pull request by tothxa**
**Type of change**
Bugfix

**Issue(s) closed**
Fixes #5667
Fixes #5809

**To reproduce**
Steps to reproduce the behavior which cause the bug in master but not in your branch:
1. Start a game with closed player slots (test both with single and multiplayer)
2. Resign all players
3. master crashes, with these changes it works

**Possible regressions**
Win conditions, game summary, game speed setting

**Additional context**
Alternative and extension of #5823

### CODE REVIEW

File: src/logic/playersmanager.cc [hunk 1]
```diff
@@ -87,34 +87,33 @@ Player* PlayersManager::add_player(PlayerNumber const player_number,
...
-
-	{
-		PlayerEndStatus& s = players_end_status_.at(status.player - 1);
-		if (!change_existing && s.player != 0) {
+	assert(status.player > 0);
+	const PlayerNumber& pn = status.player;
+	auto it = players_end_status_.find(pn);
+
+	if (it == players_end_status_.end()) {
+		players_end_status_.insert({pn, status});
```
Comment (tothxa) [inline src/logic/playersmanager.cc]: @Noordfrees Should/could this be emplace?

**Comment by tothxa** [comment]
There are more places where player numbers are iterated only up to number of players in the game. One I've found, and where I could trigger the problem is saving the game. (last player's end status is not saved if there is a closed slot: start multiplayer on a map that allows at least 4 players, pick last player, close a lower numbered slot, set rest to AI, start game, give up, save, reload: your end status is not set)

**Comment by tothxa** [comment]
OK, maybe it would be best to revert https://github.com/widelands/widelands/pull/5604/commits/2a27e73cf68a2394d18649112f35f7bddc909300 and do https://github.com/widelands/widelands/pull/5604#pullrequestreview-1169102400 (with map instead of vector :) but at this point I'm not sure which is easier: untangle #5604 or hunt down all downstreams that need updating.

**Comment by tothxa** [comment]
OK, I think this is the best of both worlds. Based on the diff of https://github.com/widelands/widelands/commit/2a27e73cf68a2394d18649112f35f7bddc909300 there shouldn't be more affected users…

File: src/logic/playersmanager.h [hunk 2]
```diff
@@ -92,12 +92,15 @@ class PlayersManager {
 	void add_player_end_status(const PlayerEndStatus& status, bool change_existing = false);
 
 	[[nodiscard]] const PlayerEndStatus* get_player_end_status(PlayerNumber player) const;
+	[[nodiscard]] const std::map<PlayerNumber, PlayerEndStatus>& get_players_end_status() {
```
Comment (hessenfarmer) [inline src/logic/playersmanager.h]: may we name this function get_all_players_end_status to avoid logical error due to a silly typo. (or any other name more distinguishable)

**Review by hessenfarmer — APPROVED** [review]
nice and much more elegant solution that I could have imagined. 
one small nit inline. 
Code LGTM. not tested yet.
will close my PR then

File: src/logic/playersmanager.h (hunk 2 above)
Comment (tothxa) [reply src/logic/playersmanager.h]: Indeed. Thanks.

**Comment by tothxa** [comment]
> nice and much more elegant solution that I could have imagined.

Thank you. :)

File: src/game_io/game_player_info_packet.cc [hunk 3]
```diff
@@ -182,19 +182,15 @@ void GamePlayerInfoPacket::write(FileSystem& fs, Game& game, MapObjectSaver* /*
...
-	fw.unsigned_8(end_status_list.size());
-	for (const PlayerEndStatus* status : end_status_list) {
-		fw.unsigned_8(status->player);
-		fw.unsigned_8(static_cast<uint8_t>(status->result));
-		status->time.save(fw);
-		fw.c_string(status->info.c_str());
+	const std::map<Widelands::PlayerNumber, Widelands::PlayerEndStatus>& end_status_map =
+	   game.player_manager()->get_all_players_end_status();
+	fw.unsigned_8(end_status_map.size());
+	for (const auto it : end_status_map) {
```
Comment (hessenfarmer) [inline src/game_io/game_player_info_packet.cc]:
```suggestion
	for (auto it = end_status_map.begin(), it != end_status_map.end(), ++it) {
```
maybe this fixes clang tidy

**Review by hessenfarmer — APPROVED** [review]
tested it and works perfectly.

small suggstion for clang tidy
