### PR TITLE
More box layouting

### LINKED ISSUE #947: Fullscreen Menu overhaul
Since we are still short for text space in the fullscreen menus, I have started doing an overhaul. I am aiming to make the layout more uniform while I'm at it, and to use variables and relative positioning to make it more easy to change stuff in the future.

The first step was to have a look at the menus where a map or savegame is selected. The biggest change is to rearrange the OK/Back buttons, because they were eating up a lot of screen space. I have also cleaned up the checkboxes in the map selection for a new game. Note that they still don't line up in a vertical grid; this is on purpose to make more room for translations.

I am attaching 3 screenshots so you can see where I'm heading and veto anything you think needs fixing without having to compile. I'd rather not change anything for these unless I have to though.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-10-05T15:37:28Z
 * owner: gunchleoc
 * assignee: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1377660

### LINKED ISSUE #956: Fullscreen Menus cannot relayout themselves
Now that we can change into fullscreen with 'f' everywhere it becomes apparent to the user that fullscreen menus never relayout themselves. The fix is very easy:

Either:
- Each UI element must be hold on to as a member.
- A layout() method puts them into the correct place. This will be called on resolution changes.

Or:
- The menus are switched to using UI::Box which can already layout themselves. This will make working with them in the future also easier. This is more work.

See also: https://bugs.launchpad.net/widelands/+bug/1459529

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-12-03T08:13:32Z
 * owner: sirver
 * assignee: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1398733

### LINKED ISSUE #3985: Campaign scenario selection screen text overlaps at 800x600 resolution
## Describe the bug

UI is barely tested when it comes to window mode and low resolution (800x600). E.g. text does not fit in the box.
It applies mainly to the scenario description. Difficulty selector is affected as well.

### Bug 1

1. Run **Widelands** in window mode (800x600)
2. Select `Single Player`
3. Select `Campaigns`
4. Select `Empire`

### Bug 2

1. Run **Widelands** in window mode (800x600)
2. Select `Single Player`
3. Select `Campaigns`
4. Select `Frisians`
5. Select `Difficulty`

## Actual behavior

widelands-21-rc1-window-scenario

widelands-21-rc1-window-scenario-difficulty

## Expected behavior
There should be a scroll bar, like in the `campaign` screen.

widelands-21-rc1-window-campaign

## Version:
 - OS: EL7
 - Widelands Version: `Build 21~rc1`, flatpak

## Additional context

`Build 20` is not affected, but only because descriptions are shorter there. There is also no difficulty selector.

### LINKED ISSUE #4275: atlantean scenario selection screen is layouted wrong
grafik

further more the text between choose a campaign and chosse a scenario jumps a bit down which does not look good
in the other tribes the distances between "choose a scenario" and the name of the campaign differs as well but is not overlapping

### PR DESCRIPTION
**Pull request by jmoerschbach**
Fixes #947 
Fixes #956 
Fixes #3985
Fixes #4275
Superseeds #4054
 #4274 should be merged first

Introduce a small inheritance tree of classes that use nested UI::Boxes to avoid any magic numbers and make all setup screens look alike regarding basic widget alignment, padding, etc

SinglePlayer:
- [x] FullscreenMenuCampaignSelect ("Choose a campaign")
- [x] FullscreenMenuScenarioSelect("Choose a scenario")
- [x] FullscreenMenuScenarioSelect("Choose a tutorial")
- [x] FullscreenMenuMapSelect("Choose a map")
- [x] FullscreenMenuLaunchSPG("Launch game")
- [x] FullscreenMenuLoadGame("Choose a saved game") (this should be refactored in a follow up branch imho)

MultiPlayer
- [x] FullscreenMenuInternetLobby("Metaserver Lobby")
- [x] FullscreenMenuNetSetupLAN("Begin Network Game")
- [x] FullscreenMenuLaunchMPG("Multiplayer Game Setup")

Watch replay
- [x] FullscreenMenuLoadGame("Choose a replay")

- [x] scaling of widgets
- [x] namespace

### CODE REVIEW

**Comment by Noordfrees** [comment]
Are you also going to convert the LoginBox to box layout here? (No is a perfectly good answer, in this case I will do it)

**Comment by jmoerschbach** [comment]
> 
> 
> Are you also going to convert the LoginBox to box layout here? (No is a perfectly good answer, in this case I will do it)

No :D

**Comment by Noordfrees** [comment]
Okay, I converted and polished it in my branch now :) 

How long do you estimate until this branch is ready for merging? My refactoring work will have much larger scope than I anticipated so the bigger part needs to wait until this is in – if this branch still takes a while I'd split mine into two pieces to minimize the amount of coding where we risk stepping on each other's toes :)

**Comment by jmoerschbach** [comment]
> 
> 
> Okay, I converted and polished it in my branch now :)
> 
> How long do you estimate until this branch is ready for merging? My refactoring work will have much larger scope than I anticipated so the bigger part needs to wait until this is in – if this branch still takes a while I'd split mine into two pieces to minimize the amount of coding where we risk stepping on each other's toes :)

Hopefully by the end of this week (including weekend) :)

**Comment by Noordfrees** [comment]
Version 1.0~git25071[3ee64c3@HEAD] (Debug): Pressing N or P in the main menu gives me this crash
```
widelands: ../src/ui_basic/box.cc:303: void UI::Box::add(UI::Panel*, UI::Box::Resizing, UI::Align): Assertion `panel->get_parent() == this' failed.
```

**Comment by jmoerschbach** [comment]
> 
> 
> Version 1.0~git25071[[3ee64c3](https://github.com/widelands/widelands/commit/3ee64c33f9b9fddc836de608cc1aa6a676fe4f58)@HEAD] (Debug): Pressing N or P in the main menu gives me this crash
> 
> ```
> widelands: ../src/ui_basic/box.cc:303: void UI::Box::add(UI::Panel*, UI::Box::Resizing, UI::Align): Assertion `panel->get_parent() == this' failed.
> ```

thx, fixed (the recently added assert to UI::Box is helpful it seems...^^)

**Comment by Noordfrees** [comment]
This window needs to become a child of the parent window's parent:
shot0001

Oh and can you please make the player setup rows taller (about twice as large as now)? They're a pretty small click target atm.

**Comment by Noordfrees** [comment]
There seems to be some kind of trouble with this dropdown:
shot0000

**Comment by jmoerschbach** [comment]
> 
> 
> This window needs to become a child of the parent window's parent:
> shot0001
>
changed the parent, but not quite sure if I did the right thing, I don't see a major difference. 
> 
> Oh and can you please make the player setup rows taller (about twice as large as now)? They're a pretty small click target atm.

done. not sure if I like though, now these widgets are once again special...

**Comment by jmoerschbach** [comment]
> 
> 
> There seems to be some kind of trouble with this dropdown:
> shot0000

hmm, I can reproduce similiar issues on master (e.g. toggle fullscreen when dropdown is "open" aka the list of options is visible)
I don't think this is a problem of this branch, maybe a dropdown vs modal window issue?

**Comment by Noordfrees** [comment]
UI-wise everything seems fine now :) 

I got this when entering the lobby and just waiting a few seconds:
```
[00:02:59.123 real] INFO: [00:02:59.123 real] INFO: InternetGaming: Sending login request.
[BufferedConnection] Starting networking thread
[00:02:59.167 real] INFO: InternetGaming: Client Nordfriese logged in at UTC Thu Nov  5 09:24:40 2020
[00:02:59.247 real] INFO: InternetGaming: Server time offset is 0 second(s).
[00:02:59.290 real] INFO: InternetGaming: Received a client list update with 17 items.
[00:02:59.290 real] INFO: InternetGaming: Received a game list update with 0 items.
[00:03:02.233 real] INFO: InternetGaming: Client update on metaserver.
[00:03:02.307 real] INFO: InternetGaming: Received a client list update with 17 items.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==15408==ERROR: AddressSanitizer: SEGV on unknown address 0x606199b047f0 (pc 0x55f9f8c40ffd bp 0x7ffe185f52f0 sp 0x7ffe185f52d0 T0)
==15408==The signal is caused by a READ memory access.
    #0 0x55f9f8c40ffd in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::_M_set_node(InternetGame**) /usr/include/c++/10/bits/stl_deque.h:263
    #1 0x55f9f8c41c78 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::operator+=(long) /usr/include/c++/10/bits/stl_deque.h:239
    #2 0x55f9f8c411f9 in std::operator+(std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*> const&, long) /usr/include/c++/10/bits/stl_deque.h:378
    #3 0x55f9f8c40c42 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::operator[](long) const /usr/include/c++/10/bits/stl_deque.h:252
    #4 0x55f9f8c40140 in std::deque<InternetGame, std::allocator<InternetGame> >::operator[](unsigned long) const /usr/include/c++/10/bits/stl_deque.h:1345
    #5 0x55f9f8c3fe18 in UI::Listselect<InternetGame>::get_selected() const ../src/ui_basic/listselect.h:194
    #6 0x55f9f8c2cc11 in FsMenu::FullscreenMenuInternetLobby::server_selected() ../src/ui_fsmenu/internet_lobby.cc:371
    #7 0x55f9f8c25fe0 in operator() ../src/ui_fsmenu/internet_lobby.cc:177
    #8 0x55f9f8c381bd in invoke /usr/include/boost/function/function_template.hpp:158
    #9 0x55f9f8a8b65e in boost::function1<void, unsigned int>::operator()(unsigned int) const /usr/include/boost/function/function_template.hpp:763
    #10 0x55f9f8a8b42c in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (unsigned int)>, 0u, unsigned int&>(boost::function<void (unsigned int)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<unsigned int&> const&, boost::enable_if<boost::is_void<boost::function<void (unsigned int)>::result_type>, void>::type*) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
    #11 0x55f9f8a8b34b in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (unsigned int)>, unsigned int&, 1ul>(boost::function<void (unsigned int)>&, std::tuple<unsigned int&> const&, mpl_::size_t<1ul>) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
    #12 0x55f9f8a8b137 in boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
    #13 0x55f9f8a8a70a in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >::dereference() const /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
    #14 0x55f9f8a8939b in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) /usr/include/boost/iterator/iterator_facade.hpp:550
    #15 0x55f9f8a889d7 in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const /usr/include/boost/iterator/iterator_facade.hpp:656
    #16 0x55f9f8a87105 in void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const /usr/include/boost/signals2/optional_last_value.hpp:57
    #17 0x55f9f8a85061 in void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
    #18 0x55f9f8a82da0 in boost::signals2::detail::signal_impl<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) /usr/include/boost/signals2/detail/signal_template.hpp:243
    #19 0x55f9f8a80fc0 in boost::signals2::signal<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) /usr/include/boost/signals2/detail/signal_template.hpp:722
    #20 0x55f9f8a78e70 in UI::BaseListselect::select(unsigned int) ../src/ui_basic/listselect.cc:227
    #21 0x55f9f8a7ce8f in UI::BaseListselect::handle_mousewheel(unsigned int, int, int) ../src/ui_basic/listselect.cc:461
    #22 0x55f9f8aa82ae in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1013
    #23 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #24 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #25 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #26 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #27 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #28 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #29 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
    #30 0x55f9f8aa9a21 in UI::Panel::ui_mousewheel(unsigned int, int, int) ../src/ui_basic/panel.cc:1246
    #31 0x55f9f83546b7 in WLApplication::handle_input(InputCallback const*) ../src/wlapplication.cc:644
    #32 0x55f9f8aa0a6b in UI::Panel::do_run() ../src/ui_basic/panel.cc:190
    #33 0x55f9f8382f67 in MenuTarget UI::Panel::run<MenuTarget>() ../src/ui_basic/panel.h:104
    #34 0x55f9f836552e in WLApplication::mainmenu_multiplayer(FullscreenMenuMain&, bool) ../src/wlapplication.cc:1355
    #35 0x55f9f8363045 in WLApplication::mainmenu() ../src/wlapplication.cc:1207
    #36 0x55f9f83525ef in WLApplication::run() ../src/wlapplication.cc:500
    #37 0x55f9f834cc91 in main ../src/main.cc:42
    #38 0x7fe4c72aecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #39 0x55f9f834cb2d in _start (/home/benedikt/wl/_multithreading_old/widelands+0x48eb2d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/10/bits/stl_deque.h:263 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::_M_set_node(InternetGame**)
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```
Version 1.0~git25075[00ca722@HEAD] (Debug)

File: src/ui_fsmenu/menu.h [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+	UI::Box main_box_, header_box_;
+	uint32_t standard_height_;
+};
+
+class TwoColumnsMenu : public BaseMenu {
+public:
+	TwoColumnsMenu(FullscreenMenuMain&,
+	               const std::string& name,
+	               const std::string& title,
+	               double right_column_width_factor = 1.0 / 3);
```
Comment (Noordfrees) [inline src/ui_fsmenu/menu.h]: Pull this value out into a `constexpr` which can also be reused below

File: src/ui_fsmenu/menu.h [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+#include "ui_basic/box.h"
+#include "ui_basic/button.h"
+#include "ui_basic/window.h"
+#include "ui_fsmenu/main.h"
+
+namespace FsMenu {
+constexpr int kPadding = 4;
+
+class BaseMenu : public UI::Window {
```
Comment (Noordfrees) [inline src/ui_fsmenu/menu.h:36]: Please write a few lines of documentation for each class in this file: What does the respective menu look like? What widgets and features does it offer or lack? How to choose which one to use when implementing a new window?

File: src/ui_fsmenu/internet_lobby.h [hunk 3]
```diff
@@ -69,8 +69,6 @@ class FullscreenMenuInternetLobby : public FullscreenMenuLoadMapOrGame {
 
 	FullscreenMenuMain& fsmm_;
```
Comment (Noordfrees) [inline src/ui_fsmenu/internet_lobby.h]: You could now get rid of the several local `fsmm_` variables and make this a `protected` variable in  `BaseMenu`

**Review by Noordfrees — COMMENTED** [review]
Code looking straightforward and nicely structured, a few suggestions inline

**Comment by jmoerschbach** [comment]
> 
> 
> UI-wise everything seems fine now :)
> 
> I got this when entering the lobby and just waiting a few seconds:
> 
> ```
> [00:02:59.123 real] INFO: [00:02:59.123 real] INFO: InternetGaming: Sending login request.
> [BufferedConnection] Starting networking thread
> [00:02:59.167 real] INFO: InternetGaming: Client Nordfriese logged in at UTC Thu Nov  5 09:24:40 2020
> [00:02:59.247 real] INFO: InternetGaming: Server time offset is 0 second(s).
> [00:02:59.290 real] INFO: InternetGaming: Received a client list update with 17 items.
> [00:02:59.290 real] INFO: InternetGaming: Received a game list update with 0 items.
> [00:03:02.233 real] INFO: InternetGaming: Client update on metaserver.
> [00:03:02.307 real] INFO: InternetGaming: Received a client list update with 17 items.
> AddressSanitizer:DEADLYSIGNAL
> =================================================================
> ==15408==ERROR: AddressSanitizer: SEGV on unknown address 0x606199b047f0 (pc 0x55f9f8c40ffd bp 0x7ffe185f52f0 sp 0x7ffe185f52d0 T0)
> ==15408==The signal is caused by a READ memory access.
>     #0 0x55f9f8c40ffd in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::_M_set_node(InternetGame**) /usr/include/c++/10/bits/stl_deque.h:263
>     #1 0x55f9f8c41c78 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::operator+=(long) /usr/include/c++/10/bits/stl_deque.h:239
>     #2 0x55f9f8c411f9 in std::operator+(std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*> const&, long) /usr/include/c++/10/bits/stl_deque.h:378
>     #3 0x55f9f8c40c42 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::operator[](long) const /usr/include/c++/10/bits/stl_deque.h:252
>     #4 0x55f9f8c40140 in std::deque<InternetGame, std::allocator<InternetGame> >::operator[](unsigned long) const /usr/include/c++/10/bits/stl_deque.h:1345
>     #5 0x55f9f8c3fe18 in UI::Listselect<InternetGame>::get_selected() const ../src/ui_basic/listselect.h:194
>     #6 0x55f9f8c2cc11 in FsMenu::FullscreenMenuInternetLobby::server_selected() ../src/ui_fsmenu/internet_lobby.cc:371
>     #7 0x55f9f8c25fe0 in operator() ../src/ui_fsmenu/internet_lobby.cc:177
>     #8 0x55f9f8c381bd in invoke /usr/include/boost/function/function_template.hpp:158
>     #9 0x55f9f8a8b65e in boost::function1<void, unsigned int>::operator()(unsigned int) const /usr/include/boost/function/function_template.hpp:763
>     #10 0x55f9f8a8b42c in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void (unsigned int)>, 0u, unsigned int&>(boost::function<void (unsigned int)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<unsigned int&> const&, boost::enable_if<boost::is_void<boost::function<void (unsigned int)>::result_type>, void>::type*) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:105
>     #11 0x55f9f8a8b34b in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void (unsigned int)>, unsigned int&, 1ul>(boost::function<void (unsigned int)>&, std::tuple<unsigned int&> const&, mpl_::size_t<1ul>) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
>     #12 0x55f9f8a8b137 in boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) const /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
>     #13 0x55f9f8a8a70a in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >::dereference() const /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
>     #14 0x55f9f8a8939b in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > const&) /usr/include/boost/iterator/iterator_facade.hpp:550
>     #15 0x55f9f8a889d7 in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const /usr/include/boost/iterator/iterator_facade.hpp:656
>     #16 0x55f9f8a87105 in void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const /usr/include/boost/signals2/optional_last_value.hpp:57
>     #17 0x55f9f8a85061 in void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, unsigned int>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (unsigned int), boost::function<void (unsigned int)> >, boost::signals2::mutex> >) const /usr/include/boost/signals2/detail/result_type_wrapper.hpp:64
>     #18 0x55f9f8a82da0 in boost::signals2::detail::signal_impl<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) /usr/include/boost/signals2/detail/signal_template.hpp:243
>     #19 0x55f9f8a80fc0 in boost::signals2::signal<void (unsigned int), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (unsigned int)>, boost::function<void (boost::signals2::connection const&, unsigned int)>, boost::signals2::mutex>::operator()(unsigned int) /usr/include/boost/signals2/detail/signal_template.hpp:722
>     #20 0x55f9f8a78e70 in UI::BaseListselect::select(unsigned int) ../src/ui_basic/listselect.cc:227
>     #21 0x55f9f8a7ce8f in UI::BaseListselect::handle_mousewheel(unsigned int, int, int) ../src/ui_basic/listselect.cc:461
>     #22 0x55f9f8aa82ae in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1013
>     #23 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #24 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #25 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #26 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #27 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #28 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #29 0x55f9f8aa81b1 in UI::Panel::do_mousewheel(unsigned int, int, int, Vector2<int>) ../src/ui_basic/panel.cc:1007
>     #30 0x55f9f8aa9a21 in UI::Panel::ui_mousewheel(unsigned int, int, int) ../src/ui_basic/panel.cc:1246
>     #31 0x55f9f83546b7 in WLApplication::handle_input(InputCallback const*) ../src/wlapplication.cc:644
>     #32 0x55f9f8aa0a6b in UI::Panel::do_run() ../src/ui_basic/panel.cc:190
>     #33 0x55f9f8382f67 in MenuTarget UI::Panel::run<MenuTarget>() ../src/ui_basic/panel.h:104
>     #34 0x55f9f836552e in WLApplication::mainmenu_multiplayer(FullscreenMenuMain&, bool) ../src/wlapplication.cc:1355
>     #35 0x55f9f8363045 in WLApplication::mainmenu() ../src/wlapplication.cc:1207
>     #36 0x55f9f83525ef in WLApplication::run() ../src/wlapplication.cc:500
>     #37 0x55f9f834cc91 in main ../src/main.cc:42
>     #38 0x7fe4c72aecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
>     #39 0x55f9f834cb2d in _start (/home/benedikt/wl/_multithreading_old/widelands+0x48eb2d)
> 
> AddressSanitizer can not provide additional info.
> SUMMARY: AddressSanitizer: SEGV /usr/include/c++/10/bits/stl_deque.h:263 in std::_Deque_iterator<InternetGame, InternetGame&, InternetGame*>::_M_set_node(InternetGame**)
> AddressSanitizer:DEADLYSIGNAL
> AddressSanitizer: nested bug in the same thread, aborting.
> ```
> 
> Version 1.0~git25075[[00ca722](https://github.com/widelands/widelands/commit/00ca722a7a8c5a9cfa389afae7c33cda79c7660a)@HEAD] (Debug)

hmm, I'm on windows/msys where I couldn't get asan working so far, so I cannot reproduce/verify.... ;( Is this reproducable? Only on this branch? I didn't touch any business logic I hope, so I am wondering...

**Review by Noordfrees — APPROVED** [review]
I can reproduce the segfault with another branch as well, will open a new issue for that. Code LGTM now :)

**Comment by Noordfrees** [comment]
Please merge master into this branch
