### PR TITLE
Delay AI initalization after scenario init

### LINKED ISSUE #4655: Scenario The Green Plateau crashes
There is a shipped map called "The Green Plateau". Trying to start it crashes the game.

**To Reproduce**
1. Start the map The Green Plateau

Result:
~~~~
[00:00:00.000 game] INFO: Forcing flag at (48, 14)
[00:00:00.000 game] INFO: Forcing flag at (42, 73)
[00:00:00.000 game] INFO: Forcing flag at (52, 27)
Speicherzugriffsfehler (Speicherabzug geschrieben)
~~~~

**Version:**
 - OS: archlinux
 - Widelands Version: [af82ca0@master] (Debug)

### PR DESCRIPTION
**Pull request by matthiakl**
Fixes #4655 

The scenario script uses some atlantean buildings, which are loaded when the script is executed. The AI does not get the new buildings and is lost:
`[/mnt/storage/Programme/widelands/src/ai/defaultai.cc:6330] Help: I (player 3 / tribe barbarians) do not know what to do with a atlanteans_tower` (Masked by some lua error)
So we wait for the commands at gametime 0 and start AI thinking at gametime 1.

### CODE REVIEW

File: src/ai/defaultai.cc [hunk 1]
```diff
@@ -102,7 +102,7 @@ DefaultAI::DefaultAI(Widelands::Game& ggame, Widelands::PlayerNumber const pid,
      player_(nullptr),
      tribe_(nullptr),
      attackers_count_(0),
-     next_ai_think_(0),
+     next_ai_think_(1),
```
Comment (Noordfrees) [inline src/ai/defaultai.cc:107]: Fix confirmed and working, code LGTM. This line needs a comment why this must not be 0 though or it might be changed again in the future by accident.

**Review by Noordfrees — APPROVED** [review]
