### PR TITLE
Disable keys for fullscreen and screenshot when changing shortcuts

### LINKED ISSUE #5001: Cannot assign shortcut for "Toggle Fullscreen" to any other function
Trying to assign Ctrl+F (toggle fullscreen default shortcut) to any other shortcut action available toggles fullscreen instead of showing the dialog which informs about conflicting shortcuts

**To Reproduce**
1. Go to Options
2. Click on Edit keyboard shortcuts
3. Click on Take screenshot (F11)
4. Assign Ctrl+F
5. Fullscreen is toggled

**Expected behavior**
Infobox informing about conflicting screenshot should be shown like for all other shortcut conflicts

**Screenshots**

**Version:**
 - OS: [e.g. Ubuntu 20-04]
 - Widelands Version: 1.1~git25396[42b5f0e@master]

### PR DESCRIPTION
**Pull request by tothxa**
fixes #5001

### CODE REVIEW

File: src/wlapplication.h [hunk 1]
```diff
@@ -178,6 +178,9 @@ struct WLApplication {
 	// Handle the given pressed key. Returns true when key was
 	// handled.
 	bool handle_key(bool down, const SDL_Keycode& keycode, int modifiers);
+	void enable_handle_key(bool enable_) {
+		handle_key_enabled = enable_;
```
Comment (Noordfrees) [inline src/wlapplication.h]: Please use a trailing underscore for member variables and no trailing underscore for local variables. So those should be `handle_key_enabled_` and `enable`.

**Review by Noordfrees — COMMENTED** [review]
Tested and working :) 
Just one codestyle comment

**Review by Noordfrees — APPROVED** [review]
