### PR TITLE
fixed help for atlantean labyrinth

### LINKED ISSUE #4164: Atlantean Labyrinth Help Error
In the Atlantean Labyrinth the needed wares for health training and evade training are wrong

see also https://www.widelands.org/forum/topic/4928

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4164

### CODE REVIEW

File: data/tribes/buildings/trainingsites/atlanteans/labyrinth/init.lua [hunk 1]
```diff
@@ -74,6 +73,7 @@ tribes:new_trainingsite_type {
    ["soldier evade"] = {
       food = {
          {"smoked_fish", "smoked_meat"}
```
Comment (gunchleoc) [inline data/tribes/buildings/trainingsites/atlanteans/labyrinth/init.lua]:
```suggestion
         {"smoked_fish", "smoked_meat"},
```

**Review by gunchleoc — APPROVED** [review]
Code LGTM now. I'll leave the testing to Travis.
