### PR TITLE
Fix statistics string cache

### LINKED ISSUE #4537: Wrong militarysite soldier statistics strings
In this screenshot the milsite displays the wrong soldier info: It says there are 0 soldiers present but in fact 1 soldier is inside.
shot0002
[Savegame](https://github.com/widelands/widelands/files/5603589/soldierstatsbug.wgf.zip)

### PR DESCRIPTION
**Pull request by matthiakl**
Fixes #4537

### CODE REVIEW

File: src/logic/map_objects/tribes/militarysite.cc [hunk 1]
```diff
@@ -396,7 +396,8 @@ void MilitarySite::update_statistics_string(std::string* s) {
 					cr->push_arg(capacity_);
 					cr->resume();
 					std::string new_string = cr->pop_string();
-					statistics_string_cache_[idx].insert(std::make_pair(stat, new_string));
+					statistics_string_cache_[idx].insert(
+					   std::make_pair((pres << 8) + (stat << 4) + capacity_, new_string));
```
Comment (Noordfrees) [inline src/logic/map_objects/tribes/militarysite.cc]: Good catch :) 
But wouldn't milsites with large soldier capacities still show the bug if the capacity can occupy more than four bits? Perhaps use std::tuple<int,int,int> as key instead of plain int to ensure all keys are unique.

Comment (matthiakl) [reply src/logic/map_objects/tribes/militarysite.cc]: I thought the current milsites don't have more than 12 soldiers. But for future expansions (and Addons) you are right.

**Review by Noordfrees — APPROVED** [review]
Fix confirmed, code LGTM :)
