### PR TITLE
Overhaul of SP and MP launch game screen

### LINKED ISSUE #3831: Multiplayer map with more than 8 players
**Describe the bug**
The "Multiplayer Game Setup" shows only 8 players, even if the map has more than eight. Since I cannot modify player 9, 10, etc. the button "Start game" stays inactive and the game refuses to start.
If this is related to screen resolution: my display can go up to 1280x1024.

**To Reproduce**
1. Go to Multiplayer > LAN / Direct IP > Host a new game
2. Choose a map with more than 8 players, e.g. "Rounds Ultra"
3. The first eight players show up. 

**Expected behavior**
The list of players should be scrollable so I can configure all players.

**Screenshots**
map_with_15_players

**Version:**
 - OS: Windows 7
 - Widelands Version: build-20, master-6928, bzr9110

### LINKED ISSUE #3886: Singleplayer Launch Game menu does not cleanup
The launch game menu does not cleanup after reentry.

**To Reproduce**
1. Enter Singleplayer -> New Game -> Choose a 8 Players map -> OK
2. Make some changes, e.g. Set you as fifth player, set you as team 3, disable players 1,2,3, and 6,7,8 so that you are second player
3. Click on Back 
4. now choose a two players map -> OK

Result:
Some of the settings made for the previous map are applied now, f.e. your team will be 3, you will be the second player.

'Resetting' the screen can only be done by going two times back, so start by clicking on 'Singleplayer'.

During testing i have managed to have a launch game screen where one players name is missing, don't know how.

**Expected behavior**
The launch game screen should be 'clean' whenever one had chosen a new map. That is it should be shown as this is the first time one entered this screen. 

**Version:**
 - OS: archlinux
 - Widelands Version: [44281e5]

### LINKED ISSUE #3928: Recommended teams are not shown on multiplayer setup screen
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
When a map has team recommendations they are shown on the multiplayer setup screen between the win conditions and the start game button. These er missing.

**To Reproduce**
1. Set up a multiplayer game.
2. Choose the map Calvison or any map with team recommendations.

**Expected behavior**
Show the recommendations again

**Version:**
 - OS: macOS
 - Widelands Version: https://github.com/widelands/widelands/pull/3857/commits/15b8420ef06235ea5b787ad01bf2d9fe47cbfdd5

### LINKED ISSUE #3940: MP Scenario Smugglers segfaults when loading the scenario
Just wanted to reproduce issue #3927 but the scenario doesn't start at all:

~~~~
....
[Host]: starting up.
[NetHost] Opening a listening IPv4 socket on TCP port 7396
[NetHost] Opening a listening IPv6 socket on TCP port 7396
[NetHost] Starting to listen for network connections
[NetHost] Starting networking thread
[LAN] Started an IPv4 socket on UDP port 7395.
[LAN] Started an IPv6 socket on UDP port 7395.
[LAN] Will broadcast to 127.0.0.1.
[LAN] Will broadcast to 192.168.178.255.
[LAN] Will broadcast for IPv6.
Map/Save is a directory! No way for making it available a.t.m.!
widelands: /home/kaputtnik/Quellcode/widelands-repo/widelands/src/ui_basic/panel.cc:313: virtual void UI::Panel::set_desired_size(int, int): Zusicherung »w >= 0« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)
~~~~

**To Reproduce**
1. Choose Multiplayer -> LAN/Direct IP
2. Click on: New Game -> Map
3. Choose: Multiplayer Scenarios -> Smugglers
4. Click OK

**Version:**
 - archlinux
 - Widelands Version: edec161@master] (Debug)

**Additional context**
As far i have tested the crash happens only with 'Smugglers', not with 'Island Hopping' or any other map.

### LINKED ISSUE #3942: [Duplicate] Assert failure in Suggested Teams Box
Please fill out the relevant sections below and delete the rest.

**Describe the bug**
As of the "multiplayer tournament 2020" 
https://www.widelands.org/forum/topic/4847/?page=10#post-33503
i wanted to play the builtin Map "Full Moon". But when openinig it as
mutiplayer map (not in singleplayer) I get 

Assertion failed: (w >= 0), function set_desired_size, file ../src/ui_basic/panel.cc, line 313.

**To Reproduce**
1.Open Mutiplayer Lobby, host ne Game "HasiFarming"
2. Chose Map "Full Moon"
-> See error

**Expected behavior**

Works without an Issue in R20, should do so in R21, too.

**Version:**
 - OS: macOS Caztallina 10.15.5
 - master:r24633[3a98a0b@HEAD] amazons:r24837[75189d8@amazons]

### PR DESCRIPTION
**Pull request by jmoerschbach**
**Update**

I am getting closer... ;) There are still some (minor) issues, see todo list (the very first one is a showstopper imho).
Feedback appreciated :)
yes, there are still some logs which will be deleted before merging... also new classes will replace the old ones.

* fixes #3831
* fixes #3886
* fixed #3928 
* fixes #3942 
* fixes partly #947
* fixes partly  #956

- [x] fix automatic relayout of dropdowns (fixed a bug in basedropdown -> needs extra careful review since I still don't get box layout)
- [x] decide what to do with help button in mp screen (hard coded position in layout())
- [ ] decide whether mp screen should also be completely reset when map changes (as sp now does)
- [x] fine tune paddings
- [x] add missing license header
- [x] SP: map description is not localized
- [x] SP: set tribes according to map defaults
- [x] MP: address scrolling problem when many-player-map is swapped by few-player-map (empty scrolling area) 
- [x] use predefined player names from map
- [x] SP: keep player name when switching player position/number

---

* add scrollbar iff necessary to playerbox
* adapt width so scrollbar is aligned nicely
* extract some local variables

personally, I dislike the forced scrollbar of the chat panel, see screenshot
grafik

Is there a specific reason why it is forced to be displayed? It can be easily be fixed by changing
https://github.com/widelands/widelands/blob/8ca731ae521c49992931c0d9152eb3b3ea2b8163/src/wui/game_chat_panel.cc#L45
to 
`UI::MultilineTextarea::ScrollMode::kScrollLog`

This of course would be visible in the internet lobby, too, since the game_chat_panel is also used there.

What do you think? :)

### CODE REVIEW

File: src/wui/multiplayersetupgroup.cc [hunk 1]
```diff
@@ -698,11 +698,12 @@ MultiPlayerSetupGroup::~MultiPlayerSetupGroup() {
 void MultiPlayerSetupGroup::update() {
 	const GameSettings& settings = settings_->settings();
 
+	size_t number_of_users = settings.users.size();
```
Comment (Noordfrees) [inline src/wui/multiplayersetupgroup.cc]: make this `const`

**Review by Noordfrees — COMMENTED** [review]
Nice! :)

Tested and working, Code LGTM, just one minor style suggestion inline. Please unlink the linked issue though because it is fixed only half by this change as the singleplayer screen is unchanged.

> personally, I dislike the forced scrollbar of the chat panel, see screenshot
> Is there a specific reason why it is forced to be displayed? It can be easily be fixed […]

I don't know why it is like this, but IMHO displaying it only when needed would look nicer

**Comment by jmoerschbach** [comment]
> 
> 
> Nice! :)
> 
> Tested and working, Code LGTM, just one minor style suggestion inline. Please unlink the linked issue though because it is fixed only half by this change as the singleplayer screen is unchanged.

Mhm, I'd rather fix the problem in singleplayer too ;)
Any reasons why the setup looks different there? I like the multiplayer "list" with the embedded dropdowns much better! May I change it in Singleplayer so it looks alike? :)

> > personally, I dislike the forced scrollbar of the chat panel, see screenshot
> > Is there a specific reason why it is forced to be displayed? It can be easily be fixed […]
> 
> I don't know why it is like this, but IMHO displaying it only when needed would look nicer

yeah let's wait if somebody else has a different opionion, otherwise I'll change it

**Comment by Noordfrees** [comment]
Making the singleplayer setup screen consistent with the multiplayer setup screen has been on our wishlist for quite some time, if you want to do this this would be great :)

**Comment by jmoerschbach** [comment]
Ok, I'm just now realising how much work this will be... Oo 
I like it :D

Out of curiosity: Is there any particular reason why the layout (dimensions and positioning of widgets) is done by calculating the values manually with a loooot of magic numbers instead of building it up from nested UI:Boxes with appropriate spacing/padding?
A lot of layouting would then be done automatically, I hope...?

**Comment by Noordfrees** [comment]
I think using box layout would be good here. See also #947 and #956

**Comment by jmoerschbach** [comment]
ok, this will take a few days... ;)

**Comment by jmoerschbach** [comment]
just to give a heads up: still working on it and making progress! ;) will take some more days though...

can anyone tell me why both multiplayersetupgroup.h/cc (used in the multiplayer gameloading screen) and playerdescgroup.h/cc (used in singleplayer gameloading screen) are located in wl_library "wui" and not in wl_library "ui_fsmenu_gameloading" where they are actually used?

**Comment by Noordfrees** [comment]
> can anyone tell me why both multiplayersetupgroup.h/cc (used in the multiplayer gameloading screen) and playerdescgroup.h/cc (used in singleplayer gameloading screen) are located in wl_library "wui" and not in wl_library "ui_fsmenu_gameloading" where they are actually used?

I'm inclined to call this a design fault, perhaps you'd like to move the setupgroups to ui_fsmenu_gameloading?

**Comment by Noordfrees** [comment]
What's the status here? How are the chances to have this in b21?

**Comment by jmoerschbach** [comment]
I will need at least one more week before it is ready for testing/review. UI::Box layout is killing me...

**Comment by Noordfrees** [comment]
After some looking at the diff I am reconsidering about how urgently we need this in b21…
@jmoerschbach would you mind if we reschedule this PR for b22?

**Comment by jmoerschbach** [comment]
no, I don't mind ;)

**Comment by stonerl** [comment]
> Ok, I'm just now realising how much work this will be... Oo
> I like it :D
> 
> Out of curiosity: Is there any particular reason why the layout (dimensions and positioning of widgets) is done by calculating the values manually with a loooot of magic numbers instead of building it up from nested UI:Boxes with appropriate spacing/padding?
> A lot of layouting would then be done automatically, I hope...?

Some of these magic numbers are used to make sure that buttons don't move too much when the screen size increases. Otherwise, there would be a lot of ugly white space and fields like the map description have to be scrolled albeit there would be enough space to display it completely. These numbers are more or less a result of trial and error.

I haven't dug into the code for a long time, are sure that you can achieve this just by using the box layout?.

The starting point for the layout is 800 x 600. Since this is the minimum resolution we support. From there you increase the resolution and make sure that the white spaces don't increase proportional and everything still fits.

**Comment by jmoerschbach** [comment]
yeah, actually I am quite sure but of course there might be some de facto unused white space, but I still think this is preferable to the current not-at-all-relayouting behaviour when changing between window mode and fullscreen :)

can someone explain what the "Shared-in" mode is? I assume it is not used in Singleplayer, right?

**Comment by hessenfarmer** [comment]
> 
> can someone explain what the "Shared-in" mode is? I assume it is not used in Singleplayer, right?

Just to answer your question Shared-in is a multiplayer mode where 2 or more players share their HQ's and economies in a team. this means each of them can play in each others territory and interact which each others buildings. in fact this reaults in one player manged by 2 people simultaneously.

**Comment by stonerl** [comment]
I can't build this branch on my mac. Here is the output:

```
[63/126] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/launch_spg2.cc.o
../src/ui_fsmenu/launch_spg2.cc:25:36: warning: unused parameter 'note' [-Wunused-parameter]
           [this](const NoteGameSettings& note) { update(); });
                                          ^
1 warning generated.
[66/126] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/launch_mpg2.cc.o
In file included from ../src/ui_fsmenu/launch_mpg2.cc:20:
../src/ui_fsmenu/launch_mpg2.h:69:16: warning: non-static data member 'padding_' of 'FullscreenMenuLaunchMPG2' shadows member inherited from type 'FullscreenMenuLaunchGame' [-Wshadow-field]
        int32_t const padding_;  // Common padding between panels
                      ^
../src/ui_fsmenu/launch_game.h:84:11: note: declared here
        uint32_t padding_;
                 ^
In file included from ../src/ui_fsmenu/launch_mpg2.cc:20:
../src/ui_fsmenu/launch_mpg2.h:69:16: warning: private field 'padding_' is not used [-Wunused-private-field]
        int32_t const padding_;  // Common padding between panels
                      ^
../src/ui_fsmenu/launch_mpg2.h:70:16: warning: private field 'indent_' is not used [-Wunused-private-field]
        int32_t const indent_;   // Indent for elements below labels
                      ^
../src/ui_fsmenu/launch_mpg2.h:71:16: warning: private field 'label_height_' is not used [-Wunused-private-field]
        int32_t const label_height_;
                      ^
4 warnings generated.
[69/126] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/launch_mpg.cc.o
In file included from ../src/ui_fsmenu/launch_mpg.cc:20:
../src/ui_fsmenu/launch_mpg.h:70:16: warning: non-static data member 'padding_' of 'FullscreenMenuLaunchMPG' shadows member inherited from type 'FullscreenMenuLaunchGame' [-Wshadow-field]
        int32_t const padding_;  // Common padding between panels
                      ^
../src/ui_fsmenu/launch_game.h:84:11: note: declared here
        uint32_t padding_;
                 ^
In file included from ../src/ui_fsmenu/launch_mpg.cc:20:
../src/ui_fsmenu/launch_mpg.h:84:25: warning: non-static data member 'suggested_teams_box_' of 'FullscreenMenuLaunchMPG' shadows member inherited from type 'FullscreenMenuLaunchGame' [-Wshadow-field]
        UI::SuggestedTeamsBox* suggested_teams_box_;
                               ^
../src/ui_fsmenu/launch_game.h:98:24: note: declared here
        UI::SuggestedTeamsBox suggested_teams_box_;
                              ^
2 warnings generated.
[101/126] Building CXX object src/wui/CMakeFiles/wui.dir/multiplayersetupgroup.cc.o
FAILED: src/wui/CMakeFiles/wui.dir/multiplayersetupgroup.cc.o
/usr/local/opt/ccache/libexec/clang++  -DBOOST_ALL_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -I../src -Isrc -isystem /usr/local/include -isystem /usr/local/Cellar/sdl2/2.0.12_1/include/SDL2 -isystem /usr/local/opt/gettext/include -isystem /usr/local/opt/libpng/include -isystem /usr/local/include/SDL2 -isystem /usr/local/opt/glew/include -isystem /usr/local/opt/icu4c/include -isystem /usr/local/opt/zlib/include -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9    -std=c++11 -O3 -DNDEBUG -DNOPARACHUTE -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-exit-time-destructors -Wno-global-constructors -Wno-padded -Wno-sign-conversion -Wno-missing-noreturn -Wno-switch-enum -Wno-weak-vtables -Wno-unreachable-code -Wno-documentation -Werror=deprecated -Werror=non-pod-varargs -Qunused-arguments -Wint-to-void-pointer-cast -Winconsistent-missing-override -Werror=format-security -Werror=return-type -Werror=shadow -Werror=uninitialized -MD -MT src/wui/CMakeFiles/wui.dir/multiplayersetupgroup.cc.o -MF src/wui/CMakeFiles/wui.dir/multiplayersetupgroup.cc.o.d -o src/wui/CMakeFiles/wui.dir/multiplayersetupgroup.cc.o -c ../src/wui/multiplayersetupgroup.cc
../src/wui/multiplayersetupgroup.cc:24:10: fatal error: 'bits/stl_algobase.h' file not found
#include <bits/stl_algobase.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
[102/126] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/singleplayersetupbox.cc.o
In file included from ../src/ui_fsmenu/singleplayersetupbox.cc:1:
../src/ui_fsmenu/singleplayersetupbox.h:45:30: warning: private field 'settings_' is not used [-Wunused-private-field]
        GameSettingsProvider* const settings_;
                                    ^
1 warning generated.
[106/126] Building CXX object src/CMakeFiles/widelands_ball_of_mud.dir/wlapplication.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by jmoerschbach** [comment]
@stonerl 
it should work now :)

**Comment by stonerl** [comment]
@jmoerschbach Yes it does :-) Haven't had the time to look into this PR. Will give you feedback as soon as I find some time.

**Comment by jmoerschbach** [comment]
Hi,
I just fixed the last showstopper. Please see the updated first post. If anybody could have a look and give some feedback, I'd would be glad :)
The code is still not ready for a thorough review, but in general, it should work now ;)

**Comment by Noordfrees** [comment]
Tested this a bit now. I like the new SP screen much better than the old one :)

I get one compiler warning:
```
[247/336] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/multiplayersetupgroup.cc.o
../src/ui_fsmenu/multiplayersetupgroup.cc: In member function ‘void MultiPlayerSetupGroup::update()’:
../src/ui_fsmenu/multiplayersetupgroup.cc:719:63: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int32_t’ {aka ‘int’} [-Wsign-compare]
  719 |  scrollable_playerbox.set_scrolling(number_of_players * buth_ > scrollable_playerbox.get_h());
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

In both screens, the player names are not displayed but replaced with "Player 1" through "Player 16", which can be seen e.g. with the official Europa map. The name defined in the map (if any) should be used there, and ideally after switching to a different position in SP the player should be assigned that position's name for the game.

In the MP screen it seems that there is a layouting issue: the players box is only 5 rows high and there's a lot of unused space beneath
wl-new-game-setup-screen
And if the scrollbar is displayed, the box always has the height needed for 16 players, even if the map has less than that:
wl-new-mp-setup-screen

**Review by Noordfrees — COMMENTED** [review]
I'll try to do a code review soonish. 
Please go though the diff and ensure that all files have a license header, and that the copyright end year is 2020 for all.

**Comment by Noordfrees** [comment]
Another observation: In the SP setup screen, the map description is not localized

Edit: And another one: In the SP screen, player 1 always seems to have tribe barbarians and all others random tribe, regardless of what the map defines as default

**Comment by gunchleoc** [comment]
> Out of curiosity: Is there any particular reason why the layout (dimensions and positioning of widgets) is done by calculating the values manually with a loooot of magic numbers instead of building it up from nested UI:Boxes with appropriate spacing/padding?
> A lot of layouting would then be done automatically, I hope...?

Yes. The code was written before the `UI::Box` class existed. I have been working for ca. 6 years on converting all the screens, so I am glad you are helping with this now :)

I have it a quick spin and the scrolling on the Multiplayer screen doesn't work properly - something is wrong with the box size. We have never used a scrolling `UI::Box` anywhere so far, so the bug is probably somewhere in that class.

File: src/ui_fsmenu/multiplayersetupgroup.cc [hunk 2]
```diff
@@ -292,17 +280,15 @@ struct MultiPlayerPlayerGroup : public UI::Box {
...
 
-	/// Update dropdown sizes
-	void layout() override {
-		const int max_height = g_gr->get_yres() * 3 / 4;
-		type_dropdown_.set_height(max_height);
-		tribes_dropdown_.set_height(max_height);
-		init_dropdown_.set_height(max_height);
-		team_dropdown_.set_height(max_height);
-		UI::Box::layout();
+	void force_new_dimensions(float, uint32_t max_width, uint32_t standard_element_height) {
```
Comment (gunchleoc) [inline src/ui_fsmenu/multiplayersetupgroup.cc]: Is there a reason you renamed this function? I have been calling this `layout()` everywhere so far, so having a different name here will make the code harder to read IMO.

File: src/ui_fsmenu/singleplayerdropdown.cc [hunk 3]
```diff
@@ -0,0 +1,384 @@
...
+#include <boost/algorithm/string.hpp>
+
+#include "ai/computer_player.h"
+#include "base/i18n.h"
+#include "graphic/playercolor.h"
+#include "map_io/map_loader.h"
+
+#define AI_NAME_PREFIX "ai" AI_NAME_SEPARATOR
+#define HUMAN_PLAYER "human_player"
+#define RANDOM "random"
```
Comment (gunchleoc) [inline src/ui_fsmenu/singleplayerdropdown.cc:33]: We have started replacing macros with constexpr, because this will give us a datatype too. Like this:

`constexpr const char* const kRandom = "random";`

File: src/wui/CMakeLists.txt [hunk 4]
```diff
@@ -1,150 +1,152 @@
...
-  SRCS
-    sound_options.cc
-    sound_options.h
-  DEPENDS
-    base_i18n
-    graphic_styles
-    sound
-    ui_basic
-)
+        SRCS
```
Comment (gunchleoc) [inline src/wui/CMakeLists.txt]: Please revert the broken formatting here

File: src/wui/game_chat_panel.h [hunk 5]
```diff
@@ -25,7 +25,7 @@
 #include "chat/chat.h"
 #include "ui_basic/editbox.h"
 #include "ui_basic/multilinetextarea.h"
-
+// TODO(jmoerschbach): replace with gamechatpanel2 once internetlobby is using boxlayout also
```
Comment (gunchleoc) [inline src/wui/game_chat_panel.h]: I have an almost working branch for that - do you want to continue that branch for me?

https://github.com/gunchleoc/widelands/tree/internet-lobby-box

Comment (jmoerschbach) [reply src/wui/game_chat_panel.h]: yes, I will do that :)

File: src/wui/CMakeLists.txt (hunk 4 above)
Comment (jmoerschbach) [reply src/wui/CMakeLists.txt]: done

File: src/ui_fsmenu/singleplayerdropdown.cc (hunk 3 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayerdropdown.cc:33]: hmm, I tried that, see latest commit. But since I need to concat these strings, I am not sure if this is feasible. Internet says I'd need to use strcat, see https://stackoverflow.com/questions/1995053/const-char-concatenation/44204042

Please advise :)

File: src/ui_fsmenu/multiplayersetupgroup.cc (hunk 2 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/multiplayersetupgroup.cc]: Yeah, that was intentional. I wanted to highlight that these panels cannot relayout themselves but need parameters from "outside". I can rename them to layout(float, uint32_t, ...) if you like. Not sure if this actually improves readability because this of course would not override Panel::layout(), right? ;)

**Comment by jmoerschbach** [comment]
> 
> 
> > Out of curiosity: Is there any particular reason why the layout (dimensions and positioning of widgets) is done by calculating the values manually with a loooot of magic numbers instead of building it up from nested UI:Boxes with appropriate spacing/padding?
> > A lot of layouting would then be done automatically, I hope...?
> 
> Yes. The code was written before the `UI::Box` class existed. I have been working for ca. 6 years on converting all the screens, so I am glad you are helping with this now :)
> 
Sure :)

> I have it a quick spin and the scrolling on the Multiplayer screen doesn't work properly - something is wrong with the box size. We have never used a scrolling `UI::Box` anywhere so far, so the bug is probably somewhere in that class.

Do you refer to the problem as @Noordfrees (see https://github.com/widelands/widelands/pull/3847#issuecomment-652435730 second screenshot)?
If yes:
The problem is loading a 8-player-map adds 8 panels to the box. When a 5-player-map is then selected, 3 panels are set to invisible, but not removed. So the box has still 8 panels, thus the scrolling looks broken. I see 2 possible solutions:

1. add support for removing a child which was added from Panel
2. change Box to not take invisible items into consideration for actual size computation

I think both of them are not easily implemented.

File: src/ui_fsmenu/CMakeLists.txt [hunk 6]
```diff
@@ -97,7 +97,16 @@ wl_library(ui_fsmenu_gameloading
     launch_spg.h
     loadgame.cc
     loadgame.h
+    mapdetailsbox.cc
+    mapdetailsbox.h
+	multiplayersetupgroup.cc
```
Comment (gunchleoc) [inline src/ui_fsmenu/CMakeLists.txt]: We are using space here - are you using tabs?

File: src/ui_fsmenu/singleplayerdropdown.cc (hunk 3 above)
Comment (gunchleoc) [reply src/ui_fsmenu/singleplayerdropdown.cc:33]: Leave the `AI_NAME_PREFIX` as macro and change the other 2 which are not concatenated.

File: src/ui_fsmenu/multiplayersetupgroup.cc (hunk 2 above)
Comment (gunchleoc) [reply src/ui_fsmenu/multiplayersetupgroup.cc]: Duh, I overlooked that.

**Comment by gunchleoc** [comment]
> The problem is loading a 8-player-map adds 8 panels to the box. When a 5-player-map is then selected, 3 panels are set to invisible, but not removed. So the box has still 8 panels, thus the scrolling looks broken. I see 2 possible solutions:
> 
>     1. add support for removing a child which was added from Panel
> 
>     2. change Box to not take invisible items into consideration for actual size computation
> 
> 
> I think both of them are not easily implemented.

And both of them sound attractive. 2 sounds like the easier way to go and less bug-prone.

File: src/wui/game_chat_panel.h (hunk 5 above)
Comment (gunchleoc) [reply src/wui/game_chat_panel.h]: Thanks! I have just merged master.

The remaining issue with that branch is that the chatpanel blocks the ctrl+F screenshot for fullscreen switching.

File: src/ui_fsmenu/CMakeLists.txt (hunk 6 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/CMakeLists.txt]: yes, sorry. fixed.

File: src/ui_fsmenu/singleplayerdropdown.cc (hunk 3 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayerdropdown.cc:33]: yeah, I think I did that already... ;)

**Comment by jmoerschbach** [comment]
> 
> 
> > The problem is loading a 8-player-map adds 8 panels to the box. When a 5-player-map is then selected, 3 panels are set to invisible, but not removed. So the box has still 8 panels, thus the scrolling looks broken. I see 2 possible solutions:
> > ```
> > 1. add support for removing a child which was added from Panel
> > 
> > 2. change Box to not take invisible items into consideration for actual size computation
> > ```
> > 
> > 
> > I think both of them are not easily implemented.
> 
> And both of them sound attractive. 2 sounds like the easier way to go and less bug-prone.

I hacked in the second approach. Problem is, Box does not get notified, when a child panel's visibility is changed. In this particular use case I can work around this because `void Box::set_scrolling(bool scroll)` is called which triggers a recalculation.
Any ideas for a more general solution? :)

**Comment by Noordfrees** [comment]
In the [add-ons branch](https://www.github.com/Noordfrees/widelands/commits/addons) I hacked together a way to remove all children from a UI::Box. I also implemented force-scrolling capabilities into UI::Box there to fix some related layouting problems. A more general solution for both would be good to have

**Comment by gunchleoc** [comment]
> I hacked in the second approach. Problem is, Box does not get notified, when a child panel's visibility is changed. In this particular use case I can work around this because `void Box::set_scrolling(bool scroll)` is called which triggers a recalculation.
> Any ideas for a more general solution? :)

You could sent a notification in `~Panel() ` and let the Box subscribe to it.

**Comment by jmoerschbach** [comment]
> 
> 
> > I hacked in the second approach. Problem is, Box does not get notified, when a child panel's visibility is changed. In this particular use case I can work around this because `void Box::set_scrolling(bool scroll)` is called which triggers a recalculation.
> > Any ideas for a more general solution? :)
> 
> You could sent a notification in `~Panel() ` and let the Box subscribe to it.

Not quite sure if I understood you correctly, but I tried something. Please have a look :)

**Comment by gunchleoc** [comment]
Yes, something like that.

**Comment by jmoerschbach** [comment]
call for testing/review since almost all known issues are fixed (see first post) :)

**Comment by Noordfrees** [comment]
Two more bugs.
First in the multiplayer screen, an issue with the players list:
wl-3847-bug
Modifying a player's slot will cause the list to expand horizontally.

And second, an issue which is also in master but which seems even less intuitive here. When I choose the Europe map in singleplayer, I am always called Sweden, regardless of my starting position. If I play e.g. as player 6, I'd expect to be called England, but instead I am named Sweden and the blue player (who starts in sweden) is called England. It would be great if you could fix this as well here.

**Comment by jmoerschbach** [comment]
> 
> 
> Two more bugs.
> First in the multiplayer screen, an issue with the players list:
> wl-3847-bug
> Modifying a player's slot will cause the list to expand horizontally.

Hmm, actually I cannot reproduce this. What are the steps you are doing to get this picture?

> And second, an issue which is also in master but which seems even less intuitive here. When I choose the Europe map in singleplayer, I am always called Sweden, regardless of my starting position. If I play e.g. as player 6, I'd expect to be called England, but instead I am named Sweden and the blue player (who starts in sweden) is called England. It would be great if you could fix this as well here.

fixed

**Comment by Noordfrees** [comment]
> Hmm, actually I cannot reproduce this. What are the steps you are doing to get this picture?

Multiplayer → LAN → New Game → Cancel → Select Map/Savegame → Map → Double-click on any map

Edit: And this also happens when all slots are set to Open.

---

And I found a crash: 
Multiplayer → LAN → New Game → [Escape] → [Escape]
```
==45574==ERROR: AddressSanitizer: heap-use-after-free on address 0x604000674ae8 at pc 0x5598d30716a7 bp 0x7ffe1bf503b0 sp 0x7ffe1bf503a0
READ of size 8 at 0x604000674ae8 thread T0
    #0 0x5598d30716a6 in boost::shared_ptr<boost::signals2::mutex>::operator*() const /usr/include/boost/smart_ptr/shared_ptr.hpp:728
    #1 0x5598d35e016f in boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() /usr/include/boost/signals2/detail/signal_template.hpp:230
    #2 0x5598d35dfccf in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() /usr/include/boost/signals2/detail/signal_template.hpp:722
    #3 0x5598d363f269 in UI::Panel::set_pos(Vector2<int>) ../src/ui_basic/panel.cc:284
    #4 0x5598d35c63e9 in UI::Box::set_item_pos(unsigned int, int) ../src/ui_basic/box.cc:432
    #5 0x5598d35c4e65 in UI::Box::update_positions() ../src/ui_basic/box.cc:257
    #6 0x5598d35c499e in UI::Box::layout() ../src/ui_basic/box.cc:239
    #7 0x5598d35c369c in UI::Box::update_desired_size() ../src/ui_basic/box.cc:138
    #8 0x5598d35c239d in operator() ../src/ui_basic/box.cc:49
    #9 0x5598d35c6e48 in __invoke_impl<void, UI::Box::Box(UI::Panel*, int32_t, int32_t, uint32_t, int32_t, int32_t, uint32_t)::<lambda(const UI::NotePanel&)>&, const UI::NotePanel&> /usr/include/c++/10/bits/invoke.h:60
    #10 0x5598d35c6a3d in __invoke_r<void, UI::Box::Box(UI::Panel*, int32_t, int32_t, uint32_t, int32_t, int32_t, uint32_t)::<lambda(const UI::NotePanel&)>&, const UI::NotePanel&> /usr/include/c++/10/bits/invoke.h:153
    #11 0x5598d35c672a in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #12 0x5598d364779c in std::function<void (UI::NotePanel const&)>::operator()(UI::NotePanel const&) const /usr/include/c++/10/bits/std_function.h:622
    #13 0x5598d3647561 in void Notifications::NotificationsManager::publish<UI::NotePanel>(UI::NotePanel const&) ../src/notifications/notifications_impl.h:74
    #14 0x5598d3646d8a in void Notifications::publish<UI::NotePanel>(UI::NotePanel const&) ../src/notifications/notifications.h:51
    #15 0x5598d3640b3f in UI::Panel::set_visible(bool) ../src/ui_basic/panel.cc:455
    #16 0x5598d4300842 in UI::SuggestedTeamsBox::hide() ../src/wui/suggested_teams_box.cc:70
    #17 0x5598d4300426 in UI::SuggestedTeamsBox::~SuggestedTeamsBox() ../src/wui/suggested_teams_box.cc:52
    #18 0x5598d370e49f in FullscreenMenuLaunchGame::~FullscreenMenuLaunchGame() ../src/ui_fsmenu/launch_game.cc:111
    #19 0x5598d36ba2e4 in FullscreenMenuLaunchMPG::~FullscreenMenuLaunchMPG() ../src/ui_fsmenu/launch_mpg.cc:147
    #20 0x5598d34e0b31 in GameHost::run() ../src/network/gamehost.cc:647
    #21 0x5598d2fe5f02 in WLApplication::mainmenu_multiplayer() ../src/wlapplication.cc:1318
    #22 0x5598d2fe4237 in WLApplication::mainmenu() ../src/wlapplication.cc:1157
    #23 0x5598d2fd430d in WLApplication::run() ../src/wlapplication.cc:493
    #24 0x5598d2fcfac1 in main ../src/main.cc:42
    #25 0x7f29b6d8c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #26 0x5598d2fcf95d in _start (/home/benedikt/wl/clevercritters/widelands+0xedd95d)

0x604000674ae8 is located 24 bytes inside of 40-byte region [0x604000674ad0,0x604000674af8)
freed by thread T0 here:
    #0 0x7f29b798da37 in operator delete(void*) (/lib/x86_64-linux-gnu/libasan.so.6+0xb2a37)
    #1 0x5598d307ce24 in void boost::checked_delete<boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex> >(boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>*) (/home/benedikt/wl/clevercritters/widelands+0xf8ae24)
    #2 0x5598d309d18a in boost::detail::sp_counted_impl_p<boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex> >::dispose() /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:93
    #3 0x5598d2ff25c3 in boost::detail::sp_counted_base::release() /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:112
    #4 0x5598d2ff2749 in boost::detail::shared_count::~shared_count() /usr/include/boost/smart_ptr/detail/shared_count.hpp:427
    #5 0x5598d2ffa11d in boost::shared_ptr<boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex> >::~shared_ptr() /usr/include/boost/smart_ptr/shared_ptr.hpp:341
    #6 0x5598d2ffa170 in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::~signal() /usr/include/boost/signals2/detail/signal_template.hpp:664
    #7 0x5598d363dfcf in UI::Panel::~Panel() ../src/ui_basic/panel.cc:96
    #8 0x5598d3005934 in UI::Box::~Box() ../src/ui_basic/box.h:37
    #9 0x5598d36e6c1e in MultiPlayerSetupGroup::~MultiPlayerSetupGroup() ../src/ui_fsmenu/multiplayersetupgroup.cc:701
    #10 0x5598d36ba2b4 in FullscreenMenuLaunchMPG::~FullscreenMenuLaunchMPG() ../src/ui_fsmenu/launch_mpg.cc:147
    #11 0x5598d34e0b31 in GameHost::run() ../src/network/gamehost.cc:647
    #12 0x5598d2fe5f02 in WLApplication::mainmenu_multiplayer() ../src/wlapplication.cc:1318
    #13 0x5598d2fe4237 in WLApplication::mainmenu() ../src/wlapplication.cc:1157
    #14 0x5598d2fd430d in WLApplication::run() ../src/wlapplication.cc:493
    #15 0x5598d2fcfac1 in main ../src/main.cc:42
    #16 0x7f29b6d8c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

previously allocated by thread T0 here:
    #0 0x7f29b798cf17 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x5598d30613df in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::signal(boost::signals2::optional_last_value<void> const&, std::less<int> const&) /usr/include/boost/signals2/detail/signal_template.hpp:660
    #2 0x5598d363d2bc in UI::Panel::Panel(UI::Panel*, int, int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/ui_basic/panel.cc:77
    #3 0x5598d35c24bf in UI::Box::Box(UI::Panel*, int, int, unsigned int, int, int, unsigned int) ../src/ui_basic/box.cc:46
    #4 0x5598d36e5f56 in MultiPlayerSetupGroup::MultiPlayerSetupGroup(UI::Panel*, int, int, int, int, GameSettingsProvider*, unsigned int, unsigned int) ../src/ui_fsmenu/multiplayersetupgroup.cc:670
    #5 0x5598d36b9599 in FullscreenMenuLaunchMPG::FullscreenMenuLaunchMPG(GameSettingsProvider*, GameController*, ChatProvider&) ../src/ui_fsmenu/launch_mpg.cc:121
    #6 0x5598d34df1aa in GameHost::run() ../src/network/gamehost.cc:622
    #7 0x5598d2fe5f02 in WLApplication::mainmenu_multiplayer() ../src/wlapplication.cc:1318
    #8 0x5598d2fe4237 in WLApplication::mainmenu() ../src/wlapplication.cc:1157
    #9 0x5598d2fd430d in WLApplication::run() ../src/wlapplication.cc:493
    #10 0x5598d2fcfac1 in main ../src/main.cc:42
    #11 0x7f29b6d8c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-use-after-free /usr/include/boost/smart_ptr/shared_ptr.hpp:728 in boost::shared_ptr<boost::signals2::mutex>::operator*() const
```

> fixed

Great, got to try this out right away
Edit: Yay, perfect! :)

**Comment by Noordfrees** [comment]
Another bug: When loading a savegame in the MP/LAN screen, the map description area will show "No map selected. please select a map or savegame.".

Edit: And when I choose Shared In for another player when loading an MP savegame, that player will nonetheless be controlled by the AI and not by me. Hitting Alt-F4 from within this game then results in ASan reporting a heap-use-after-free.

**Comment by jmoerschbach** [comment]
>Multiplayer → LAN → New Game → Cancel → Select Map/Savegame → Map → Double-click on any map
>
> Edit: And this also happens when all slots are set to Open.

I give up. Trying to understand how Box layout works for three month now and still not getting it. Sometimes I think I am misusing it completely... Maybe someone can step in here or we can have a look together?
The problem regarding the collapsing is, that I changed Box.cc to ignore invisible children (to fix scrolling issue, see above).
The code spots to play around/have potential to fix the problem:
* `FullscreenMenuLaunchMPG::layout()`
* `MultiPlayerSetupGroup::force_new_dimensions(...)`
* `MultiPlayerPlayerGroup::force_new_dimensions(...)`

It is usable right now but looks ugly (especially with a many-player-map which makes a scrollbar necessary)
> 
> And I found a crash:
> Multiplayer → LAN → New Game → [Escape] → [Escape]

fixed. please have a look into deconstructor of suggested_teams_box.cc. I am not sure if I introduced a memory leak by discarding call to hide(). If freeing the icons is really necessary, I can reintroduce that. The problem was the call to set_visible() of course.
> 
> Another bug: When loading a savegame in the MP/LAN screen, the map description area will show "No map selected. please select a map or savegame.".

fixed
> 
> Edit: And when I choose Shared In for another player when loading an MP savegame, that player will nonetheless be controlled by the AI and not by me. Hitting Alt-F4 from within this game then results in ASan reporting a heap-use-after-free.

this is the very same behaviour as in current master / build 21. Since this PR is really big already, I would like this to be solved on another PR. The crash is fixed, see above

**Comment by Noordfrees** [comment]
Okay, even more reports coming ;)

Please merge master sometime soon, this is getting a bit outdated.

A bunch of codecheck warnings:
```
[53/470] Checking launch_mpg.cc with CodeCheck
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:134: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:134: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:159: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:159: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:165: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:165: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:166: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:166: Comments need to start with a space.
[54/470] Checking multiplayersetupgroup.cc with CodeCheck
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:676: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:676: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:678: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:678: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:736: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:736: Comments need to start with a space.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:766: Tabs are only allowed before the first non-whitespace character in line.
/home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:766: Comments need to start with a space.
[316/470] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/multiplayersetupgroup.cc.o
../src/ui_fsmenu/multiplayersetupgroup.cc: In member function ‘void MultiPlayerSetupGroup::force_new_dimensions(float, uint32_t, uint32_t, uint32_t)’:
../src/ui_fsmenu/multiplayersetupgroup.cc:759:59: warning: unused parameter ‘max_height’ [-Wunused-parameter]
  759 |                                                  uint32_t max_height,
      |                                                  ~~~~~~~~~^~~~~~~~~~
```

The player rows in the MP setup screen don't utilize the full width of their box which looks a bit strange. Will try to have a look at the box layouting soonish.

I could not make it crash any more, nor did I encounter any memory leaks :)

**Comment by jmoerschbach** [comment]
> 
> 
> Okay, even more reports coming ;)
> 
> Please merge master sometime soon, this is getting a bit outdated.

will do

> 
> A bunch of codecheck warnings:
> 
> ```
> [53/470] Checking launch_mpg.cc with CodeCheck
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:134: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:134: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:159: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:159: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:165: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:165: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:166: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/launch_mpg.cc:166: Comments need to start with a space.
> [54/470] Checking multiplayersetupgroup.cc with CodeCheck
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:676: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:676: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:678: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:678: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:736: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:736: Comments need to start with a space.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:766: Tabs are only allowed before the first non-whitespace character in line.
> /home/benedikt/wl/debug/src/ui_fsmenu/multiplayersetupgroup.cc:766: Comments need to start with a space.
> [316/470] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu_gameloading.dir/multiplayersetupgroup.cc.o
> ../src/ui_fsmenu/multiplayersetupgroup.cc: In member function ‘void MultiPlayerSetupGroup::force_new_dimensions(float, uint32_t, uint32_t, uint32_t)’:
> ../src/ui_fsmenu/multiplayersetupgroup.cc:759:59: warning: unused parameter ‘max_height’ [-Wunused-parameter]
>   759 |                                                  uint32_t max_height,
>       |                                                  ~~~~~~~~~^~~~~~~~~~
> ```

will fix
> 
> The player rows in the MP setup screen don't utilize the full width of their box which looks a bit strange. Will try to have a look at the box layouting soonish.

yes, that is what I meant. I was not able to solve this without introducing weird bugs (especially when toggling between full screen and window mode). Maybe you have a good idea :)
> 
> I could not make it crash any more, nor did I encounter any memory leaks :)

good :)

**Comment by jmoerschbach** [comment]
@Noordfrees did you yet have time to look closer into the problems described above? :)

**Comment by Noordfrees** [comment]
Yes, but I have not found a solution yet :( 
My guess is that the size-forcing methods prevent the box from layouting correctly. I'll keep experimenting with the code to try if I can improve things

**Comment by gunchleoc** [comment]
I have fixed a crash when switching to a smaller map in singleplayer.

I have also commented out the main exception handling so we can get stack traces for debugging. This will need to go back in before we merge.

**Comment by Noordfrees** [comment]
I have pushed a fix for the MP `MultiPlayerPlayerGroup` width.
There are some problems with fullscreen switching in this branch. Perhaps try adding a notification subscriber for resolution changes. Another issue I noticed is that the `clientbox` is resized according to the username width – very long usernames cause the width of the `MultiPlayerPlayerGroup`s to become negative, resulting in an assert failure.

File: src/ui_fsmenu/multiplayersetupgroup.cc [hunk 7]
```diff
@@ -769,11 +760,7 @@ void MultiPlayerSetupGroup::force_new_dimensions(float scale,
 	log("ind. contentbox - clientbox: %d\n", max_width - clientbox.get_w());
 	log("scrollable before: %d\n", scrollable_playerbox.get_w());
 	for (auto& multiPlayerPlayerGroup : multi_player_player_groups) {
-		multiPlayerPlayerGroup->force_new_dimensions(
-		   scale,
-		   /*needs_scrolling_ ? scrollable_playerbox.get_w() - UI::Scrollbar::kSize :
-		                     scrollable_playerbox.get_w()*/
-		   max_width - clientbox.get_w(), standard_element_height);
+		multiPlayerPlayerGroup->set_desired_size(get_w() - 32 - clientbox.get_w() - UI::Scrollbar::kSize, multiPlayerPlayerGroup->get_h());
```
Comment (jmoerschbach) [inline src/ui_fsmenu/multiplayersetupgroup.cc]: thanks @Noordfrees ! I will have once again a look at the end of the week latest. What is the 32 all about?

Comment (Noordfrees) [reply src/ui_fsmenu/multiplayersetupgroup.cc]: 32 is the constant that is used for padding when the box is being created (line 666). perhaps this could be pulled out as a constexpr.

**Comment by jmoerschbach** [comment]
this is once again worth testing imho ;)

**Comment by gunchleoc** [comment]
Can you revert https://github.com/widelands/widelands/pull/4249 in this branch and let us know when it's ready?

**Comment by jmoerschbach** [comment]
> 
> 
> Can you revert #4249 in this branch and let us know when it's ready?

I'd rather not for the following reasons:

1. This branch is already ready from my point of view
2. This branch does not rely on UI::Box's invisible item handling (it now uses UI::Box's capability to delete child items)
3. When reverting #4249, a fix for the shipwindow must also be applied (which has nothing to do with this branch at all, and this one here is rather big already)

So, I'll create a new pr which reverts #4249 and provides the shipwindow fix. Its only precondition will be that this one is merged beforehand

**Comment by gunchleoc** [comment]
Thanks for the explanation. I'll prioritize reviewing this branch then :)

**Comment by gunchleoc** [comment]
Some testing results:

- Single player: Starting a game from a subdirectory bumps me back into the mapselect screen, either directly or after hitting the "Start game" button
- Multiplayer: I am listed multiple times as a client until I am hidden a few ticks later. This also happens on map switching, and they blink on and off when assigning an AI to an empty slot. Opening the screen is also slow - this might be related.
- Both modes: The "Suggested teams" overlap the Start Game / Back buttons in 800x600 resolution. In the long run, it would be great if they were a selectable dropdown. For now, sticking them into the MapsDetailsBox could solve our space problem here.

**Comment by Noordfrees** [comment]
There's a bug left: Main Menu → press 'P' → click New game → Choose either "Map" or "Saved game" → click Back → Crash to main menu with "The map file seems to be invalid"

**Comment by jmoerschbach** [comment]
>
>
>- Single player: Starting a game from a subdirectory bumps me back into the mapselect screen, either directly or after hitting the "Start game" button
>
fixed (back behaviour is now the same as in MPG)

>- Multiplayer: I am listed multiple times as a client until I am hidden a few ticks later. This also happens on map switching, and >they blink on and off when assigning an AI to an empty slot. Opening the screen is also slow - this might be related.
>
fixed
>- Both modes: The "Suggested teams" overlap the Start Game / Back buttons in 800x600 resolution. In the long run, it would be great if they were a selectable dropdown. For now, sticking them into the MapsDetailsBox could solve our space problem here.
> 
fixed
> 
> There's a bug left: Main Menu → press 'P' → click New game → Choose either "Map" or "Saved game" → click Back → Crash to main menu with "The map file seems to be invalid"

fixed

Please test :) Maybe we can finally merge it after months^^

**Comment by Noordfrees** [comment]
Another issue: In the map select screen, highlight a map without suggested teams. The description in the right column will go all the way to the bottom. Then click on a map with suggested teams. Now highlight a map without teams again, and there's a lot of unused space at the bottom of the side column now.

> Please test :) Maybe we can finally merge it after months^^

I know how you feel… :)

**Comment by jmoerschbach** [comment]
> 
> 
> Another issue: In the map select screen, highlight a map without suggested teams. The description in the right column will go all the way to the bottom. Then click on a map with suggested teams. Now highlight a map without teams again, and there's a lot of unused space at the bottom of the side column now.
> 
fixed

**Comment by Noordfrees** [comment]
Found a crash in the LAN setup screen. I changed the map a number of times and then got this:
```
[00:03:29.631 real] INFO: [LAN] Started an IPv4 socket on UDP port 7394.
[00:03:29.631 real] INFO: [LAN] Started an IPv6 socket on UDP port 7394.
[00:03:29.631 real] INFO: [LAN] Will broadcast to 127.0.0.1.
[00:03:29.631 real] INFO: [LAN] Will broadcast to 192.168.178.255.
[00:03:29.631 real] INFO: [LAN] Will broadcast for IPv6.
[00:03:31.016 real] INFO: [Host]: starting up.
[00:03:31.016 real] INFO: [NetHost] Opening a listening IPv4 socket on TCP port 7396
[00:03:31.016 real] INFO: [NetHost] Opening a listening IPv6 socket on TCP port 7396
[00:03:31.016 real] INFO: [NetHost] Starting to listen for network connections
[00:03:31.017 real] INFO: [NetHost] Starting networking thread
[00:03:31.017 real] INFO: [LAN] Started an IPv4 socket on UDP port 7395.
[00:03:31.017 real] INFO: [LAN] Started an IPv6 socket on UDP port 7395.
[00:03:31.017 real] INFO: [LAN] Will broadcast to 127.0.0.1.
[00:03:31.017 real] INFO: [LAN] Will broadcast to 192.168.178.255.
[00:03:31.017 real] INFO: [LAN] Will broadcast for IPv6.
[00:03:31.092 real] DEBUG: mapdetails 256x284, map 256x645
[00:03:31.092 real] DEBUG: ok (0,569) 256x34, back (0,611) 256x34
[00:03:31.092 real] DEBUG: ---------------------------------
[00:03:36.387 real] INFO: Registering the world took 195ms
[00:03:36.594 real] INFO: WidelandsMapLoader::load_map_for_render() for '16 Sektoren' took 419ms
[00:03:37.126 real] INFO: WidelandsMapLoader::load_map_for_render() for '16 Sektoren' took 159ms
[00:03:38.000 real] INFO: WidelandsMapLoader::load_map_for_render() for '16 Sektoren' took 161ms
[00:03:38.506 real] INFO: WidelandsMapLoader::load_map_for_render() for '16 Sektoren' took 157ms
[00:03:41.441 real] WARNING: Map/Save is a directory! No way for making it available a.t.m.!
[00:03:41.445 real] DEBUG: lastserial: 0
[00:04:01.085 real] DEBUG: mapdetails 480x361, map 480x853
[00:04:01.085 real] DEBUG: ok (0,757) 480x44, back (0,809) 480x44
[00:04:01.085 real] DEBUG: ---------------------------------
[00:04:01.090 real] DEBUG: mapdetails 480x361, map 480x853
[00:04:01.090 real] DEBUG: ok (0,781) 480x44, back (0,833) 480x44
[00:04:01.090 real] DEBUG: ---------------------------------
[00:04:05.535 real] DEBUG: mapdetails 256x284, map 256x645
[00:04:05.535 real] DEBUG: ok (0,569) 256x34, back (0,611) 256x34
[00:04:05.535 real] DEBUG: ---------------------------------
[00:04:05.541 real] DEBUG: mapdetails 256x284, map 256x645
[00:04:05.541 real] DEBUG: ok (0,567) 256x34, back (0,609) 256x34
[00:04:05.541 real] DEBUG: ---------------------------------
[00:04:09.446 real] DEBUG: lastserial: 0
[00:04:14.614 real] INFO: Registering the world took 198ms
[00:04:14.713 real] INFO: WidelandsMapLoader::load_map_for_render() for 'The Nile' took 300ms
[00:04:16.059 real] WARNING: Map/Save is a directory! No way for making it available a.t.m.!
[00:04:16.066 real] DEBUG: lastserial: 0
=================================================================
==66087==ERROR: AddressSanitizer: heap-use-after-free on address 0x6120010ec990 at pc 0x558a283d7d79 bp 0x7ffc220b3420 sp 0x7ffc220b3410
READ of size 8 at 0x6120010ec990 thread T0
    #0 0x558a283d7d78 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:848
    #1 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #2 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #3 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #4 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #5 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #6 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #7 0x558a283d2041 in UI::Panel::do_run() ../src/ui_basic/panel.cc:198
    #8 0x558a27ce7641 in FullscreenMenuBase::MenuTarget UI::Panel::run<FullscreenMenuBase::MenuTarget>() ../src/ui_basic/panel.h:103
    #9 0x558a2826aa5c in GameHost::run() ../src/network/gamehost.cc:633
    #10 0x558a27ccd0d6 in WLApplication::mainmenu_multiplayer(FullscreenMenuMain const&, bool) ../src/wlapplication.cc:1331
    #11 0x558a27ccb502 in WLApplication::mainmenu() ../src/wlapplication.cc:1202
    #12 0x558a27cbb121 in WLApplication::run() ../src/wlapplication.cc:496
    #13 0x558a27cb5cc1 in main ../src/main.cc:42
    #14 0x7fde55f3d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #15 0x558a27cb5b5d in _start (/home/benedikt/wl/scenario-editor/widelands+0x49bb5d)

0x6120010ec990 is located 80 bytes inside of 304-byte region [0x6120010ec940,0x6120010eca70)
freed by thread T0 here:
    #0 0x7fde56a3ea37 in operator delete(void*) (/lib/x86_64-linux-gnu/libasan.so.6+0xb2a37)
    #1 0x558a27cf0075 in UI::Scrollbar::~Scrollbar() ../src/ui_basic/scrollbar.h:30
    #2 0x558a27d056ac in std::default_delete<UI::Scrollbar>::operator()(UI::Scrollbar*) const /usr/include/c++/10/bits/unique_ptr.h:84
    #3 0x558a283565b8 in std::__uniq_ptr_impl<UI::Scrollbar, std::default_delete<UI::Scrollbar> >::reset(UI::Scrollbar*) /usr/include/c++/10/bits/unique_ptr.h:181
    #4 0x558a2835590f in std::unique_ptr<UI::Scrollbar, std::default_delete<UI::Scrollbar> >::reset(UI::Scrollbar*) /usr/include/c++/10/bits/unique_ptr.h:455
    #5 0x558a2835049d in UI::Box::layout() ../src/ui_basic/box.cc:228
    #6 0x558a283d298d in UI::Panel::set_size(int, int) ../src/ui_basic/panel.cc:272
    #7 0x558a28351e01 in UI::Box::set_item_size(unsigned int, int, int) ../src/ui_basic/box.cc:403
    #8 0x558a28350ef6 in UI::Box::update_positions() ../src/ui_basic/box.cc:273
    #9 0x558a28350a37 in UI::Box::layout() ../src/ui_basic/box.cc:256
    #10 0x558a283d298d in UI::Panel::set_size(int, int) ../src/ui_basic/panel.cc:272
    #11 0x558a28351d6d in UI::Box::set_item_size(unsigned int, int, int) ../src/ui_basic/box.cc:401
    #12 0x558a28350ef6 in UI::Box::update_positions() ../src/ui_basic/box.cc:273
    #13 0x558a28350a37 in UI::Box::layout() ../src/ui_basic/box.cc:256
    #14 0x558a283d298d in UI::Panel::set_size(int, int) ../src/ui_basic/panel.cc:272
    #15 0x558a28351e01 in UI::Box::set_item_size(unsigned int, int, int) ../src/ui_basic/box.cc:403
    #16 0x558a28350ef6 in UI::Box::update_positions() ../src/ui_basic/box.cc:273
    #17 0x558a28350a37 in UI::Box::layout() ../src/ui_basic/box.cc:256
    #18 0x558a2834f46e in UI::Box::update_desired_size() ../src/ui_basic/box.cc:154
    #19 0x558a283d3158 in UI::Panel::set_desired_size(int, int) ../src/ui_basic/panel.cc:312
    #20 0x558a2834f139 in UI::Box::update_desired_size() ../src/ui_basic/box.cc:141
    #21 0x558a283d3158 in UI::Panel::set_desired_size(int, int) ../src/ui_basic/panel.cc:312
    #22 0x558a2834f40d in UI::Box::update_desired_size() ../src/ui_basic/box.cc:147
    #23 0x558a283d3158 in UI::Panel::set_desired_size(int, int) ../src/ui_basic/panel.cc:312
    #24 0x558a2834f40d in UI::Box::update_desired_size() ../src/ui_basic/box.cc:147
    #25 0x558a2835293b in UI::Box::on_death(UI::Panel*) ../src/ui_basic/box.cc:460
    #26 0x558a283d7e5b in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:851
    #27 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #28 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855
    #29 0x558a283d7f15 in UI::Panel::check_child_death() ../src/ui_basic/panel.cc:855

previously allocated by thread T0 here:
    #0 0x7fde56a3df17 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x558a2834ffef in UI::Box::layout() ../src/ui_basic/box.cc:218
    #2 0x558a2834f46e in UI::Box::update_desired_size() ../src/ui_basic/box.cc:154
    #3 0x558a28351324 in UI::Box::add(UI::Panel*, UI::Box::Resizing, UI::Align) ../src/ui_basic/box.cc:317
    #4 0x558a28483e2c in MultiPlayerSetupGroup::update_players() ../src/ui_fsmenu/multiplayersetupgroup.cc:661
    #5 0x558a284829eb in operator() ../src/ui_fsmenu/multiplayersetupgroup.cc:634
    #6 0x558a284858d0 in __invoke_impl<void, MultiPlayerSetupGroup::MultiPlayerSetupGroup(UI::Panel*, int32_t, int32_t, int32_t, int32_t, GameSettingsProvider*, uint32_t)::<lambda(const NoteGameSettings&)>&, const NoteGameSettings&> /usr/include/c++/10/bits/invoke.h:60
    #7 0x558a28485753 in __invoke_r<void, MultiPlayerSetupGroup::MultiPlayerSetupGroup(UI::Panel*, int32_t, int32_t, int32_t, int32_t, GameSettingsProvider*, uint32_t)::<lambda(const NoteGameSettings&)>&, const NoteGameSettings&> /usr/include/c++/10/bits/invoke.h:153
    #8 0x558a284855a1 in _M_invoke /usr/include/c++/10/bits/std_function.h:291
    #9 0x558a282618de in std::function<void (NoteGameSettings const&)>::operator()(NoteGameSettings const&) const /usr/include/c++/10/bits/std_function.h:622
    #10 0x558a2825ea13 in void Notifications::NotificationsManager::publish<NoteGameSettings>(NoteGameSettings const&) ../src/notifications/notifications_impl.h:74
    #11 0x558a2825d15f in void Notifications::publish<NoteGameSettings>(NoteGameSettings const&) ../src/notifications/notifications.h:51
    #12 0x558a28276458 in GameHost::write_setting_player(SendPacket&, unsigned char) ../src/network/gamehost.cc:1551
    #13 0x558a282767b1 in GameHost::write_setting_all_players(SendPacket&) ../src/network/gamehost.cc:1565
    #14 0x558a282712cf in GameHost::set_map(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool) ../src/network/gamehost.cc:1117
    #15 0x558a2828a78d in HostGameSettingsProvider::set_map(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool) ../src/network/gamehost.cc:126
    #16 0x558a28458606 in FullscreenMenuLaunchMPG::select_map() ../src/ui_fsmenu/launch_mpg.cc:217
    #17 0x558a28458076 in FullscreenMenuLaunchMPG::clicked_select_map() ../src/ui_fsmenu/launch_mpg.cc:188
    #18 0x558a28456c90 in FullscreenMenuLaunchMPG::FullscreenMenuLaunchMPG(GameSettingsProvider*, GameController*, ChatProvider&) ../src/ui_fsmenu/launch_mpg.cc:130
    #19 0x558a2826aa4d in GameHost::run() ../src/network/gamehost.cc:632
    #20 0x558a27ccd0d6 in WLApplication::mainmenu_multiplayer(FullscreenMenuMain const&, bool) ../src/wlapplication.cc:1331
    #21 0x558a27ccb502 in WLApplication::mainmenu() ../src/wlapplication.cc:1202
    #22 0x558a27cbb121 in WLApplication::run() ../src/wlapplication.cc:496
    #23 0x558a27cb5cc1 in main ../src/main.cc:42
    #24 0x7fde55f3d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-use-after-free ../src/ui_basic/panel.cc:848 in UI::Panel::check_child_death()
Shadow bytes around the buggy address:
  0x0c24802158e0: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c24802158f0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2480215900: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2480215910: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c2480215920: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x0c2480215930: fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2480215940: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x0c2480215950: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2480215960: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2480215970: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c2480215980: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==66087==ABORTING
```

**Comment by jmoerschbach** [comment]
not exactly a bug of this branch, but anyways...
please try again :)

Thx for all the effort ;)

File: src/wui/game_chat_panel.h [hunk 8]
```diff
@@ -26,7 +26,6 @@
 #include "ui_basic/box.h"
 #include "ui_basic/editbox.h"
 #include "ui_basic/multilinetextarea.h"
-
```
Comment (Noordfrees) [inline src/wui/game_chat_panel.h]: no need to delete that line

File: src/ui_fsmenu/singleplayersetupbox.cc [hunk 9]
```diff
@@ -0,0 +1,172 @@
...
+     player_type_(this,
+                  (boost::format("dropdown_type%d") % static_cast<unsigned int>(id)).str(),
+                  0,
+                  0,
+                  h,
+                  h,
+                  settings,
+                  id),
+     tribe_(this,
+            (boost::format("dropdown_type%d") % static_cast<unsigned int>(id)).str(),
```
Comment (Noordfrees) [inline src/ui_fsmenu/singleplayersetupbox.cc]:
```suggestion
            (boost::format("dropdown_tribe%d") % static_cast<unsigned>(id)).str(),
```

File: src/ui_fsmenu/singleplayerdropdown.h [hunk 10]
```diff
@@ -0,0 +1,165 @@
...
+#ifndef WL_UI_FSMENU_SINGLEPLAYERDROPDOWN_H
+#define WL_UI_FSMENU_SINGLEPLAYERDROPDOWN_H
+
+#include <memory>
+#include <string>
+
+#include "logic/game_settings.h"
+#include "ui_basic/dropdown.h"
+
+template <typename T> class SinglePlayerDropDown {
```
Comment (Noordfrees) [inline src/ui_fsmenu/singleplayerdropdown.h]: Rename to `SinglePlayerDropdown` for consistency

File: src/ui_fsmenu/multiplayersetupgroup.h [hunk 11]
```diff
@@ -17,14 +17,16 @@
  *
  */
 
-#ifndef WL_WUI_MULTIPLAYERSETUPGROUP_H
-#define WL_WUI_MULTIPLAYERSETUPGROUP_H
+#ifndef WL_UI_FSMENU_MULTIPLAYERSETUPGROUP_H
+#define WL_UI_FSMENU_MULTIPLAYERSETUPGROUP_H
 
 #include <memory>
+#include <ui_basic/button.h>
```
Comment (Noordfrees) [inline src/ui_fsmenu/multiplayersetupgroup.h]: wrong include block

File: src/ui_fsmenu/mapselect.cc [hunk 12]
```diff
@@ -205,7 +205,9 @@ MapData const* FullscreenMenuMapSelect::get_map() const {
 	}
 	return &maps_data_[table_.get_selected()];
 }
-
+void FullscreenMenuMapSelect::clicked_back() {
+	FullscreenMenuLoadMapOrGame::clicked_back();
+}
```
Comment (Noordfrees) [inline src/ui_fsmenu/mapselect.cc]: What's the point of overriding this?

File: src/ui_fsmenu/mapdetailsbox.h [hunk 13]
```diff
@@ -0,0 +1,48 @@
+#ifndef WL_UI_FSMENU_MAPDETAILSBOX_H
```
Comment (Noordfrees) [inline src/ui_fsmenu/mapdetailsbox.h:20]: Add license header

File: src/ui_fsmenu/mapdetailsbox.cc [hunk 14]
```diff
@@ -0,0 +1,178 @@
+#include "ui_fsmenu/mapdetailsbox.h"
```
Comment (Noordfrees) [inline src/ui_fsmenu/mapdetailsbox.cc:20]: add license header

File: src/ui_fsmenu/mapdetailsbox.cc [hunk 15]
```diff
@@ -0,0 +1,178 @@
...
+
+#include "graphic/image_cache.h"
+#include "map_io/map_loader.h"
+
+MapDetailsBox::MapDetailsBox(
+   Panel* parent, uint32_t, uint32_t standard_element_height, uint32_t padding, int32_t, int32_t)
```
Comment (Noordfrees) [inline src/ui_fsmenu/mapdetailsbox.cc]: What are the unused parameters intended for?

File: src/ui_fsmenu/mapdetailsbox.cc [hunk 16]
```diff
@@ -0,0 +1,178 @@
...
+
+	show_map_description_savegame(game_settings);
+	show_map_name(game_settings);
+}
+void MapDetailsBox::show_map_description_savegame(const GameSettings& game_settings) {
+	std::string infotext = _("Saved players are:");
+
+	for (uint8_t i = 0; i < game_settings.players.size(); ++i) {
+		const PlayerSettings& current_player = game_settings.players.at(i);
+		infotext += "\n* ";
```
Comment (Noordfrees) [inline src/ui_fsmenu/mapdetailsbox.cc:97]: I imagine this kind of piecewise assembly would break with RTL languages. Please check whether you can use multiple nested `boost::format(_("..."))` instead. Below as well.

File: src/ui_fsmenu/launch_spg.cc [hunk 17]
```diff
@@ -315,40 +118,52 @@ void FullscreenMenuLaunchSPG::set_player_names_and_tribes() {
...
-	// Kick player 1 and take the position
-	settings_->set_player_state(0, PlayerSettings::State::kClosed);
-	settings_->set_player_state(0, PlayerSettings::State::kOpen);
-	switch_to_position(0);
+void FullscreenMenuLaunchSPG::layout() {
+	FullscreenMenuLaunchGame::layout();
+	player_setup.force_new_dimensions(scale_factor(), standard_element_height_);
 }
+
+FullscreenMenuLaunchSPG::~FullscreenMenuLaunchSPG() = default;
```
Comment (Noordfrees) [inline src/ui_fsmenu/launch_spg.cc]:
```suggestion
FullscreenMenuLaunchSPG::~FullscreenMenuLaunchSPG() {
}
```

File: src/logic/single_player_game_settings_provider.cc [hunk 18]
```diff
@@ -92,10 +92,10 @@ void SinglePlayerGameSettingsProvider::set_map(const std::string& mapname,
 	s.mapname = mapname;
 	s.mapfilename = mapfilename;
 	s.savegame = savegame;
-
-	uint32_t oldplayers = s.players.size();
 	s.players.resize(maxplayers);
 
+	set_player_number(0);
+	uint32_t oldplayers = 0;  // s.players.size();
```
Comment (Noordfrees) [inline src/logic/single_player_game_settings_provider.cc]: What do you mean by this?

File: src/logic/single_player_game_settings_provider.cc [hunk 19]
```diff
@@ -251,11 +251,25 @@ void SinglePlayerGameSettingsProvider::set_player_number(uint8_t const number) {
...
 	                                           position.state == PlayerSettings::State::kComputer)) {
+
+		// swap player but keep player name
 		set_player(number, player);
+		set_player_name(number, position.name);
+
 		set_player(settings().playernum, position);
+		// NOCOM fix player name properly. Display player name in front of each row?
+		// The condition is here to prevent crash when map is changed and the new map has less slots
+		// than the current player position.
```
Comment (Noordfrees) [inline src/logic/single_player_game_settings_provider.cc]: Is this comment still valid?

File: src/ui_fsmenu/launch_game.cc [hunk 20]
```diff
@@ -251,3 +333,7 @@ void FullscreenMenuLaunchGame::clicked_ok() {
 void FullscreenMenuLaunchGame::clicked_back() {
 	NEVER_HERE();
 }
+
+bool FullscreenMenuLaunchGame::clicked_select_map() {
+	NEVER_HERE();
```
Comment (Noordfrees) [inline src/ui_fsmenu/launch_game.cc]: Instead if having several functions that just do `NEVER_HERE` change their declarations to `some_function() = 0;`

File: src/ui_fsmenu/launch_mpg.cc [hunk 21]
```diff
@@ -89,147 +87,75 @@ struct MapOrSaveSelectionWindow : public UI::Window {
...
-	   ok_.get_y() + ok_.get_h() - mpsg_->get_y() - mpsg_->get_h() - padding_ - 1, chat,
-	   UI::PanelStyle::kFsMenu);
 	// set focus to chat input
-	chat_->focus_edit();
+	chat_.focus_edit();
+	log_dbg("mapdetails %dx%d, map %dx%d", map_details.get_w(), map_details.get_h(),
+	        map_box_.get_w(), map_box_.get_h());
+	log_dbg("ok (%d,%d) %dx%d, back (%d,%d) %dx%d", ok_.get_x(), ok_.get_y(), ok_.get_w(),
+	        ok_.get_h(), back_.get_x(), back_.get_y(), back_.get_w(), back_.get_h());
+	log_dbg("---------------------------------");
```
Comment (Noordfrees) [inline src/ui_fsmenu/launch_mpg.cc]: needs to go before merging

File: src/ui_fsmenu/launch_mpg.cc [hunk 22]
```diff
@@ -329,9 +248,10 @@ void FullscreenMenuLaunchMPG::select_saved_game() {
 		Section& s = prof.get_safe_section("global");
 
 		std::string mapname = s.get_safe_string("name");
-		nr_players_ = s.get_safe_int("nr_players");
+		auto nr_players_ = s.get_safe_int("nr_players");
```
Comment (Noordfrees) [inline src/ui_fsmenu/launch_mpg.cc]:
```suggestion
		const int nr_players = s.get_safe_int("nr_players");
```
don't use `auto` for primitive types, and no trailing underscore in local variable names please

File: src/ui_fsmenu/launch_mpg.cc [hunk 23]
```diff
@@ -380,8 +300,35 @@ void FullscreenMenuLaunchMPG::think() {
...
+			if (settings.scenario) {
+				set_scenario_values();
+			}
+		}
+		// Try to translate the map name.
+		// This will work on every official map as expected
+		// and 'fail silently' (not find a translation) for already translated campaign map names.
+		// It will also translate 'false-positively' on any user-made map which shares a name with
+		// the official maps, but this should not be a problem to worry about.
+		i18n::Textdomain td("maps");
```
Comment (Noordfrees) [inline src/ui_fsmenu/launch_mpg.cc]: This line does nothing at all because `td` goes out of scope immediately

**Review by Noordfrees — COMMENTED** [review]
No more issues spotted while testing. 
I have started to do a review, some comments inline. 
Please revert the change to `debian/rules`.

File: src/wui/game_chat_panel.h (hunk 8 above)
Comment (jmoerschbach) [reply src/wui/game_chat_panel.h]: done

File: src/ui_fsmenu/multiplayersetupgroup.h (hunk 11 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/multiplayersetupgroup.h]: done

File: src/ui_fsmenu/launch_game.cc (hunk 20 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/launch_game.cc]: done

File: src/ui_fsmenu/launch_mpg.cc (hunk 21 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/launch_mpg.cc]: done

File: src/ui_fsmenu/launch_mpg.cc (hunk 23 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/launch_mpg.cc]: removed

File: src/ui_fsmenu/launch_mpg.cc (hunk 22 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/launch_mpg.cc]: done

File: src/ui_fsmenu/mapselect.cc (hunk 12 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapselect.cc]: was for debugging purposes... removed

File: src/ui_fsmenu/singleplayerdropdown.h (hunk 10 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayerdropdown.h]: done

File: src/ui_fsmenu/singleplayersetupbox.cc (hunk 9 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayersetupbox.cc]: done

**Comment by Noordfrees** [comment]
Another minor glitch: When selecting a savegame in the LAN setup screen, the players are enumerated 0-3 instead of 1-4 in the Saved Players infotext in the right column

File: src/logic/single_player_game_settings_provider.cc (hunk 19 above)
Comment (jmoerschbach) [reply src/logic/single_player_game_settings_provider.cc]: no, removed

File: src/ui_fsmenu/singleplayersetupbox.cc [hunk 24]
```diff
@@ -55,23 +55,23 @@ SinglePlayerActivePlayerGroup::SinglePlayerActivePlayerGroup(UI::Panel* const pa
                   settings,
                   id),
      tribe_(this,
-            (boost::format("dropdown_type%d") % static_cast<unsigned int>(id)).str(),
+            (boost::format("dropdown_type%d") % static_cast<unsigned>(id)).str(),
```
Comment (Noordfrees) [inline src/ui_fsmenu/singleplayersetupbox.cc]:
```suggestion
            (boost::format("dropdown_tribe%d") % static_cast<unsigned>(id)).str(),
```

Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayersetupbox.cc]: done

File: src/ui_fsmenu/mapdetailsbox.cc (hunk 14 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapdetailsbox.cc:20]: done

File: src/ui_fsmenu/mapdetailsbox.h (hunk 13 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapdetailsbox.h:20]: done

File: src/ui_fsmenu/mapdetailsbox.cc (hunk 15 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapdetailsbox.cc]: removed

**Comment by jmoerschbach** [comment]
> 
> 
> Another minor glitch: When selecting a savegame in the LAN setup screen, the players are enumerated 0-3 instead of 1-4 in the Saved Players infotext in the right column

fixed

File: src/logic/single_player_game_settings_provider.cc (hunk 18 above)
Comment (jmoerschbach) [reply src/logic/single_player_game_settings_provider.cc]: deactivated old behaviour...
I've just rephrased it slightly to  emphasize map settings are reset when map is changed

File: src/ui_fsmenu/launch_spg.cc (hunk 17 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/launch_spg.cc]: okay... :)

File: src/ui_fsmenu/mapdetailsbox.cc (hunk 16 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapdetailsbox.cc:97]: hmm, will check how to do that...
actually this is code as it was - just moved it into a new class

File: src/ui_fsmenu/singleplayersetupbox.cc (hunk 24 above)
Comment (Noordfrees) [reply src/ui_fsmenu/singleplayersetupbox.cc]: The dropdown *still* has the wrong internal name ;)

File: src/ui_fsmenu/mapdetailsbox.cc (hunk 16 above)
Comment (Noordfrees) [reply src/ui_fsmenu/mapdetailsbox.cc:97]: Fair point. Do you want to look into this here? If not, just leave a TODO and I'll have some fun with it after this branch is merged

File: src/ui_fsmenu/singleplayersetupbox.cc (hunk 24 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/singleplayersetupbox.cc]: upsi, sry, just looked at the static_cast.
fixed now :)

File: src/ui_fsmenu/mapdetailsbox.cc (hunk 16 above)
Comment (jmoerschbach) [reply src/ui_fsmenu/mapdetailsbox.cc:97]: I'll leave a TODO, invested enough time in this one already... ;)

**Review by Noordfrees — COMMENTED** [review]
Good :)
Now you only need to revert the change to `debian/rules` (I guess it slipped in by accident?), and the includes script is unhappy:
```
Superfluous includes in ./ui_fsmenu/multiplayersetupgroup.h
	ui_basic/button.h
```
Then this can go in

**Comment by jmoerschbach** [comment]
> 
> 
> Good :)
> Now you only need to revert the change to `debian/rules` (I guess it slipped in by accident?), and the includes script is unhappy:
> 
> ```
> Superfluous includes in ./ui_fsmenu/multiplayersetupgroup.h
> 	ui_basic/button.h
> ```
> 
> Then this can go in

done and done :) Let's see if travis is happy and then, finally... ;)

**Review by Noordfrees — APPROVED** [review]

**Comment by hessenfarmer** [comment]
A big thank you to @jmoerschbach for his patience and endurance to get this done

**Comment by jmoerschbach** [comment]
> 
> 
> A big thank you to @jmoerschbach for his patience and endurance to get this done

thanks :) learned quite some new things, especially UI::Box haha

**Comment by gunchleoc** [comment]
Yep. UI::Box can be fun.
