### PR TITLE
Make AI supplycheck non recursive and more efficient

### LINKED ISSUE #5854: Infinite recursion and crash with segmentation fault in `src/ai/defaultai.cc:6918` (`AI::DefaultAI::check_supply(AI::BuildingObserver const&)`).
*EDIT: Backtrace of debug build available, see [next comment](#issuecomment-1509620690). The backtrace points to `src/ai/defaultai.cc:6918`.*

Ahoj,

### Describe the bug

I just encountered a segmentation fault of unknown origin. It is reproducable.

It appeared at some progress with the game, one human player (European tribe) and ohne computer player (Barbarian tribe).

I restarted widelands (compiled without debugging symbols) in GDB and resumed from the automatic savegame, and it crashed again after a short time.

The last lines of `widelands`'s output are:

```
[00:00:21.677 real] WARNING: Unused key "carrier" in LuaTable. Please report as a bug.
[00:00:21.677 real] WARNING: Unused key "carrier2" in LuaTable. Please report as a bug.
[00:00:25.795 real] WARNING: The AI needs the tribe 'barbarians' to define 1 type of well at the most. This is the building that produces the ware 'water', has no inputs and mines the 'resource_water'.
```

The terminal output of `widelands`, started within `gdb`, is:

```
Starting program: /usr/bin/widelands                                                                                                                          
[Thread debugging using libthread_db enabled]                                                                                                                 
Using host libthread_db library "/usr/lib/libthread_db.so.1".
This is Widelands version 1.2~git26104 (059c44a@makepkg) Debug                                                                                                
[00:00:00.000 real] INFO: Set home directory: /home/[...]/.widelands
[00:00:00.000 real] INFO: Set configuration file: /home/[...]/.widelands/config
[00:00:00.000 real] WARNING: No locale translations found in /usr/share/widelands/locale
[00:00:00.000 real] INFO: selected language: de
[00:00:00.000 real] INFO: using locale de_DE
[00:00:00.033 real] INFO: Adding directory: /usr/share/widelands
[00:00:00.033 real] INFO: selected language: de
[00:00:00.034 real] INFO: using locale de_DE
[00:00:00.046 real] INFO: Byte order: little-endian
[New Thread 0x7fffea0976c0 (LWP 22477)]                                                                                                                       
[New Thread 0x7fffe60966c0 (LWP 22478)]
[New Thread 0x7fffd3fff6c0 (LWP 22479)]
[New Thread 0x7fffcfffe6c0 (LWP 22480)]
[New Thread 0x7fffc3fff6c0 (LWP 22481)]
[New Thread 0x7fffbfffe6c0 (LWP 22482)]
[Thread 0x7fffbfffe6c0 (LWP 22482) exited]
[Thread 0x7fffc3fff6c0 (LWP 22481) exited]
[00:00:00.965 real] INFO: Graphics: Try to set Videomode 800x600
[New Thread 0x7fffc3fff6c0 (LWP 22486)]
[New Thread 0x7fffbfffe6c0 (LWP 22490)]
[00:00:01.039 real] INFO: Graphics: OpenGL: Version "4.6 (Compatibility Profile) Mesa 23.1.0-devel (git-c8949db0cc)"
[00:00:01.040 real] INFO: Graphics: SDL_GL_RED_SIZE is 8
[00:00:01.040 real] INFO: Graphics: SDL_GL_GREEN_SIZE is 8
[00:00:01.040 real] INFO: Graphics: SDL_GL_BLUE_SIZE is 8
[00:00:01.040 real] INFO: Graphics: SDL_GL_ALPHA_SIZE is 0
[00:00:01.041 real] INFO: Graphics: SDL_GL_BUFFER_SIZE is 24
[00:00:01.046 real] INFO: Graphics: SDL_GL_DOUBLEBUFFER is 1
[00:00:01.046 real] INFO: Graphics: SDL_GL_DEPTH_SIZE is 24
[00:00:01.046 real] INFO: Graphics: SDL_GL_STENCIL_SIZE is 0
[00:00:01.046 real] INFO: Graphics: SDL_GL_ACCUM_RED_SIZE is 0
[00:00:01.047 real] INFO: Graphics: SDL_GL_ACCUM_GREEN_SIZE is 0
[00:00:01.047 real] INFO: Graphics: SDL_GL_ACCUM_BLUE_SIZE is 0
[00:00:01.047 real] INFO: Graphics: SDL_GL_ACCUM_ALPHA_SIZE is 0
[00:00:01.047 real] INFO: Graphics: SDL_GL_STEREO is 0
[00:00:01.050 real] INFO: Graphics: SDL_GL_MULTISAMPLEBUFFERS is 0
[00:00:01.051 real] INFO: Graphics: SDL_GL_MULTISAMPLESAMPLES is 0
[00:00:01.051 real] INFO: Graphics: SDL_GL_ACCELERATED_VISUAL is 1
[00:00:01.051 real] INFO: Graphics: SDL_GL_CONTEXT_MAJOR_VERSION is 2
[00:00:01.051 real] INFO: Graphics: SDL_GL_CONTEXT_MINOR_VERSION is 1
[00:00:01.051 real] INFO: Graphics: SDL_GL_CONTEXT_FLAGS is 0
[00:00:01.052 real] INFO: Graphics: SDL_GL_CONTEXT_PROFILE_MASK is 0
[00:00:01.052 real] INFO: Graphics: SDL_GL_SHARE_WITH_CURRENT_CONTEXT is 0
[00:00:01.052 real] INFO: Graphics: SDL_GL_FRAMEBUFFER_SRGB_CAPABLE is 0
[00:00:01.052 real] INFO: Graphics: OpenGL: Double buffering enabled
[00:00:01.052 real] INFO: Graphics: OpenGL: Max texture size: 16384
[00:00:01.053 real] INFO: Graphics: OpenGL: ShadingLanguage: "4.60"
[00:00:01.059 real] INFO: **** GRAPHICS REPORT ****
[00:00:01.059 real] INFO: VIDEO DRIVER GLVND x11
[00:00:01.059 real] INFO: Display #0: 1280x720 @ 60hz SDL_PIXELFORMAT_RGB888
[00:00:01.059 real] INFO: Display #1: 1280x1024 @ 75hz SDL_PIXELFORMAT_RGB888
[00:00:03.104 real] INFO: **** SOUND REPORT ****
[00:00:03.104 real] INFO: SDL version: 2.26.5
[00:00:03.104 real] INFO: SDL_mixer version: 2.6.3
[00:00:03.104 real] INFO: **** END SOUND REPORT ****
[New Thread 0x7fffe1c956c0 (LWP 22545)]                                                                                                                       
[New Thread 0x7fff8bfff6c0 (LWP 22546)]
[New Thread 0x7fff7ffff6c0 (LWP 22550)]
[00:00:03.725 real] WARNING: DescriptionManager::register_description linden_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.725 real] WARNING: DescriptionManager::register_description linden_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.725 real] WARNING: DescriptionManager::register_description linden_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.725 real] WARNING: DescriptionManager::register_description linden_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.725 real] WARNING: The registry file addons/white_summer.wad/immovables/linden/register.lua
[00:00:03.725 real] WARNING:     defines multiple (4) units: linden_summer_mature linden_summer_old linden_summer_pole linden_summer_sapling
[00:00:03.725 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.725 real] WARNING: DescriptionManager::register_description pine_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.725 real] WARNING: DescriptionManager::register_description pine_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: DescriptionManager::register_description pine_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: DescriptionManager::register_description pine_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: The registry file addons/white_summer.wad/immovables/pine/register.lua
[00:00:03.726 real] WARNING:     defines multiple (4) units: pine_summer_mature pine_summer_old pine_summer_pole pine_summer_sapling
[00:00:03.726 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.726 real] WARNING: DescriptionManager::register_description red_maple_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: DescriptionManager::register_description red_maple_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: DescriptionManager::register_description red_maple_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: DescriptionManager::register_description red_maple_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.726 real] WARNING: The registry file addons/white_summer.wad/immovables/red maple/register.lua
[00:00:03.726 real] WARNING:     defines multiple (4) units: red_maple_summer_mature red_maple_summer_old red_maple_summer_pole red_maple_summer_sapling
[00:00:03.726 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.731 real] WARNING: The registry file addons/white_summer.wad/terrains/register.lua
[00:00:03.731 real] WARNING:     defines multiple (18) units: summer_clearing1 summer_clearing2 summer_clearing3 summer_dolomites1 summer_dolomites2 summer_dolomites_meadow summer_flowering_meadow1 summer_flowering_meadow2 summer_flowering_meadow3 summer_flowering_meadow4 summer_forested_dolomites1 summer_forested_dolomites2 summer_forested_dolomites3 summer_green_water1 summer_green_water2 summer_green_water3 summer_muddy_water summer_wet_beach
[00:00:03.731 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.732 real] WARNING: DescriptionManager::register_description corymbia_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description corymbia_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description corymbia_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description corymbia_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: The registry file addons/tropics.wad/immovables/trees/corymbia/register.lua
[00:00:03.732 real] WARNING:     defines multiple (4) units: corymbia_tropic_mature corymbia_tropic_old corymbia_tropic_pole corymbia_tropic_sapling
[00:00:03.732 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.732 real] WARNING: DescriptionManager::register_description ebony_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description ebony_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description ebony_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: DescriptionManager::register_description ebony_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.732 real] WARNING: The registry file addons/tropics.wad/immovables/trees/ebonytree/register.lua
[00:00:03.732 real] WARNING:     defines multiple (4) units: ebony_tropic_mature ebony_tropic_old ebony_tropic_pole ebony_tropic_sapling
[00:00:03.732 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.733 real] WARNING: DescriptionManager::register_description kapok_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description kapok_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description kapok_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description kapok_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: The registry file addons/tropics.wad/immovables/trees/kapok/register.lua
[00:00:03.733 real] WARNING:     defines multiple (4) units: kapok_tropic_mature kapok_tropic_old kapok_tropic_pole kapok_tropic_sapling
[00:00:03.733 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.733 real] WARNING: DescriptionManager::register_description lapacho_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description lapacho_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description lapacho_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: DescriptionManager::register_description lapacho_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.733 real] WARNING: The registry file addons/tropics.wad/immovables/trees/lapacho/register.lua
[00:00:03.733 real] WARNING:     defines multiple (4) units: lapacho_tropic_mature lapacho_tropic_old lapacho_tropic_pole lapacho_tropic_sapling
[00:00:03.733 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.734 real] WARNING: DescriptionManager::register_description mangrove_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description mangrove_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description mangrove_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description mangrove_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: The registry file addons/tropics.wad/immovables/trees/mangrove/register.lua
[00:00:03.734 real] WARNING:     defines multiple (4) units: mangrove_tropic_mature mangrove_tropic_old mangrove_tropic_pole mangrove_tropic_sapling
[00:00:03.734 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.734 real] WARNING: DescriptionManager::register_description palm_peach_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description palm_peach_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description palm_peach_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: DescriptionManager::register_description palm_peach_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.734 real] WARNING: The registry file addons/tropics.wad/immovables/trees/peachpalm/register.lua
[00:00:03.734 real] WARNING:     defines multiple (4) units: palm_peach_tropic_mature palm_peach_tropic_old palm_peach_tropic_pole palm_peach_tropic_sapling
[00:00:03.734 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.735 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.735 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.735 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.735 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:03.735 real] WARNING: The registry file addons/tropics.wad/immovables/trees/syagruspalm/register.lua
[00:00:03.735 real] WARNING:     defines multiple (4) units: palm_syargus_tropic_mature palm_syargus_tropic_old palm_syargus_tropic_pole palm_syargus_tropic_sapling
[00:00:03.735 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:03.736 real] WARNING: The registry file addons/tropics.wad/terrains/register.lua
[00:00:03.736 real] WARNING:     defines multiple (18) units: tropics_beach tropics_fen1 tropics_fen2 tropics_forest_mountain1 tropics_forest_mountain2 tropics_forest_mountain3 tropics_mountain1 tropics_mountain2 tropics_mountain3 tropics_rocky_soil1 tropics_rocky_soil2 tropics_soil1 tropics_soil2 tropics_soil3 tropics_soil4 tropics_swamp tropics_water1 tropics_water2
[00:00:03.736 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:04.057 real] WARNING: The registry file addons/perma-resi.wad/resi/amazons/register.lua
[00:00:04.057 real] WARNING:     defines multiple (5) units: amazons_resi_gold_1 amazons_resi_gold_2 amazons_resi_none amazons_resi_stones_1 amazons_resi_stones_2
[00:00:04.057 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:04.057 real] WARNING: The registry file addons/perma-resi.wad/resi/atlanteans/register.lua
[00:00:04.057 real] WARNING:     defines multiple (10) units: atlanteans_resi_coal_1 atlanteans_resi_coal_2 atlanteans_resi_gold_1 atlanteans_resi_gold_2 atlanteans_resi_iron_1 atlanteans_resi_iron_2 atlanteans_resi_none atlanteans_resi_stones_1 atlanteans_resi_stones_2 atlanteans_resi_water
[00:00:04.057 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:04.058 real] WARNING: The registry file addons/perma-resi.wad/resi/barbarians/register.lua
[00:00:04.058 real] WARNING:     defines multiple (10) units: barbarians_resi_coal_1 barbarians_resi_coal_2 barbarians_resi_gold_1 barbarians_resi_gold_2 barbarians_resi_iron_1 barbarians_resi_iron_2 barbarians_resi_none barbarians_resi_stones_1 barbarians_resi_stones_2 barbarians_resi_water
[00:00:04.058 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:04.058 real] WARNING: The registry file addons/perma-resi.wad/resi/empire/register.lua
[00:00:04.058 real] WARNING:     defines multiple (10) units: empire_resi_coal_1 empire_resi_coal_2 empire_resi_gold_1 empire_resi_gold_2 empire_resi_iron_1 empire_resi_iron_2 empire_resi_none empire_resi_stones_1 empire_resi_stones_2 empire_resi_water
[00:00:04.058 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:04.059 real] WARNING: The registry file addons/perma-resi.wad/resi/frisians/register.lua
[00:00:04.059 real] WARNING:     defines multiple (10) units: frisians_resi_coal_1 frisians_resi_coal_2 frisians_resi_gold_1 frisians_resi_gold_2 frisians_resi_iron_1 frisians_resi_iron_2 frisians_resi_none frisians_resi_stones_1 frisians_resi_stones_2 frisians_resi_water
[00:00:04.059 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.914 real] WARNING: DescriptionManager::register_description linden_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.915 real] WARNING: DescriptionManager::register_description linden_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.915 real] WARNING: DescriptionManager::register_description linden_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.915 real] WARNING: DescriptionManager::register_description linden_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.915 real] WARNING: The registry file addons/white_summer.wad/immovables/linden/register.lua
[00:00:09.915 real] WARNING:     defines multiple (4) units: linden_summer_mature linden_summer_old linden_summer_pole linden_summer_sapling
[00:00:09.915 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.915 real] WARNING: DescriptionManager::register_description pine_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.915 real] WARNING: DescriptionManager::register_description pine_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: DescriptionManager::register_description pine_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: DescriptionManager::register_description pine_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: The registry file addons/white_summer.wad/immovables/pine/register.lua
[00:00:09.916 real] WARNING:     defines multiple (4) units: pine_summer_mature pine_summer_old pine_summer_pole pine_summer_sapling
[00:00:09.916 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.916 real] WARNING: DescriptionManager::register_description red_maple_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: DescriptionManager::register_description red_maple_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: DescriptionManager::register_description red_maple_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: DescriptionManager::register_description red_maple_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.916 real] WARNING: The registry file addons/white_summer.wad/immovables/red maple/register.lua
[00:00:09.916 real] WARNING:     defines multiple (4) units: red_maple_summer_mature red_maple_summer_old red_maple_summer_pole red_maple_summer_sapling
[00:00:09.916 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.923 real] WARNING: The registry file addons/white_summer.wad/terrains/register.lua
[00:00:09.923 real] WARNING:     defines multiple (18) units: summer_clearing1 summer_clearing2 summer_clearing3 summer_dolomites1 summer_dolomites2 summer_dolomites_meadow summer_flowering_meadow1 summer_flowering_meadow2 summer_flowering_meadow3 summer_flowering_meadow4 summer_forested_dolomites1 summer_forested_dolomites2 summer_forested_dolomites3 summer_green_water1 summer_green_water2 summer_green_water3 summer_muddy_water summer_wet_beach
[00:00:09.923 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.924 real] WARNING: DescriptionManager::register_description corymbia_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.925 real] WARNING: DescriptionManager::register_description corymbia_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.925 real] WARNING: DescriptionManager::register_description corymbia_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.925 real] WARNING: DescriptionManager::register_description corymbia_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.925 real] WARNING: The registry file addons/tropics.wad/immovables/trees/corymbia/register.lua
[00:00:09.925 real] WARNING:     defines multiple (4) units: corymbia_tropic_mature corymbia_tropic_old corymbia_tropic_pole corymbia_tropic_sapling
[00:00:09.925 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.926 real] WARNING: DescriptionManager::register_description ebony_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.926 real] WARNING: DescriptionManager::register_description ebony_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.926 real] WARNING: DescriptionManager::register_description ebony_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.926 real] WARNING: DescriptionManager::register_description ebony_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.926 real] WARNING: The registry file addons/tropics.wad/immovables/trees/ebonytree/register.lua
[00:00:09.926 real] WARNING:     defines multiple (4) units: ebony_tropic_mature ebony_tropic_old ebony_tropic_pole ebony_tropic_sapling
[00:00:09.926 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.927 real] WARNING: DescriptionManager::register_description kapok_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.927 real] WARNING: DescriptionManager::register_description kapok_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.927 real] WARNING: DescriptionManager::register_description kapok_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.927 real] WARNING: DescriptionManager::register_description kapok_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.927 real] WARNING: The registry file addons/tropics.wad/immovables/trees/kapok/register.lua
[00:00:09.927 real] WARNING:     defines multiple (4) units: kapok_tropic_mature kapok_tropic_old kapok_tropic_pole kapok_tropic_sapling
[00:00:09.927 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.928 real] WARNING: DescriptionManager::register_description lapacho_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.928 real] WARNING: DescriptionManager::register_description lapacho_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.928 real] WARNING: DescriptionManager::register_description lapacho_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.928 real] WARNING: DescriptionManager::register_description lapacho_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.928 real] WARNING: The registry file addons/tropics.wad/immovables/trees/lapacho/register.lua
[00:00:09.928 real] WARNING:     defines multiple (4) units: lapacho_tropic_mature lapacho_tropic_old lapacho_tropic_pole lapacho_tropic_sapling
[00:00:09.928 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.929 real] WARNING: DescriptionManager::register_description mangrove_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.929 real] WARNING: DescriptionManager::register_description mangrove_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.929 real] WARNING: DescriptionManager::register_description mangrove_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.929 real] WARNING: DescriptionManager::register_description mangrove_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.929 real] WARNING: The registry file addons/tropics.wad/immovables/trees/mangrove/register.lua
[00:00:09.929 real] WARNING:     defines multiple (4) units: mangrove_tropic_mature mangrove_tropic_old mangrove_tropic_pole mangrove_tropic_sapling
[00:00:09.929 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.929 real] WARNING: DescriptionManager::register_description palm_peach_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.929 real] WARNING: DescriptionManager::register_description palm_peach_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.930 real] WARNING: DescriptionManager::register_description palm_peach_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.930 real] WARNING: DescriptionManager::register_description palm_peach_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.930 real] WARNING: The registry file addons/tropics.wad/immovables/trees/peachpalm/register.lua
[00:00:09.930 real] WARNING:     defines multiple (4) units: palm_peach_tropic_mature palm_peach_tropic_old palm_peach_tropic_pole palm_peach_tropic_sapling
[00:00:09.930 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.930 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.931 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.931 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.931 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:09.931 real] WARNING: The registry file addons/tropics.wad/immovables/trees/syagruspalm/register.lua
[00:00:09.931 real] WARNING:     defines multiple (4) units: palm_syargus_tropic_mature palm_syargus_tropic_old palm_syargus_tropic_pole palm_syargus_tropic_sapling
[00:00:09.931 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:09.933 real] WARNING: The registry file addons/tropics.wad/terrains/register.lua
[00:00:09.933 real] WARNING:     defines multiple (18) units: tropics_beach tropics_fen1 tropics_fen2 tropics_forest_mountain1 tropics_forest_mountain2 tropics_forest_mountain3 tropics_mountain1 tropics_mountain2 tropics_mountain3 tropics_rocky_soil1 tropics_rocky_soil2 tropics_soil1 tropics_soil2 tropics_soil3 tropics_soil4 tropics_swamp tropics_water1 tropics_water2
[00:00:09.933 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:10.368 real] WARNING: The registry file addons/perma-resi.wad/resi/amazons/register.lua
[00:00:10.368 real] WARNING:     defines multiple (5) units: amazons_resi_gold_1 amazons_resi_gold_2 amazons_resi_none amazons_resi_stones_1 amazons_resi_stones_2
[00:00:10.368 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:10.369 real] WARNING: The registry file addons/perma-resi.wad/resi/atlanteans/register.lua
[00:00:10.369 real] WARNING:     defines multiple (10) units: atlanteans_resi_coal_1 atlanteans_resi_coal_2 atlanteans_resi_gold_1 atlanteans_resi_gold_2 atlanteans_resi_iron_1 atlanteans_resi_iron_2 atlanteans_resi_none atlanteans_resi_stones_1 atlanteans_resi_stones_2 atlanteans_resi_water
[00:00:10.369 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:10.370 real] WARNING: The registry file addons/perma-resi.wad/resi/barbarians/register.lua
[00:00:10.370 real] WARNING:     defines multiple (10) units: barbarians_resi_coal_1 barbarians_resi_coal_2 barbarians_resi_gold_1 barbarians_resi_gold_2 barbarians_resi_iron_1 barbarians_resi_iron_2 barbarians_resi_none barbarians_resi_stones_1 barbarians_resi_stones_2 barbarians_resi_water
[00:00:10.370 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:10.371 real] WARNING: The registry file addons/perma-resi.wad/resi/empire/register.lua
[00:00:10.371 real] WARNING:     defines multiple (10) units: empire_resi_coal_1 empire_resi_coal_2 empire_resi_gold_1 empire_resi_gold_2 empire_resi_iron_1 empire_resi_iron_2 empire_resi_none empire_resi_stones_1 empire_resi_stones_2 empire_resi_water
[00:00:10.371 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:10.371 real] WARNING: The registry file addons/perma-resi.wad/resi/frisians/register.lua
[00:00:10.371 real] WARNING:     defines multiple (10) units: frisians_resi_coal_1 frisians_resi_coal_2 frisians_resi_gold_1 frisians_resi_gold_2 frisians_resi_iron_1 frisians_resi_iron_2 frisians_resi_none frisians_resi_stones_1 frisians_resi_stones_2 frisians_resi_water
[00:00:10.371 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.680 real] WARNING: The registry file addons/perma-resi.wad/resi/amazons/register.lua
[00:00:13.680 real] WARNING:     defines multiple (5) units: amazons_resi_gold_1 amazons_resi_gold_2 amazons_resi_none amazons_resi_stones_1 amazons_resi_stones_2
[00:00:13.680 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.681 real] WARNING: The registry file addons/perma-resi.wad/resi/atlanteans/register.lua
[00:00:13.681 real] WARNING:     defines multiple (10) units: atlanteans_resi_coal_1 atlanteans_resi_coal_2 atlanteans_resi_gold_1 atlanteans_resi_gold_2 atlanteans_resi_iron_1 atlanteans_resi_iron_2 atlanteans_resi_none atlanteans_resi_stones_1 atlanteans_resi_stones_2 atlanteans_resi_water
[00:00:13.681 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.682 real] WARNING: The registry file addons/perma-resi.wad/resi/barbarians/register.lua
[00:00:13.682 real] WARNING:     defines multiple (10) units: barbarians_resi_coal_1 barbarians_resi_coal_2 barbarians_resi_gold_1 barbarians_resi_gold_2 barbarians_resi_iron_1 barbarians_resi_iron_2 barbarians_resi_none barbarians_resi_stones_1 barbarians_resi_stones_2 barbarians_resi_water
[00:00:13.682 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.682 real] WARNING: The registry file addons/perma-resi.wad/resi/empire/register.lua
[00:00:13.682 real] WARNING:     defines multiple (10) units: empire_resi_coal_1 empire_resi_coal_2 empire_resi_gold_1 empire_resi_gold_2 empire_resi_iron_1 empire_resi_iron_2 empire_resi_none empire_resi_stones_1 empire_resi_stones_2 empire_resi_water
[00:00:13.682 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.683 real] WARNING: The registry file addons/perma-resi.wad/resi/frisians/register.lua
[00:00:13.683 real] WARNING:     defines multiple (10) units: frisians_resi_coal_1 frisians_resi_coal_2 frisians_resi_gold_1 frisians_resi_gold_2 frisians_resi_iron_1 frisians_resi_iron_2 frisians_resi_none frisians_resi_stones_1 frisians_resi_stones_2 frisians_resi_water
[00:00:13.683 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.699 real] WARNING: DescriptionManager::register_description linden_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.699 real] WARNING: DescriptionManager::register_description linden_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.699 real] WARNING: DescriptionManager::register_description linden_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.699 real] WARNING: DescriptionManager::register_description linden_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.699 real] WARNING: The registry file addons/white_summer.wad/immovables/linden/register.lua
[00:00:13.699 real] WARNING:     defines multiple (4) units: linden_summer_mature linden_summer_old linden_summer_pole linden_summer_sapling
[00:00:13.699 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.700 real] WARNING: DescriptionManager::register_description pine_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description pine_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description pine_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description pine_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: The registry file addons/white_summer.wad/immovables/pine/register.lua
[00:00:13.700 real] WARNING:     defines multiple (4) units: pine_summer_mature pine_summer_old pine_summer_pole pine_summer_sapling
[00:00:13.700 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.700 real] WARNING: DescriptionManager::register_description red_maple_summer_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description red_maple_summer_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description red_maple_summer_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: DescriptionManager::register_description red_maple_summer_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.700 real] WARNING: The registry file addons/white_summer.wad/immovables/red maple/register.lua
[00:00:13.700 real] WARNING:     defines multiple (4) units: red_maple_summer_mature red_maple_summer_old red_maple_summer_pole red_maple_summer_sapling
[00:00:13.700 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.707 real] WARNING: The registry file addons/white_summer.wad/terrains/register.lua
[00:00:13.707 real] WARNING:     defines multiple (18) units: summer_clearing1 summer_clearing2 summer_clearing3 summer_dolomites1 summer_dolomites2 summer_dolomites_meadow summer_flowering_meadow1 summer_flowering_meadow2 summer_flowering_meadow3 summer_flowering_meadow4 summer_forested_dolomites1 summer_forested_dolomites2 summer_forested_dolomites3 summer_green_water1 summer_green_water2 summer_green_water3 summer_muddy_water summer_wet_beach
[00:00:13.707 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.708 real] WARNING: DescriptionManager::register_description corymbia_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.708 real] WARNING: DescriptionManager::register_description corymbia_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.708 real] WARNING: DescriptionManager::register_description corymbia_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.708 real] WARNING: DescriptionManager::register_description corymbia_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.708 real] WARNING: The registry file addons/tropics.wad/immovables/trees/corymbia/register.lua
[00:00:13.708 real] WARNING:     defines multiple (4) units: corymbia_tropic_mature corymbia_tropic_old corymbia_tropic_pole corymbia_tropic_sapling
[00:00:13.708 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.709 real] WARNING: DescriptionManager::register_description ebony_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.709 real] WARNING: DescriptionManager::register_description ebony_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.709 real] WARNING: DescriptionManager::register_description ebony_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.709 real] WARNING: DescriptionManager::register_description ebony_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.709 real] WARNING: The registry file addons/tropics.wad/immovables/trees/ebonytree/register.lua
[00:00:13.709 real] WARNING:     defines multiple (4) units: ebony_tropic_mature ebony_tropic_old ebony_tropic_pole ebony_tropic_sapling
[00:00:13.709 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.710 real] WARNING: DescriptionManager::register_description kapok_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description kapok_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description kapok_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description kapok_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: The registry file addons/tropics.wad/immovables/trees/kapok/register.lua
[00:00:13.710 real] WARNING:     defines multiple (4) units: kapok_tropic_mature kapok_tropic_old kapok_tropic_pole kapok_tropic_sapling
[00:00:13.710 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.710 real] WARNING: DescriptionManager::register_description lapacho_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description lapacho_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description lapacho_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: DescriptionManager::register_description lapacho_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.710 real] WARNING: The registry file addons/tropics.wad/immovables/trees/lapacho/register.lua
[00:00:13.710 real] WARNING:     defines multiple (4) units: lapacho_tropic_mature lapacho_tropic_old lapacho_tropic_pole lapacho_tropic_sapling
[00:00:13.710 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.711 real] WARNING: DescriptionManager::register_description mangrove_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.711 real] WARNING: DescriptionManager::register_description mangrove_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.711 real] WARNING: DescriptionManager::register_description mangrove_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.711 real] WARNING: DescriptionManager::register_description mangrove_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.711 real] WARNING: The registry file addons/tropics.wad/immovables/trees/mangrove/register.lua
[00:00:13.711 real] WARNING:     defines multiple (4) units: mangrove_tropic_mature mangrove_tropic_old mangrove_tropic_pole mangrove_tropic_sapling
[00:00:13.711 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_peach_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_peach_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_peach_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_peach_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: The registry file addons/tropics.wad/immovables/trees/peachpalm/register.lua
[00:00:13.712 real] WARNING:     defines multiple (4) units: palm_peach_tropic_mature palm_peach_tropic_old palm_peach_tropic_pole palm_peach_tropic_sapling
[00:00:13.712 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_mature: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_old: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_pole: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: DescriptionManager::register_description palm_syargus_tropic_sapling: add-on entities should define '__skip_if_exists' or '__replace_if_exists'
[00:00:13.712 real] WARNING: The registry file addons/tropics.wad/immovables/trees/syagruspalm/register.lua
[00:00:13.712 real] WARNING:     defines multiple (4) units: palm_syargus_tropic_mature palm_syargus_tropic_old palm_syargus_tropic_pole palm_syargus_tropic_sapling
[00:00:13.712 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:13.714 real] WARNING: The registry file addons/tropics.wad/terrains/register.lua
[00:00:13.714 real] WARNING:     defines multiple (18) units: tropics_beach tropics_fen1 tropics_fen2 tropics_forest_mountain1 tropics_forest_mountain2 tropics_forest_mountain3 tropics_mountain1 tropics_mountain2 tropics_mountain3 tropics_rocky_soil1 tropics_rocky_soil2 tropics_soil1 tropics_soil2 tropics_soil3 tropics_soil4 tropics_swamp tropics_water1 tropics_water2
[00:00:13.714 real] WARNING:     Defining multiple units in one file is error-prone. Every unit should be defined in a registry directory of its own.
[00:00:21.559 real] WARNING: Trainingsite 'europeans_battlearena_level_4': Key 'soldier_health' is no longer needed
[00:00:21.560 real] WARNING: Trainingsite 'europeans_battlearena_level_4': Key 'soldier_attack' is no longer needed
[00:00:21.560 real] WARNING: Trainingsite 'europeans_battlearena_level_4': Key 'soldier_defense' is no longer needed
[00:00:21.560 real] WARNING: Trainingsite 'europeans_battlearena_level_4': Key 'soldier_evade' is no longer needed
[00:00:21.564 real] WARNING: Trainingsite 'europeans_battlearena_level_3': Key 'soldier_health' is no longer needed
[00:00:21.565 real] WARNING: Trainingsite 'europeans_battlearena_level_3': Key 'soldier_attack' is no longer needed
[00:00:21.565 real] WARNING: Trainingsite 'europeans_battlearena_level_3': Key 'soldier_defense' is no longer needed
[00:00:21.565 real] WARNING: Trainingsite 'europeans_battlearena_level_3': Key 'soldier_evade' is no longer needed
[00:00:21.568 real] WARNING: Trainingsite 'europeans_battlearena_level_2': Key 'soldier_health' is no longer needed
[00:00:21.569 real] WARNING: Trainingsite 'europeans_battlearena_level_2': Key 'soldier_attack' is no longer needed
[00:00:21.569 real] WARNING: Trainingsite 'europeans_battlearena_level_2': Key 'soldier_defense' is no longer needed
[00:00:21.569 real] WARNING: Trainingsite 'europeans_battlearena_level_2': Key 'soldier_evade' is no longer needed
[00:00:21.573 real] WARNING: Trainingsite 'europeans_battlearena_level_1': Key 'soldier_health' is no longer needed
[00:00:21.574 real] WARNING: Trainingsite 'europeans_battlearena_level_1': Key 'soldier_attack' is no longer needed
[00:00:21.574 real] WARNING: Trainingsite 'europeans_battlearena_level_1': Key 'soldier_defense' is no longer needed
[00:00:21.574 real] WARNING: Trainingsite 'europeans_battlearena_level_1': Key 'soldier_evade' is no longer needed
[00:00:21.576 real] WARNING: Trainingsite 'europeans_battlearena_basic': Key 'soldier_health' is no longer needed
[00:00:21.577 real] WARNING: Trainingsite 'europeans_battlearena_basic': Key 'soldier_attack' is no longer needed
[00:00:21.577 real] WARNING: Trainingsite 'europeans_battlearena_basic': Key 'soldier_defense' is no longer needed
[00:00:21.577 real] WARNING: Trainingsite 'europeans_battlearena_basic': Key 'soldier_evade' is no longer needed
[00:00:21.676 real] WARNING: Tribe europeans specifies no warehouse_names
[00:00:21.677 real] WARNING: Unused key "carrier" in LuaTable. Please report as a bug.
[00:00:21.677 real] WARNING: Unused key "carrier2" in LuaTable. Please report as a bug.
[00:00:25.795 real] WARNING: The AI needs the tribe 'barbarians' to define 1 type of well at the most. This is the building that produces the ware 'water', has no inputs and mines the 'resource_water'.

Thread 12 "widelands" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7ffff6c0 (LWP 22550)]
0x0000555555bf4aa7 in AI::DefaultAI::check_supply(AI::BuildingObserver const&) ()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
────────────────────────────────────────────────────────────────────────[ REGISTERS ]─────────────────────────────────────────────────────────────────────────
 RAX  0x55555a6b6a50 ◂— 0x55500f3e000f
 RBX  0x0
 RCX  0x0
 RDX  0x55555a6d7b50 ◂— 0xd00540010000f
 RDI  0x55555a692080 —▸ 0x555555f20518 —▸ 0x555555bdb5b0 (AI::DefaultAI::~DefaultAI()) ◂— push   r14
 RSI  0x55555a656c10 —▸ 0x555558280220 ◂— 'barbarians_fishers_hut'
 R8   0x55555a6b6a50 ◂— 0x55500f3e000f
 R9   0x1
 R10  0x0
 R11  0x55555a4c8a48 —▸ 0x5555564f14e0 —▸ 0x555556683fd0 —▸ 0x555555f19cd8 —▸ 0x555555a62f50 (Widelands::Warehouse::~Warehouse()) ◂— ...
 R12  0x55555a653610 —▸ 0x555557f05c70 ◂— 'frisians_wooden_tower_high'
 R13  0x55555a656c10 —▸ 0x555558280220 ◂— 'barbarians_fishers_hut'
 R14  0x55555a6b6a52 ◂— 0x55500f3e
 R15  0x55555a65b410 ◂— 0x6f1485873287dd42
 RBP  0x0
 RSP  0x7fff7bffffe0 ◂— 0x0
 RIP  0x555555bf4aa7 ◂— mov    qword ptr [rsp + 0x18], rdi
──────────────────────────────────────────────────────────────────────────[ DISASM ]──────────────────────────────────────────────────────────────────────────
 ► 0x555555bf4aa7    mov    qword ptr [rsp + 0x18], rdi
   0x555555bf4aac    cmp    rbx, rbp
   0x555555bf4aaf    mov    qword ptr [rsp + 0x10], rbx
   0x555555bf4ab4    mov    qword ptr [rsp + 8], 0
   0x555555bf4abd    je     0x555555bf4b35                <0x555555bf4b35>
    ↓
   0x555555bf4b35    mov    rax, qword ptr [rsp + 0x10]
   0x555555bf4b3a    sub    rbp, rax
   0x555555bf4b3d    mov    rax, qword ptr [rsp + 8]
   0x555555bf4b42    sar    rbp, 1
   0x555555bf4b45    cmp    rbp, rax
   0x555555bf4b48    sete   al
──────────────────────────────────────────────────────────────────────────[ STACK ]───────────────────────────────────────────────────────────────────────────
00:0000│ rsp 0x7fff7bffffe0 ◂— 0x0
... ↓        4 skipped
05:0028│     0x7fff7c000008 —▸ 0x55555a6d7b50 ◂— 0xd00540010000f
06:0030│     0x7fff7c000010 —▸ 0x55555a6d7b62 ◂— 0x21000000000000
07:0038│     0x7fff7c000018 —▸ 0x55555a653610 —▸ 0x555557f05c70 ◂— 'frisians_wooden_tower_high'
────────────────────────────────────────────────────────────────────────[ BACKTRACE ]─────────────────────────────────────────────────────────────────────────
 ► f 0   0x555555bf4aa7
   f 1   0x555555bf4b10
   f 2   0x555555bf4b10
   f 3   0x555555bf4b10
   f 4   0x555555bf4b10
   f 5   0x555555bf4b10
   f 6   0x555555bf4b10
   f 7   0x555555bf4b10
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

(The last part is from `pwndbg` GDB extension.)

And the GDB backtrace:

It loops endlessly(?) with messages

```
[...]
#84034 0x0000555555bf4b10 in AI::DefaultAI::check_supply(AI::BuildingObserver const&) ()
#84035 0x0000555555bf4b10 in AI::DefaultAI::check_supply(AI::BuildingObserver const&) ()
#84036 0x0000555555bf4b10 in AI::DefaultAI::check_supply(AI::BuildingObserver const&) ()
[...]
```

I attach the savefile: [`wl_autosave_00.wgf.gz`](https://github.com/widelands/widelands/files/11237204/wl_autosave_00.wgf.gz)

### To reproduce

1. Use widelands git version, git checkout with latest commit hash 059c44a, from 2023-04-13,
2. Load [attached savefile](https://github.com/widelands/widelands/files/11237204/wl_autosave_00.wgf.gz),
   - Maybe install needed addons,
3. Wait a minute or so,
4. See the crash.

### Expected behavior

No crash.

## Version

- OS: [Artix GNU Linux](http://artixlinux.org/) (rolling release)
- Widelands Version: `1.2~git26104 (059c44a@makepkg)` (compiled with debugging console but without debugging symbols)

### PR DESCRIPTION
**Pull request by hessenfarmer**
**Type of change**
Bugfix / Refactoring 

**Issue(s) closed**
Fixes #5854 

**New behavior**
hopefully none. the Ai should behave like before

How it works**
Instead of checking the whole chain recursively we now only check whether the supplying building is working already. (this would mean it is fully supplied and is in fact more accurate as it checks real supply rather then theoretical supply)
Furthermore we only check the buildings that produce the input ware rather then checking all buildings outputs for the production. this should safe us a lot of cycles. 

**Possible regressions**
AI construction decisions

### CODE REVIEW

**Review by tothxa — APPROVED** [review]
Code looks OK.

I tested with a 4 AI game, and they were able to build up their economies.

A small speed-up is observable even with the standard tribes: I was able to run the early game at speed 15x before late jobs warnings started, but reloading the same in master got only up to 14x. Later game was 12x vs. 11x.

I don't have Europeans installed, so I didn't test with them.

File: src/ai/defaultai.cc [hunk 1]
```diff
@@ -6905,22 +6907,27 @@ void DefaultAI::lose_building(const Widelands::Building& b) {
 }
 
 // Checks that supply line exists for given building.
-// Recursively verify that all inputs have a producer.
-// TODO(unknown): this function leads to periodic freezes of ~1 second on big games on my system.
-// TODO(unknown): It needs profiling and optimization.
+// Verify that all inputs have a working producer (i.e. building statistics better then 10%).
```
Comment (tothxa) [inline src/ai/defaultai.cc]:
```suggestion
// Verify that all inputs have a working producer (i.e. building statistics better than 10%).
```

**Comment by hessenfarmer** [comment]
Many thanks for the review. I was surprised by the 5% performance gain as well. But I think it is a rather big improvement for just such a small change.
