### PR TITLE
4384 ai quick fix

### LINKED ISSUE #4384: crash with Attempt to add invalid Time or Duration
latest commit crashed with:

Attempt to add invalid Time or Duration

setup was lokal network 4 AI game on full moon. 

Emergency save and stdout.txt attached
[stdout.txt](https://github.com/widelands/widelands/files/5410980/stdout.txt)
[2020-10-20T20.59.14.wgf.zip](https://github.com/widelands/widelands/files/5410982/2020-10-20T20.59.14.wgf.zip)

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4384 
partly solved #4368

### CODE REVIEW

File: src/ai/defaultai.h [hunk 1]
```diff
@@ -355,10 +355,10 @@ struct DefaultAI : ComputerPlayer {
 	Time last_road_dismantled_;  // uses to prevent too frequent road dismantling
 	bool dead_ends_check_;       // Do we need to check and dismantle dead ends?
 
-	Time enemy_last_seen_;
+	// Time enemy_last_seen_;
```
Comment (gunchleoc) [inline src/ai/defaultai.h]:
```suggestion
```

**Review by gunchleoc — APPROVED** [review]
1 unused variable to delete, rest is good.
