### PR TITLE
Consistent farmers

### LINKED ISSUE #1672: farmers at home (out of fields)
Wonder if this is another regression. In the save-game you can see some completely or partly inactive farmers although their area overview shows several free spots which could be farmed and they appear to be walkable too. Obviously something is blocking recognition of these spots. (You can find these farmers in the center land where all parties meet for a battle. There are 3 to 4 such defected farmers, one of them completely inactive, one works only one field, etc.) When there is no activity at all then "out of fields" is reported on the building.

Suspicion is that Immovable objects could play a role in this, but the observation is inconsistent. Terrain shouldn't be the problem, but road congestion might be.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2017-03-03T10:41:22Z
 * owner: 7010622-q-deactivatedaccount
 * the launchpad url was https://bugs.launchpad.net/bugs/1669741

### PR DESCRIPTION
**Pull request by hessenfarmer**
made farmers of all tribes consistent. space flag in findspace programm uses now maxcaps for neighboring fields. 
fixes #1672

### CODE REVIEW

File: src/logic/map_objects/tribes/worker.cc [hunk 1]
```diff
@@ -533,7 +533,7 @@ struct FindNodeSpace {
 		for (uint8_t dir = FIRST_DIRECTION; dir <= LAST_DIRECTION; ++dir) {
 			FCoords const neighb = egbase.map().get_neighbour(coords, dir);
 
-			if (!(neighb.field->nodecaps() & MOVECAPS_WALK) &&
+			if (!(neighb.field->maxcaps() & MOVECAPS_WALK) &&
```
Comment (Noordfrees) [inline src/logic/map_objects/tribes/worker.cc]: You need to get rid of `ignoreimmovable` now, the change makes it obsolete and it might only cause corner-case bugs.

**Review by Noordfrees — APPROVED** [review]
Code LGTM, untested

**Comment by gunchleoc** [comment]
Tested and working - current branch on top, master on bottom.

farms

**Comment by stonerl** [comment]
```
../src/logic/map_objects/tribes/worker.cc:544:17: warning: private field 'ignoreimmovable' is not used [-Wunused-private-field]
        BaseImmovable* ignoreimmovable;
```

**Comment by hessenfarmer** [comment]
upps overlooked should be fixed in #3768
