### PR TITLE
amazons fixes

### LINKED ISSUE #4595: Amazon economy profiles crash
https://www.widelands.org/forum/topic/4911/?page=5#post-35878

Using one of the predefined amazon economy settings crashes the game

@hessenfarmer

### LINKED ISSUE #4606: Amazons glitches
- Starting a game with amazons reports
```
[00:00:13.042 real] INFO: ┏━ Loading amazons
[00:00:13.042 real] INFO: ┃    Ships
[00:00:13.091 real] INFO: ┃    Immovables
[00:00:13.417 real] WARNING: Unused key "species" in LuaTable. Please report as a bug.
[00:00:13.454 real] INFO: ┃    Wares
[00:00:13.523 real] INFO: ┃    Workers
[00:00:14.511 real] WARNING: Animation sound effect priority '64,00' without percent symbol is deprecated
[00:00:14.525 real] WARNING: Animation sound effect priority '64,00' without percent symbol is deprecated
[00:00:15.145 real] INFO: ┃    Buildings
[00:00:15.512 real] INFO: ┃    Frontiers, flags and roads
[00:00:15.522 real] INFO: ┃    Finalizing
[00:00:15.522 real] INFO: ┗━ took 2480ms
```
- There are no amazons-specific game tips yet in https://github.com/widelands/widelands/tree/master/data/txts/tips
- The first tutorial still mentions 4 tribes. Check for other mentions as well.

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4606 
fixes #4595

### CODE REVIEW

File: data/txts/tips/amazons.lua [hunk 1]
```diff
@@ -0,0 +1,21 @@
+push_textdomain("texts")
+tips = {
+   {
+      text = _"Amazons love trees. Build enough jungle preserver's huts to have enough of them.",
+      seconds = 6
+   },
+   {
+      text = _"Rare woods are the backbone of an amazon economy. Build rare tree plantations to plant this special trees.",
```
Comment (Noordfrees) [inline data/txts/tips/amazons.lua]:
```suggestion
      text = _"Rare woods are the backbone of an amazon economy. Build rare tree plantations to plant these special trees.",
```

**Review by Noordfrees — APPROVED** [review]
LGTM, tested and working
One inline comment
