### PR TITLE
Chasing the `SupplyList::remove_supply` crash

### LINKED ISSUE #4533: Error when closing the game: SupplyList::remove: not in list
When quitting the game by closing the window the following error sometimes occurs:
```
terminate called after throwing an instance of 'WException'
  what():  [../src/economy/supply_list.cc:48] SupplyList::remove: not in list
```
I don't have a replay. It happened twice when playing this game: [Euro_Turk_12.wgf.zip](https://github.com/widelands/widelands/files/5580762/Euro_Turk_12.wgf.zip). Happened together with #4532, maybe related?

**Version:**
 - OS: Manjaro 20.2
 - Widelands Version: 1.0~git25070[fe4c1e3@HEAD] (Release)

### LINKED ISSUE #4645: Crash after save and Quit
I get some crashes after saving a game and afterwards quitting the game.

Don't know if the cause is always the same.

**To Reproduce**
1. Load a big save game
2. Play a bit
3. Save the game
4. Quit the game

Sometimes the main menu does not appear instead the whole game crashes. This time i get an ASAN report:
> SUMMARY: AddressSanitizer: SEGV /home/kaputtnik/Quellcode/widelands-repo/widelands/src/economy/supply_list.cc:42 in Widelands::SupplyList::remove_supply(Widelands::Supply&)

[bt.txt](https://github.com/widelands/widelands/files/5886782/bt.txt)

**Version:**
 - OS: archlinux
 - Widelands Version: [a846817@master] (Debug)

### LINKED ISSUE #4792: [Duplicate] `SupplyList::remove_supply` crashes when leaving game
**Describe the bug**
The game crashed.

**To Reproduce**
While working on translation, I switched several times between Options and loaded singleplayer games, often pausing the game for a long time. The last game I loaded was originally an autosave after the host exited from a local multiplayer game. After running it at 8x speed for a while waiting for some buildings (with very low FPS - AIs not able to keep up according to stdout), I wanted to quit before memory runs out (happened a few times before, though on clean exits LeakSanitizer only reports a few hundred bytes leaked), so I saved the game (attached), and selected Exit Game. This caused the game to crash. End of stdout attached.

**Version:**
 - OS: antix / debian buster with some backports
 - Widelands Version: 1.0, 632406b9f6f00a977de9c7bd92316d0ee4784e39

[wl1_crashreport.txt](https://github.com/widelands/widelands/files/6232989/wl1_crashreport.txt)
[before_crash.wgf.gz](https://github.com/widelands/widelands/files/6232991/before_crash.wgf.gz)

### LINKED ISSUE #4857: ASAN heap-use-after-free  around IdleWareSupply::~IdleWareSupply()
Please fill out the relevant sections below and delete the rest.

**Describe the bug**

Do so some training for the Tournament I played the Barbarian Scenario.
[TournTest.wgf.zip](https://github.com/widelands/widelands/files/6473313/TournTest.wgf.zip)
I then pressed CMD-Q (Which Triggers  an SDL base Quit)

**To Reproduce**

Not sure, 
* load attached save game
*  then quit with CMD-Q (macOS) of ATLT-F4 (Winows) or such.

**Expected behavior**

No unclean shutdown

**Version:**
 - OS: MacOD BigSur 11.3.1 (20E241)
 - Widelands Version: 1.0~git25301[f6a3abd@master]

**Additional context**
```
===================================================================51538==
ERROR: AddressSanitizer: heap-use-after-free on address 0x6110005d39b8 at pc 0x00010b6dd718 bp 0x7ffee7d36a10 sp 0x7ffee7d36a08
READ of size 8 at 0x6110005d39b8 thread T0
    #0 0x10b6dd717 in std::__1::vector<Widelands::Supply*, std::__1::allocator<Widelands::Supply*> >::begin() vector:1520
    #1 0x10b6dd1f9 in Widelands::SupplyList::remove_supply(Widelands::Supply&) supply_list.cc:39
    #2 0x10b4ade55 in Widelands::Economy::remove_supply(Widelands::Supply&) economy.cc:479
    #3 0x10b6e87ab in Widelands::IdleWareSupply::set_economy(Widelands::Economy*) ware_instance.cc:92
    #4 0x10b6e895d in Widelands::IdleWareSupply::~IdleWareSupply() ware_instance.cc:83
    #5 0x10b6e89b4 in Widelands::IdleWareSupply::~IdleWareSupply() ware_instance.cc:82
    #6 0x10b6e89db in Widelands::IdleWareSupply::~IdleWareSupply() ware_instance.cc:82
    #7 0x10b6ea27d in Widelands::WareInstance::cleanup(Widelands::EditorGameBase&) ware_instance.cc:214
    #8 0x10aad0b4d in Widelands::MapObject::remove(Widelands::EditorGameBase&) map_object.cc:540
    #9 0x10aacfc55 in Widelands::ObjectManager::cleanup(Widelands::EditorGameBase&) map_object.cc:188
    #10 0x1080173b7 in Widelands::EditorGameBase::cleanup_objects() editor_game_base.h:195
    #11 0x1088dad92 in Widelands::Game::run(Widelands::Game::StartGameType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) game.cc:773
    #12 0x108db461f in GameHost::run_callback() gamehost.cc:752
    #13 0x108e15af7 in GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0::operator()() const gamehost.cc:665
    #14 0x108e15a8c in decltype(std::__1::forward<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0&>(fp)()) std::__1::__invoke<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0&>(GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0&) type_traits:3747
    #15 0x108e15a3c in void std::__1::__invoke_void_return_wrapper<void>::__call<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0&>(GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0&) __functional_base:348
    #16 0x108e15a0c in std::__1::__function::__alloc_func<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0, std::__1::allocator<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0>, void ()>::operator()() functional:1553
    #17 0x108e121ed in std::__1::__function::__func<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0, std::__1::allocator<GameHost::run(std::__1::unique_ptr<GameController, std::__1::default_delete<GameController> >&)::$_0>, void ()>::operator()() functional:1727
    #18 0x10938d515 in std::__1::__function::__value_func<void ()>::operator()() const functional:1880
    #19 0x109389624 in std::__1::function<void ()>::operator()() const functional:2555
    #20 0x1097779d7 in FsMenu::LaunchMPG::clicked_ok() launch_mpg.cc:232
    #21 0x1099933d9 in FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double)::$_1::operator()() const menu.cc:148
    #22 0x10999287c in boost::detail::function::void_function_obj_invoker0<FsMenu::TwoColumnsFullNavigationMenu::TwoColumnsFullNavigationMenu(FsMenu::MenuCapsule&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double)::$_1, void>::invoke(boost::detail::function::function_buffer&) function_template.hpp:158
    #23 0x1090c15da in boost::function0<void>::operator()() const function_template.hpp:763
    #24 0x1090c1443 in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void ()> >(boost::function<void ()>&, boost::signals2::detail::unsigned_meta_array<>, std::__1::tuple<> const&, boost::enable_if<boost::is_void<boost::function<void ()>::result_type>, void>::type*) const variadic_slot_invoker.hpp:117
    #25 0x1090c13f8 in boost::signals2::detail::void_type boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void ()>, 0ul>(boost::function<void ()>&, std::__1::tuple<> const&, mpl_::size_t<0ul>) const variadic_slot_invoker.hpp:90
    #26 0x1090c0eb8 in boost::signals2::detail::void_type boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) const variadic_slot_invoker.hpp:133
    #27 0x1090c0b61 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >::dereference() const slot_call_iterator.hpp:110
    #28 0x1090c0954 in boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >::reference boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) iterator_facade.hpp:550
    #29 0x1090c088c in boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const iterator_facade.hpp:656
    #30 0x1090c0593 in void boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const optional_last_value.hpp:57
    #31 0x1090bf5c6 in void boost::signals2::detail::combiner_invoker<void>::operator()<boost::signals2::optional_last_value<void>, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::optional_last_value<void>&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >) const result_type_wrapper.hpp:64
    #32 0x1090bedbf in boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() signal_template.hpp:242
    #33 0x109076ff5 in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() signal_template.hpp:722
    #34 0x1090023b0 in UI::Button::handle_mouserelease(unsigned char, int, int) button.cc:376
    #35 0x1091f399b in UI::Panel::do_mouserelease(unsigned char, int, int) panel.cc:1138
    #36 0x1091e079b in UI::Panel::ui_mouserelease(unsigned char, int, int) panel.cc:1332
    #37 0x107eedda5 in WLApplication::handle_mousebutton(SDL_Event&, InputCallback const*) wlapplication.cc:955
    #38 0x107eeb60b in WLApplication::handle_input(InputCallback const*) wlapplication.cc:863
    #39 0x1091df36f in UI::Panel::do_run() panel.cc:240
    #40 0x107ee8724 in int UI::Panel::run<int>() panel.h:111
    #41 0x107ee8135 in WLApplication::run() wlapplication.cc:728
    #42 0x107ec6774 in main main.cc:47
    #43 0x7fff204c1f3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

0x6110005d39b8 is located 120 bytes inside of 256-byte region [0x6110005d3940,0x6110005d3a40)
freed by thread T0 here:
    #0 0x1157020bd in wrap__ZdlPv+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x550bd)
    #1 0x107faf964 in std::__1::_DeallocateCaller::__do_call(void*) new:334
    #2 0x107faf948 in std::__1::_DeallocateCaller::__do_deallocate_handle_size(void*, unsigned long) new:292
    #3 0x107faf920 in std::__1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long) new:262
    #4 0x107faf8f4 in std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) new:340
    #5 0x107faf555 in std::__1::allocator<char>::deallocate(char*, unsigned long) memory:1673
    #6 0x107fadb47 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::dealloc() alt_sstream_impl.hpp:302
    #7 0x107fada0d in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #8 0x107fad604 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #9 0x107fad597 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #10 0x107fad144 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #11 0x10c0eb9af in RGBColor::hex_value() const color.cc:35
    #12 0x10b487e94 in UI::FontStyleInfo::as_font_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const font_style.cc:98
    #13 0x10a9509eb in as_richtext_paragraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, UI::FontStyleInfo const&, UI::Align) text_layout.cc:111
    #14 0x1092ea1ed in UI::Table<void*>::draw(RenderTarget&) table.cc:341
    #15 0x1091f00c6 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:952
    #16 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #17 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #18 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #19 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #20 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #21 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #22 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #23 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #24 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #25 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #26 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #27 0x1091dd381 in UI::Panel::do_redraw_now() panel.cc:187
    #28 0x1091df599 in UI::Panel::do_run() panel.cc:257
    #29 0x107ef4ae4 in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() panel.h:111

previously allocated by thread T0 here:
    #0 0x115701c9d in wrap__Znwm+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x54c9d)
    #1 0x107fb0008 in std::__1::__libcpp_allocate(unsigned long, unsigned long) new:253
    #2 0x107faff70 in std::__1::allocator<char>::allocate(unsigned long) memory:1664
    #3 0x107fafeb0 in std::__1::allocator<char>::allocate(unsigned long, void const*) memory:1669
    #4 0x107faf02d in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) alt_sstream_impl.hpp:261
    #5 0x7fff204121fa in std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsputn(char const*, long)+0x6c (libc++.1.dylib:x86_64+0xe1fa)
    #6 0x7fff204236ed in std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char)+0x11a (libc++.1.dylib:x86_64+0x1f6ed)
    #7 0x7fff20423223 in std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::do_put(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, std::__1::ios_base&, char, long) const+0x117 (libc++.1.dylib:x86_64+0x1f223)
    #8 0x7fff20417e61 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)+0x10f (libc++.1.dylib:x86_64+0x13e61)
    #9 0x109cac6d9 in void boost::io::detail::put_last<char, std::__1::char_traits<char>, int>(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int const&) feed_args.hpp:99
    #10 0x109cac63f in void boost::io::detail::call_put_last<char, std::__1::char_traits<char>, int const>(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, void const*) feed_args.hpp:126
    #11 0x107fd3db9 in void boost::io::detail::put_last<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&) feed_args.hpp:149
    #12 0x107fd08cf in void boost::io::detail::put<char, std::__1::char_traits<char>, std::__1::allocator<char>, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&>(boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&, boost::io::detail::format_item<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::string_type&, boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::internal_streambuf_t&, std::__1::locale*) feed_args.hpp:214
    #13 0x107fcf533 in void boost::io::detail::distribute<char, std::__1::char_traits<char>, std::__1::allocator<char>, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&>(boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&) feed_args.hpp:291
    #14 0x107fce2d4 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >& boost::io::detail::feed_impl<char, std::__1::char_traits<char>, std::__1::allocator<char>, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&>(boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, boost::io::detail::put_holder<char, std::__1::char_traits<char> > const&) feed_args.hpp:301
    #15 0x109caa667 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >& boost::io::detail::feed<char, std::__1::char_traits<char>, std::__1::allocator<char>, int const&>(boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, int const&) feed_args.hpp:313
    #16 0x109caa54c in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator%(int const&) format_class.hpp:87
    #17 0x10c0eb7b4 in RGBColor::hex_value() const color.cc:35
    #18 0x10b487e94 in UI::FontStyleInfo::as_font_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const font_style.cc:98
    #19 0x10a9509eb in as_richtext_paragraph(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, UI::FontStyleInfo const&, UI::Align) text_layout.cc:111
    #20 0x1092ea1ed in UI::Table<void*>::draw(RenderTarget&) table.cc:341
    #21 0x1091f00c6 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:952
    #22 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #23 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #24 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #25 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #26 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #27 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956
    #28 0x1091de477 in UI::Panel::do_draw(RenderTarget&) panel.cc:992
    #29 0x1091f0124 in UI::Panel::do_draw_inner(RenderTarget&) panel.cc:956

SUMMARY: AddressSanitizer: heap-use-after-free vector:1520 in std::__1::vector<Widelands::Supply*, std::__1::allocator<Widelands::Supply*> >::begin()
Shadow bytes around the buggy address:
  0x1c22000ba6e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba6f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba710: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba720: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
=>0x1c22000ba730: fd fd fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd
  0x1c22000ba740: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x1c22000ba750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c22000ba780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==51538==ABORTING
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by Noordfrees**
Supersedes #4858 

Fixes #4533
Fixes #4645
Fixes #4792
Fixes #4857

### CODE REVIEW

**Comment by klaus-halfmann** [comment]
moved the inline functions from SupplyList to normal fucntions for better debugging.
First glance from XCode: this is aclled when merging/spliiting economies (which I always try  to avoid 😄)
and when fleets/ships/ports are involved.

**Comment by klaus-halfmann** [comment]
Uhhm this change resuts in a desync :-(

```
void SupplyList::remove_supply(Supply& supp) {
	for (Supplies::iterator item_iter = supplies_.begin(); item_iter != supplies_.end();
	     ++item_iter) {
		if (*item_iter == &supp) {
                        // why this way?
			// *item_iter = *(supplies_.end() - 1); // copy last elemnt to current positon
			// supplies_.pop_back();                // remove lasr element duplicated above
            supplies_.erase(item_iter);
			return;
		}
	}
	throw wexception("SupplyList::remove: not in list");
}
```

**Comment by klaus-halfmann** [comment]
This SupplyList::remove_supply can not work wen the vector has just one element or is empty? 
Why does this not happen normally?

**Comment by Noordfrees** [comment]
The desync happens because you change the iteration order. What we do now is to overwrite the to-be-deleted entry with the last entry and then delete the last one. Your change simply erases an element without moving the last element. The order in which supplies are iterated is used as a tie-breaker for equally good supplies (or something like that…) so changing it results in a game logic change.

When the vector is empty, the `for` loop is simply skipped because `begin() != end()` is always `false` then. And when it has exactly 1 element, then `*iter = *(end() - 1);` is just a self-assignment, as `iter` and `end() - 1` then both point to the only element. So it is safe in all cases (though not the most elegant implementation).

**Comment by klaus-halfmann** [comment]
Thanks @Noordfrees for the explaiantion, I adde some code to make the code more debug friendly,
I still crashes but now I get:

```
==92291==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000603cf8 at pc 0x0001108f91d1 bp 0x7ffee2b171d0 sp 0x7ffee2b171c8
READ of size 8 at 0x611000603cf8 thread T0
    #0 0x1108f91d0 in std::__1::vector<Widelands::Supply*, std::__1::allocator<Widelands::Supply*> >::empty() const vector:664
    #1 0x1108f8c24 in Widelands::SupplyList::remove_supply(Widelands::Supply&) supply_list.cc:51
    #2 0x1106c94a5 in Widelands::Economy::remove_supply(Widelands::Supply&) economy.cc:479
... 
0x611000603cf8 is located 120 bytes inside of 256-byte region [0x611000603c80,0x611000603d80)
freed by thread T0 here:
    #0 0x11a9020bd in wrap__ZdlPv+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x550bd)
    #1 0x10d1cf1b4 in std::__1::_DeallocateCaller::__do_call(void*) new:334
    #2 0x10d1cf198 in std::__1::_DeallocateCaller::__do_deallocate_handle_size(void*, unsigned long) new:292
    #3 0x10d1cf170 in std::__1::_DeallocateCaller::__do_deallocate_handle_size_align(void*, unsigned long, unsigned long) new:262
    #4 0x10d1cf144 in std::__1::__libcpp_deallocate(void*, unsigned long, unsigned long) new:340
    #5 0x10d1ceda5 in std::__1::allocator<char>::deallocate(char*, unsigned long) memory:1673
    #6 0x10d1cd397 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::dealloc() alt_sstream_impl.hpp:302
    #7 0x10d1cd25d in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #8 0x10d1cce54 in boost::io::basic_altstringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_altstringbuf() alt_sstream.hpp:67
    #9 0x10d1ccde7 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #10 0x10d1cc994 in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_format() format_fwd.hpp:25
    #11 0x11130780f in RGBColor::hex_value() const color.cc:35
    #12 0x10d852f23 in StyleManager::color_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGBColor const&) style_manager.cc:387
    #13 0x10ffbe23e in Widelands::Ship::draw(Widelands::EditorGameBase const&, InfoToDraw const&, Vector2<float> const&, Widelands::Coords const&, float, RenderTarget*) const ship.cc:1039
    #14 0x10f792803 in InteractiveSpectator::draw_map_view(MapView*, RenderTarget*) interactive_spectator.cc:113

This is totally unrelated code, but perhaps that formatting has an Issue?

previously allocated by thread T0 here:
     #16 0x10eeca63c in boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator%(int const&) format_class.hpp:87
    #17 0x111307614 in RGBColor::hex_value() const color.cc:35
    #18 0x10d852f23 in StyleManager::color_tag(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RGBColor const&) style_manager.cc:387
    #19 0x10ffbe23e in Widelands::Ship::draw(Widelands::EditorGameBase const&, InfoToDraw const&, Vector2<float> const&, Widelands::Coords const&, float, RenderTarget*) const ship.cc:1039
```
[Complete Crash logs](https://github.com/widelands/widelands/files/6593406/Crash.txt)

No idea how / if this helps

**Comment by klaus-halfmann** [comment]
I found no way to trgigger an asan check directly. For now I am lost, may try again next weekend.

**Comment by Noordfrees** [comment]
To me this looks like the `IdleWareSupply`'s `economy_` is a wild pointer as the ware's economy (and therefore the `Economy`'s member variable `supplies_` as well) was deleted earlier than the ware itself. When I tried to get the ware's location with GDB it told me that the `Player` that owns the `WareInstance` has apparently also been deleted by this time already.
The thing is, a ware can only belong to a worker, flag, or ship. Workers and ships are deleted before wares and delete their wares along with themselves. The wares remaining then delete themselves earlier than the flags so their economies should still exist then. There must be something wrong with the destruction order on deletion but I still have no idea where

**Comment by Noordfrees** [comment]
The commit I just pushed changes the end-of-game destruction order. Instead of a crash I now get 
```
terminate called after throwing an instance of 'WException'
  what():  [../src/economy/supply_list.cc:52] SupplyList::remove: list is empty
```
which looks a bit better already ;) perhaps this will also be more useful for further debugging

---

In the testsuite, ASan says:
```
=================================================================
==4341==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000251b58 at pc 0x559daa42a890 bp 0x7ffd96ac7940 sp 0x7ffd96ac7930
READ of size 4 at 0x611000251b58 thread T0
    #0 0x559daa42a88f in Widelands::Economy::remove_wares_or_workers(unsigned short, unsigned int) ../src/economy/economy.cc:386
    #1 0x559daa548a5a in Widelands::WareInstance::set_economy(Widelands::Economy*) ../src/economy/ware_instance.cc:232
    #2 0x559daa548e0a in Widelands::WareInstance::set_location(Widelands::EditorGameBase&, Widelands::MapObject*) ../src/economy/ware_instance.cc:282
    #3 0x559daa5488f0 in Widelands::WareInstance::cleanup(Widelands::EditorGameBase&) ../src/economy/ware_instance.cc:217
    #4 0x559daa085165 in Widelands::MapObject::remove(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:544
    #5 0x559daa07fce9 in Widelands::ObjectManager::cleanup(Widelands::EditorGameBase&) ../src/logic/map_objects/map_object.cc:187
    #6 0x559da9382baf in Widelands::EditorGameBase::cleanup_objects() ../src/logic/editor_game_base.h:195
    #7 0x559da96ee1f8 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:773
    #8 0x559da96e8ab8 in Widelands::Game::run_splayer_scenario_direct(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:310
    #9 0x559da927d269 in WLApplication::run() ../src/wlapplication.cc:713
    #10 0x559da9271fd1 in main ../src/main.cc:47
    #11 0x7f8257e86564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #12 0x559da9271e6d in _start (/home/benedikt/wl/naval_warfare/widelands+0x52fe6d)

0x611000251b58 is located 88 bytes inside of 248-byte region [0x611000251b00,0x611000251bf8)
freed by thread T0 here:
    #0 0x7f825a6d40c7 in operator delete(void*) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:160
    #1 0x559da9751d2d in std::default_delete<Widelands::Economy>::operator()(Widelands::Economy*) const (/home/benedikt/wl/naval_warfare/widelands+0xa0fd2d)
    #2 0x559da97421e8 in std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> >::~unique_ptr() /usr/include/c++/10/bits/unique_ptr.h:361
    #3 0x559da977d247 in std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >::~pair() /usr/include/c++/10/bits/stl_pair.h:211
    #4 0x559da977d26b in void __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::destroy<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >(std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >*) /usr/include/c++/10/ext/new_allocator.h:156
    #5 0x559da97775c4 in void std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > > >::destroy<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >(std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >&, std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >*) /usr/include/c++/10/bits/alloc_traits.h:531
    #6 0x559da976e848 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::_M_destroy_node(std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >*) /usr/include/c++/10/bits/stl_tree.h:646
    #7 0x559da975dc5a in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::_M_drop_node(std::_Rb_tree_node<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >*) /usr/include/c++/10/bits/stl_tree.h:654
    #8 0x559da9765ab1 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::_M_erase_aux(std::_Rb_tree_const_iterator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >) (/home/benedikt/wl/naval_warfare/widelands+0xa23ab1)
    #9 0x559da9752b9b in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > >, std::_Select1st<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >) /usr/include/c++/10/bits/stl_tree.h:1216
    #10 0x559da974287b in std::map<unsigned int, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > > >::erase[abi:cxx11](std::_Rb_tree_iterator<std::pair<unsigned int const, std::unique_ptr<Widelands::Economy, std::default_delete<Widelands::Economy> > > >) (/home/benedikt/wl/naval_warfare/widelands+0xa0087b)
    #11 0x559da971e935 in Widelands::Player::remove_economy(unsigned int) ../src/logic/player.cc:1143
    #12 0x559daa16ea10 in Widelands::Ship::Expedition::~Expedition() ../src/logic/map_objects/tribes/ship.cc:1115
    #13 0x559daa176c37 in std::default_delete<Widelands::Ship::Expedition>::operator()(Widelands::Ship::Expedition*) const /usr/include/c++/10/bits/unique_ptr.h:85
    #14 0x559daa177e5a in std::__uniq_ptr_impl<Widelands::Ship::Expedition, std::default_delete<Widelands::Ship::Expedition> >::reset(Widelands::Ship::Expedition*) /usr/include/c++/10/bits/unique_ptr.h:182
    #15 0x559daa1747bf in std::unique_ptr<Widelands::Ship::Expedition, std::default_delete<Widelands::Ship::Expedition> >::reset(Widelands::Ship::Expedition*) /usr/include/c++/10/bits/unique_ptr.h:456
    #16 0x559daa167dae in Widelands::Ship::ship_update_idle(Widelands::Game&, Widelands::Bob::State&) ../src/logic/map_objects/tribes/ship.cc:691
    #17 0x559daa162d3e in Widelands::Ship::ship_update(Widelands::Game&, Widelands::Bob::State&) ../src/logic/map_objects/tribes/ship.cc:291
    #18 0x559da9fec2e9 in Widelands::Bob::do_act(Widelands::Game&) ../src/logic/map_objects/bob.cc:194
    #19 0x559da9fec043 in Widelands::Bob::act(Widelands::Game&, unsigned int) ../src/logic/map_objects/bob.cc:180
    #20 0x559daa07edee in Widelands::CmdAct::execute(Widelands::Game&) ../src/logic/map_objects/map_object.cc:106
    #21 0x559daa597d08 in Widelands::CmdQueue::run_queue(Duration const&, Time&) ../src/logic/cmd_queue.cc:122
    #22 0x559da96eeb03 in Widelands::Game::think() ../src/logic/game.cc:797
    #23 0x559da9c9ae65 in InteractiveBase::think() ../src/wui/interactive_base.cc:682
    #24 0x559da9d2ab86 in InteractivePlayer::think() ../src/wui/interactive_player.cc:418
    #25 0x559da98efe79 in UI::Panel::do_think() ../src/ui_basic/panel.cc:599
    #26 0x559da98ec2d2 in UI::Panel::do_run() ../src/ui_basic/panel.cc:247
    #27 0x559da92a95fb in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() ../src/ui_basic/panel.h:111
    #28 0x559da96ee0c5 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:767
    #29 0x559da96e8ab8 in Widelands::Game::run_splayer_scenario_direct(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:310

previously allocated by thread T0 here:
    #0 0x7f825a6d35a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x559da971e140 in Widelands::Player::create_economy(Widelands::WareWorker) ../src/logic/player.cc:1119
    #2 0x559daa169f6b in Widelands::Ship::start_task_expedition(Widelands::Game&) ../src/logic/map_objects/tribes/ship.cc:826
    #3 0x559daa4df9de in Widelands::ShippingSchedule::start_expedition(Widelands::Game&, Widelands::Ship&, Widelands::PortDock&) ../src/economy/shipping_schedule.cc:119
    #4 0x559daa4e002a in Widelands::ShippingSchedule::ship_arrived(Widelands::Game&, Widelands::Ship&, Widelands::PortDock&) ../src/economy/shipping_schedule.cc:141
    #5 0x559daa499c2b in Widelands::PortDock::ship_arrived(Widelands::Game&, Widelands::Ship&) ../src/economy/portdock.cc:342
    #6 0x559daa1632a9 in Widelands::Ship::ship_update_transport(Widelands::Game&, Widelands::Bob::State&) ../src/logic/map_objects/tribes/ship.cc:313
    #7 0x559daa162a3b in Widelands::Ship::ship_update(Widelands::Game&, Widelands::Bob::State&) ../src/logic/map_objects/tribes/ship.cc:265
    #8 0x559da9fec2e9 in Widelands::Bob::do_act(Widelands::Game&) ../src/logic/map_objects/bob.cc:194
    #9 0x559da9fec043 in Widelands::Bob::act(Widelands::Game&, unsigned int) ../src/logic/map_objects/bob.cc:180
    #10 0x559daa07edee in Widelands::CmdAct::execute(Widelands::Game&) ../src/logic/map_objects/map_object.cc:106
    #11 0x559daa597d08 in Widelands::CmdQueue::run_queue(Duration const&, Time&) ../src/logic/cmd_queue.cc:122
    #12 0x559da96eeb03 in Widelands::Game::think() ../src/logic/game.cc:797
    #13 0x559da9c9ae65 in InteractiveBase::think() ../src/wui/interactive_base.cc:682
    #14 0x559da9d2ab86 in InteractivePlayer::think() ../src/wui/interactive_player.cc:418
    #15 0x559da98efe79 in UI::Panel::do_think() ../src/ui_basic/panel.cc:599
    #16 0x559da98ec2d2 in UI::Panel::do_run() ../src/ui_basic/panel.cc:247
    #17 0x559da92a95fb in UI::Panel::Returncodes UI::Panel::run<UI::Panel::Returncodes>() ../src/ui_basic/panel.h:111
    #18 0x559da96ee0c5 in Widelands::Game::run(Widelands::Game::StartGameType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:767
    #19 0x559da96e8ab8 in Widelands::Game::run_splayer_scenario_direct(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../src/logic/game.cc:310
    #20 0x559da927d269 in WLApplication::run() ../src/wlapplication.cc:713
    #21 0x559da9271fd1 in main ../src/main.cc:47
    #22 0x7f8257e86564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-use-after-free ../src/economy/economy.cc:386 in Widelands::Economy::remove_wares_or_workers(unsigned short, unsigned int)
Shadow bytes around the buggy address:
  0x0c2280042310: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280042320: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280042330: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2280042340: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280042350: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
=>0x0c2280042360: fd fd fd fd fd fd fd fd fd fd fd[fd]fd fd fd fd
  0x0c2280042370: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa
  0x0c2280042380: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2280042390: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c22800423a0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c22800423b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==4341==ABORTING
```
which gives me a good idea where to look :)

**Comment by Noordfrees** [comment]
I think I fixed it now :) 
Let's wait what the testsuite says though…

The fix is essentially a one-liner, like all bugfixes that need to be chased for weeks or months :P

File: src/logic/map_objects/tribes/ship.cc [hunk 1]
```diff
@@ -649,6 +649,7 @@ void Ship::ship_update_idle(Game& game, Bob::State& state) {
 					} else {
 						wq->set_filled(wq->get_filled() + 1);
 					}
+					ware->remove(game);
```
Comment (klaus-halfmann) [inline src/logic/map_objects/tribes/ship.cc:657]: If this is the fix, please explain this line and that ship_update_idle deserves some refactoring ...

**Review by klaus-halfmann — CHANGES_REQUESTED** [review]
Will give it a try now

**Review by klaus-halfmann — CHANGES_REQUESTED** [review]
Whatever you actually did (still no clue).
**this fixed the Issue**. Shall I revert my Changes?
Or shall we set up a "clean" branch with only the acual fix.?

**Comment by Noordfrees** [comment]
The diff looks fine to me as it is so the branch is good for merging in its current state in my opinion.

The actual fix is a simple oversight: When an expedition ship unloads wares to the new port constructionsite, the wares are "semantically" destroyed but they remained in existence in a non-well-defined state. With this fix they are fully removed when they ought to be.

**Review by klaus-halfmann — COMMENTED** [review]
Let me (mostly) revert supply_list.h/.cc

**Review by klaus-halfmann — APPROVED** [review]
OK for me now

**Comment by klaus-halfmann** [comment]
Will merge this (hey my first real merge to master!) tonight unless someone else steps foreward.

**Comment by Noordfrees** [comment]
No this is not critical so merging should wait until after the release
