### PR TITLE
4911 ai fixes

### LINKED ISSUE #1006: AI makes shipyard away from sea
It happened that i was playtesting a map with seafaring and the ai made a shipyard in a place too far from water. it was close to a river one tile wide, where boats cannot be built; it sits useless. but the ai cannot figure it out; it hasn't dismantled the shipyard, nor has it made a new one in a better place.
built is 7852.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2016-03-07T23:39:50Z
 * owner: lainluigi86
 * assignee: tiborb95
 * the launchpad url was https://bugs.launchpad.net/bugs/1554267

### LINKED ISSUE #4087: AI builds shipyard on non-seafaring map
Build21: The AI has built a shipyard on a non-seafaring map (Crater).
Savegame: https://www.widelands.org/forum/topic/4924/?page=1#post-34170

@tibor95 

See also #1689

### LINKED ISSUE #4558: AI behaves wrong in scenarios
Some recent playtesting showed the AI behaving differently in Scenarios than in normal single player.
Especially it does not expand / does not build military buildings. This is going away with a save and reload.

### LINKED ISSUE #4669: AI dont enhanced trainingsites, if there are only 3 mines.
If an AI don't build more than 3 mines, for whatever reason, no upgrade of trainingsite is started. Even if all other requirements are met and 3 mines are completely sufficient to supply the economy with coal and ore.

See https://www.widelands.org/forum/topic/5146/?page=1#post-36083

apply to-> bool DefaultAI::check_trainingsites(const Time& gametime) 

My proposed solution: Instead of checking the number of mines, the amount of weapons and armor should be used as criterion. We can check which wares are defined as input for the enhancement. If the player has at least one of each kind, the enhancement should be started.

### LINKED ISSUE #4911: AI bugs and glitches in v1.0
1. this line

https://github.com/widelands/widelands/blob/0976a570055e43df6e7847c2831d08f6d09286e7/src/ai/defaultai.cc#L5628

should prevent the AI from building rangers if not at least one lumberjack was built.  With v1.0 we allowed multiple Lumberjacks to be designed in a tribe (e.g. amazons and europeans) so it is not necessarily the related lumberjack for the ranger in question. In fact for amazons and europeans an upgraded Lumberjack is considered.     
As it is not really stopping amazons, due to the upgraded Lumberjack built soon we might postpone this to v1.1. However Europeans will not work properly in AI without that fixed

2. detection of lumberjack is dependent on log used as build material. Should be detected by the immovables harvested.   

3. Detection of second carrier recruitment is not granular enough.     

4. Assertion in line defaultai.cc:3038 prevents rangers from being forced, which is against the concept of the forced_after parameter.    

5. genetic algorithm for determining Neededness of rangers is increasing the score if rangers are not allowed due to woodpolicy (e.g. defaultai.cc:5621). this should be the other way round.

### PR DESCRIPTION
**Pull request by hessenfarmer**
fixes #4911 
except the recruitment site detection
fixes #1006
fixes #4087 (hopefully)
fixes #4558 
fixes #4669

### CODE REVIEW

**Comment by hessenfarmer** [comment]
@MarkMcWire as this should fix some of the europeans AI problems you might want to give this branch a short test and see how it performs in your eyes on the problems described in the linked issue?

**Comment by MarkMcWire** [comment]
I will testing it today.

**Comment by MarkMcWire** [comment]
[00:01:07.574 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of barracks building. This is the building that produces the tribe's 'soldier' worker.
[00:01:07.574 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of well at the most. This is the building that produces the ware 'water', has no inputs and mines the 'resource_water'.
[00:01:07.574 real] WARNING: The AI needs the tribe 'europeans' to define 1 type of hunter's building at the most. Hunters are buildings that collect any bob from the map.

Is it possible to change this, too? Or is that getting too complicated for the AI of the original tribes?

@hessenfarmer @Noordfrees

**Comment by hessenfarmer** [comment]
This warning is ok for the Europeans as they have only one buildable building of each type and the others are upgrades. AI can Handle this to a certain extent but it definitly will have difficulties if it has more then one type of them that can be built directly.

**Comment by MarkMcWire** [comment]
> This warning is ok for the Europeans as they have only one buildable building of each type and the others are upgrades. AI can Handle this to a certain extent but it definitly will have difficulties if it has more then one type of them that can be built directly.

The question is, why is this not a problem for lumberjack and fisher, but it is for hunters? I dont understand this logic.
Shouldn't fishers and hunters be equivalent?

**Comment by hessenfarmer** [comment]
> 
> 
> > This warning is ok for the Europeans as they have only one buildable building of each type and the others are upgrades. AI can Handle this to a certain extent but it definitly will have difficulties if it has more then one type of them that can be built directly.
> 
> The question is, why is this not a problem for lumberjack and fisher, but it is for hunters? I dont understand this logic.
> Shouldn't fishers and hunters be equivalent?

I never claimed the AI behaviour is 100% logical. Currently the design needs to be like this as the AI handles the buildings in this way. We might work on getting rid of these restrictions but this is not that easy.     
The difference between fishers and hunters for the AI is that fishers need open water with fish while hunters don't need any special place.

**Comment by MarkMcWire** [comment]
> > > This warning is ok for the Europeans as they have only one buildable building of each type and the others are upgrades. AI can Handle this to a certain extent but it definitly will have difficulties if it has more then one type of them that can be built directly.
> > 
> > 
> > The question is, why is this not a problem for lumberjack and fisher, but it is for hunters? I dont understand this logic.
> > Shouldn't fishers and hunters be equivalent?
> 
> I never claimed the AI behaviour is 100% logical. Currently the design needs to be like this as the AI handles the buildings in this way. We might work on getting rid of these restrictions but this is not that easy.
> The difference between fishers and hunters for the AI is that fishers need open water with fish while hunters don't need any special place.

What if I develop a tribe that needs fish as a staple food but no meat? Or to keep up with the times: a vegan tribe? I have even seriously considered the latter for my tribe.

**Comment by MarkMcWire** [comment]
> @MarkMcWire as this should fix some of the europeans AI problems you might want to give this branch a short test and see how it performs in your eyes on the problems described in the linked issue?

I will testing it today and this weekende. If I find some serious problems, I will inform you here.

**Comment by hessenfarmer** [comment]
> What if I develop a tribe that needs fish as a staple food but no meat? Or to keep up with the times: a vegan tribe? I have even seriously considered the latter for my tribe.     
   
The AI needs exactly one fisher to be defined, which is the case for Europeans. It does not necessarily need a hunter but if a tribe has a hunter it should only have one. 
For a vegan tribe you will get another warning about the fisher and everything should be ok. (one would have to see how the AI will handle it.       
The AI needs to know the purpose of the buildings to decide what to build. Therefore we have all these detection algorithms implemented. The fisher is still detected from an AI Hint so for the europeans only the basic fisher is detected (which is correct).   

Regarding lumberjacks we invented the possibility for multiple lumberjacks in r1.0 and got a Bug that is fixed with this PR and still it isn't perfect.     
When designing a tribe one need to know the boundaries of the AI if the tribe should be handled properly. Nevertheless it is hard to write them all down as some problems can't be imagined beforehand.

**Comment by MarkMcWire** [comment]
> When designing a tribe one need to know the boundaries of the AI if the tribe should be handled properly. Nevertheless it is hard to write them all down as some problems can't be imagined beforehand.

I fully understand the implications and do not want to criticize your work or make it look bad.

The problem seems to me to be that the Tribes were developed first and then the AI. A universal AI should be completely independent of the technology tree of a tribe. Based on the technology tree alone, it should be able to recognize which buildings and in which number they have to build in which location.

Therefore, your current development is going in the completely right direction.

**Comment by MarkMcWire** [comment]
> When designing a tribe one need to know the boundaries of the AI if the tribe should be handled properly. Nevertheless it is hard to write them all down as some problems can't be imagined beforehand.

A human player can think backwards. He knows that to train a soldier he needs this and that armor or weapon. So he knows that he has to build a smithy. He knows that he needs metals for the forge and thus a smelting works. With that he knows that he needs a mine for ore and a mine for coal or a charcoal kiln. 
With that he knows that he needs lumberjacks. Since the mines need food and drink, he knows he needs a tavern and a brewery. To do this, he needs wells for the water and mills for the flour. The mills need grain, which means he needs farms.
He knows also, that he needs for tavern meat or fish, so he has to build a piggery, a hunting house and or a fishers house.
He also can imagine, that he needs a fishbreeder and or gamekeeper to support fisher and hunter.

The AI must proceed in exactly the same way if it is not already doing it.

**Comment by hessenfarmer** [comment]
> A human player can think backwards. He knows that to train a soldier he needs this and that armor or weapon. So he knows that he has to build a smithy. He knows that he needs metals for the forge and thus a smelting works. With that he knows that he needs a mine for ore and a mine for coal or a charcoal kiln.
> With that he knows that he needs lumberjacks. Since the mines need food and drink, he knows he needs a tavern and a brewery. To do this, he needs wells for the water and mills for the flour. The mills need grain, which means he needs farms.
> He knows also, that he needs for tavern meat or fish, so he has to build a piggery, a hunting house and or a fishers house.
> He also can imagine, that he needs a fishbreeder and or gamekeeper to support fisher and hunter.
> 
> The AI must proceed in exactly the same way if it is not already doing it.     
    
The problem is to know when a new building of a type is needed. This is the current approach of the AI. Based on stock and other (weighed) factors it determines the most needed building and tries to build it. For this we don't need any knowledge of the chain you described. But we act more the less on shortage of stock which is less efficient then proactively avoid these shortages.     
In this direction the concept you described may have some advantage in making the decisions better. So I will keep it in mind. Still it would be hard to determine the correct chain and dependencies in the code from the lua definitions alone.

**Comment by hessenfarmer** [comment]
> The problem seems to me to be that the Tribes were developed first and then the AI. A universal AI should be completely independent of the technology tree of a tribe. Based on the technology tree alone, it should be able to recognize which buildings and in which number they have to build in which location.     
   
I agree on the first part however where to build the buiodings and when is the hard part and this is dependent on the map. Anyhow we are trying (I admit that @GunChleoc pushed a bit in this direction) to determine as much information for the AI from lua as we can. Previously we laid the burden of "giving hint" to the AI on the Tribe designer, while we now aim to do this from his code. This makes it difficult to just fake some AI behaviour but makes it more general.   
So far with every new tribe the AI advanced in its complexity and abilities. As preimagination of every aspect a tribe designer might come up with is very hard.   
> 
> Therefore, your current development is going in the completely right direction.

File: src/ai/defaultai.cc [hunk 1]
```diff
@@ -5648,8 +5647,8 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo,
 			inputs[9] = (persistent_data->trees_around_cutters < 200) * 1;
 			inputs[10] = (persistent_data->trees_around_cutters < 300) * 1;
 			inputs[11] = (persistent_data->trees_around_cutters < 400) * 1;
-			inputs[12] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
-			inputs[13] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
+			inputs[12] = (wood_policy_ == WoodPolicy::kAllowRangers) * 1;
```
Comment (klaus-halfmann) [inline src/ai/defaultai.cc]: I think `(wood_policy_ == WoodPolicy::kAllowRangers)  ? 1 : 0;` wozuld make things more clear.
(Mixing boolen and int is an inheritance of C, well)

File: src/ai/defaultai.cc [hunk 2]
```diff
@@ -5664,13 +5663,13 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo,
 			inputs[22] = (basic_economy_established) ? -1 : 1;
 			inputs[23] = (msites_in_constr() > 0) ? 1 : -2;
 			inputs[24] = (msites_in_constr() > 1) ? 1 : -2;
-			inputs[25] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
+			inputs[25] = (wood_policy_ != WoodPolicy::kAllowRangers) * -1;
 			if (gametime > Time(90 * 60)) {
```
Comment (klaus-halfmann) [inline src/ai/defaultai.cc]: Is this // late game, afte 90 minutes ?

File: src/ai/defaultai.cc [hunk 3]
```diff
@@ -5664,13 +5663,13 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo,
...
-				inputs[26] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
+				inputs[26] = (wood_policy_ == WoodPolicy::kAllowRangers) * 1;
 				inputs[27] = (persistent_data->trees_around_cutters < 20) * 1;
 			}
 			if (gametime > Time(45 * 60)) {
```
Comment (klaus-halfmann) [inline src/ai/defaultai.cc]: Is this // middle game, afte 90 minutes ?

**Review by klaus-halfmann — CHANGES_REQUESTED** [review]
Some minor suggestions, so:
* How can I reasobaly test this?
* Shall we have a (jitsi) call for this?

**Comment by hessenfarmer** [comment]
> 
> 
> Some minor suggestions, so:
> 
>     * How can I reasobaly test this?
> 
>     * Shall we have a (jitsi) call for this?

a call would surely be helpful to explain things

File: src/ai/defaultai.cc (hunk 2 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: exactly

File: src/ai/defaultai.cc (hunk 3 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: yes after 45 min

File: src/ai/defaultai.cc (hunk 1 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: I could do this as it is done like this in other parts of the code. One short question as I reall don't know it: might there be a difference in performance between the 2 variants

File: src/ai/defaultai.cc (hunk 2 above)
Comment (klaus-halfmann) [reply src/ai/defaultai.cc]: So maybe we should heva some constants like kMidGame, kLateGame ?

File: src/ai/defaultai.cc (hunk 1 above)
Comment (klaus-halfmann) [reply src/ai/defaultai.cc]: Performance impact should be negligible with a modern compiler, but readabily will improve a lot ...

File: src/ai/defaultai.cc (hunk 2 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: there are much more points in time, which are evaluated  in the AI which would end up with a lot of constants then.

**Comment by MarkMcWire** [comment]
The problem with the woodcutter still persists for europeans. Again I used "log" as a general building material for several buildings and yet the AI does not build a lumberjack house. Even if I forced it by AI Hint or use basic_amount in AT Hints.

**Comment by MarkMcWire** [comment]
The AI builds now lumberjacks houses and forester houses, if I remove the hint "require_supporters = true". No sideeffects detected until now. 

The mine-problem still persists.

**Comment by hessenfarmer** [comment]
@MarkMcWire 
can you confirm the AI builds and manages foresters as well? As one of the fixes should ensure this. 
BTW: woodcutters do not need the supporters hint as the relation between foresters and woodcuttters is hardcoded in the AI.  
@klaus-halfmann 
I will reexpress the lines about woodpolicy as you suggested. If you are interested in some more explanations please write me an email when we can have a quick chat on Jitsi.

File: src/ai/defaultai.cc (hunk 2 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: on a close look the milliseconds were missing so I added the 1000 in all instances I found.

**Comment by MarkMcWire** [comment]
> @MarkMcWire
> can you confirm the AI builds and manages foresters as well? As one of the fixes should ensure this.
> BTW: woodcutters do not need the supporters hint as the relation between foresters and woodcuttters is hardcoded in the AI.

Confirmed. BTW: The AI hint for lumberjack is dangerous, it leads to AI behave of no building any lumberjack or forester houses at all. This hint block some code of the AI.

**Comment by hessenfarmer** [comment]
> 
> Confirmed. BTW: The AI hint for lumberjack is dangerous, it leads to AI behave of no building any lumberjack or forester houses at all. This hint block some code of the AI.

Correct.Here is the line where it is prevented 
https://github.com/widelands/widelands/blob/891df3d24be7f31b2fc2cd02dcc212d7121b9b83/src/ai/defaultai.cc#L2885

this is a self locking cycle for lumberjacks / foresters as foresters are only built if one lumberjack exists. Technically a lumberjack does not strictly require a supporter as there are normally trees around the map anyway (they are self seeding to a certain extent). so using the hint for lumberjacks is technically wrong.   
I will do the following to solve this I will replace the code in this location to not prevent but strongly discourage the building of productionsites which require a supporter and not having one (using some gentics for it to make it subject to ai training) and I will update the documentation that this hint should not be used for lumberjacks.

**Comment by klaus-halfmann** [comment]
I spend quite some CPU-Time on this BigEden Map now , on this branch 1.1~git25452[b3d21d4@4911_AI_fixes
But just before breaking out of my first "Stone Garden" I hit a crash with
libc++abi: terminating with uncaught exception of type std::out_of_range: map::at:  key not found 
based on AI::DefaultAI::construct_building(Time const&) + 38660 (defaultai.cc:2889) 

Form the Threads I don see a direct Race condition:
[TestingEden.zip](https://github.com/widelands/widelands/files/6940682/TestingEden.zip)

To reproduce load the attached save Game and let it run for a few minutes.

**Comment by hessenfarmer** [comment]
@klaus-halfmann  
ups myfault. Corrected the issue

**Comment by klaus-halfmann** [comment]
> ups myfault. Corrected the issue

Thanks works again

**Comment by klaus-halfmann** [comment]
After playing a huge game I got this crash 
[Crash.txt.zip](https://github.com/widelands/widelands/files/6988514/Crash.txt.zip)
Not sure If I can reproduce it.

**Comment by hessenfarmer** [comment]
> 
> 
> After playing a huge game I got this crash
> [Crash.txt.zip](https://github.com/widelands/widelands/files/6988514/Crash.txt.zip)
> Not sure If I can reproduce it.

For me he log shows that this crash is not related to AI so this is a bug that needs to be fixed outside this branch.

**Comment by MarkMcWire** [comment]
The change has a side effect. During the game against the Amazons, I noticed that the AI had dismantled all of the rare tree cutter huts and stopped all rare tree plantations and is now stuck in a deadlock because rubber and ironwood are missing. @hessenfarmer

**Comment by hessenfarmer** [comment]
> 
> 
> The change has a side effect. During the game against the Amazons, I noticed that the AI had dismantled all of the rare tree cutter huts and stopped all rare tree plantations and is now stuck in a deadlock because rubber and ironwood are missing. @hessenfarmer

can you upload a replay. I already realized that there is a potential cause of deadlock due to the amazons having 2 foresters but they only define one wood policy to control them. This results in all foresters being stopped and no rare woods are planted anymore.  If there are no rare trees the cutters might be dismantled due to low productivity afterwards. If this is the reason we don't have a second problem at least.

**Comment by klaus-halfmann** [comment]
Still palying on thsi brnach I got two crashes, one while interacting with some other (browser) window.
Second one aroud disamnteling some building, I guess. 
[Crash1-2.zip](https://github.com/widelands/widelands/files/7026988/Crash1-2.zip)

**Comment by hessenfarmer** [comment]
> 
> 
> Still palying on thsi brnach I got two crashes, one while interacting with some other (browser) window.
> Second one aroud disamnteling some building, I guess.
> [Crash1-2.zip](https://github.com/widelands/widelands/files/7026988/Crash1-2.zip)

again I beleive these crashes are unrelated to this branch but rather belong to master,  so please open a new bug and upload the crash texts there. I don't know how to do anything about them. The AI in this branch is not multithreaded. I just changed some small algorithms and values.

**Comment by klaus-halfmann** [comment]
I played this for some time on some giant map, but git (unrelated) crashes. Wat needs to be done to gt this mrgen now?
P:S . You can reach me just now via JitSi https://meet.ffmuc.net/WidelandsChat

**Comment by klaus-halfmann** [comment]
Had a short Talk with @hessenfarmer, he wil andd another fix (about foresters?)
Testing: Use a map with all tribes and check that the AI does a resonable job (not worse then in master).

Will check again after master has been merged (to benefit form the new, improved image files)

**Comment by hessenfarmer** [comment]
@Noordfrees maybe you could have a look intio the 2 crashes @klaus-halfmann reöorted here as they might be related to mutithreading.

**Comment by hessenfarmer** [comment]
@MarkMcWire I implemented a fix now to prevent Amazons from dismantling their rare tree plantations, due to lots of log available. 

@klaus-halfmann and @Noordfrees  
please have a look on my code changes in this commit https://github.com/widelands/widelands/pull/4995/commits/255642dea247b3a0c236c3d59aeb05635ffe8b0c
They are compiling and they are working. However I am not sure if they are good design or if there had been a better way to achieve the wood_policy per ranger goal.

**Comment by Noordfrees** [comment]
> @klaus-halfmann and @Noordfrees please have a look on my code changes in this commit [255642d](https://github.com/widelands/widelands/commit/255642dea247b3a0c236c3d59aeb05635ffe8b0c) They are compiling and they are working. However I am not sure if they are good design or if there had been a better way to achieve the wood_policy per ranger goal.

I'd suggest using `at()` instead of `[]` when looking up an existing entry in a map, e.g.
```diff,c++
- if (wood_policy_[site.bo->id] == WoodPolicy::kDismantleRangers
+ if (wood_policy_.at(site.bo->id) == WoodPolicy::kDismantleRangers
```
because `[]` has the side-effect to construct a new element if the key is not present yet, whereas `at()` throws an exception if the key is missing.
Otherwise LGTM

**Comment by hessenfarmer** [comment]
@MarkMcWire 
@klaus-halfmann 
any recent tests yet. if not I would appreciate if you could have a look.

**Review by klaus-halfmann — COMMENTED** [review]
I found no obvious flaws in your code, but I still do no really know what you are doing.

I will testplay now on a huge map with all tribes (will we need the Europeans, too?)

**Comment by hessenfarmer** [comment]
> 
> 
> I found no obvious flaws in your code, but I still do no really know what you are doing.
> 
> I will testplay now on a huge map with all tribes (will we need the Europeans, too?)

Having europeans might be good for testing.   
To test this you might open a locla network game on a 6player map and select normal AI for each slot leaving you as a spectator and then let it run.

If it helps I might add review comments to explain every change. will do so over the day

**Comment by klaus-halfmann** [comment]
[CrashAndSave.zip](https://github.com/widelands/widelands/files/7553684/CrashAndSave.zip)

@hessenfarmer i played +/- like you suggested but now hit a crash. Please take a look.
Attached is my latest autosave, too. Maybe you want to check how the AI did?

**Comment by hessenfarmer** [comment]
> 
> 
> [CrashAndSave.zip](https://github.com/widelands/widelands/files/7553684/CrashAndSave.zip)
> 
> @hessenfarmer i played +/- like you suggested but now hit a crash. Please take a look. Attached is my latest autosave, too. Maybe you want to check how the AI did?

will check the AI performance.
Regarding the crash, do you remember whether you clicked e.g. a Productionsite window as it might be the case that the this si some race condition caused by an external spectator openeing an Productionsite window while some statuses of the site are updated. 
#5052 might be related @Noordfrees maybe you could have alook intom the crash as well

**Comment by klaus-halfmann** [comment]
> do you remember whether you clicked e.g. a Productionsite window

I think I clicked some debug windows of AI-Productionsites. Maybe I should do this more often?

File: src/ai/defaultai.cc [hunk 4]
```diff
@@ -5650,12 +5692,12 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo,
 			inputs[9] = (persistent_data->trees_around_cutters < 200) * 1;
 			inputs[10] = (persistent_data->trees_around_cutters < 300) * 1;
 			inputs[11] = (persistent_data->trees_around_cutters < 400) * 1;
-			inputs[12] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
-			inputs[13] = (wood_policy_ != WoodPolicy::kAllowRangers) * 1;
+			inputs[12] = (wood_policy_.at(bo.id) == WoodPolicy::kAllowRangers) ? 1 : 0;
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:5682]: fixes #4911 Nr. 5

File: src/ai/defaultai.cc [hunk 5]
```diff
@@ -3272,7 +3318,8 @@ bool DefaultAI::construct_building(const Time& gametime) {
 					} else if (bo.is(BuildingAttribute::kShipyard)) {
 						// for now AI builds only one shipyard
 						assert(bo.total_count() == 0);
-						if (bf->open_water_nearby > 3 && map_allows_seafaring_) {
+						if (bf->open_water_nearby > 3 && map_allows_seafaring_ &&
+						    bf->shipyard_preferred == ExtendedBool::kTrue) {
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:3309]: here we ensure that only fields near ports are considered for shipyards

File: src/ai/defaultai.cc [hunk 6]
```diff
@@ -5717,10 +5759,10 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo,
 			inputs[53] = (bo.last_building_built.is_valid() &&
 			              bo.last_building_built + Duration(6 * 60 * 100) > gametime) *
 			             -2;
-			inputs[54] = (Time(5 * 60 * 100) > gametime) * -2;
-			inputs[55] = (Time(6 * 60 * 100) > gametime) * -2;
-			inputs[56] = (Time(8 * 60 * 100) > gametime) * -2;
-			inputs[57] = (Time(10 * 60 * 100) > gametime) * -2;
+			inputs[54] = (Time(5 * 60 * 1000) > gametime) * -2;
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:5749]: fixing typos

File: src/ai/defaultai.cc [hunk 7]
```diff
@@ -3035,7 +3065,8 @@ bool DefaultAI::construct_building(const Time& gametime) {
 
 					if (bo.is(BuildingAttribute::kRanger)) {
 
-						assert(bo.new_building == BuildingNecessity::kNeeded);
+						assert(bo.new_building == BuildingNecessity::kNeeded ||
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:3055]: fixing the bug that the forced after was ignored for rangers

File: src/ai/defaultai.cc [hunk 8]
```diff
@@ -2889,9 +2918,10 @@ bool DefaultAI::construct_building(const Time& gametime) {
 				uint8_t number_of_supporters_nearby = 0;
 				if (bo.requires_supporters) {
 					if (bf->supporters_nearby.count(bo.name) == 0) {
-						continue;
+						prio -= 100 + std::abs(management_data.get_military_number_at(18)) * 3;
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:2908]: discourage the building when no suporter available rather then forbid

File: src/ai/defaultai.cc [hunk 9]
```diff
@@ -2620,22 +2640,31 @@ bool DefaultAI::construct_building(const Time& gametime) {
...
-	} else if (stocked_wood_margin > 25) {
-		wood_policy_ = WoodPolicy::kStopRangers;
-	} else {
-		wood_policy_ = WoodPolicy::kAllowRangers;
+	// we must calculate wood policy for each type of rangers
+	for (BuildingObserver& bo : rangers_) {
+		// stocked level of supported wares (only lowest counts) is to be in some proportion to
+		// productionsites and constructionsites (this proportion is bit artifical, or we can say
+		// it is proportion to the size of economy). Plus some positive 'margin'.
+		const int32_t stocked_wood_margin = get_stocklevel(bo, gametime) -
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:2635]: this formula is exactly reused in defaultai_warfare below to replace the former woodpolicy usage

File: src/ai/defaultai.cc [hunk 10]
```diff
@@ -1555,7 +1567,7 @@ void DefaultAI::update_buildable_field(BuildableField& field) {
 	resource_count_now = false;
 	// Testing in first 10 seconds or if last testing was more then 60 sec ago
 	if (field.last_resources_check_time < Time(10000) ||
-	    field.last_resources_check_time > gametime + Duration(60 * 1000)) {
+	    gametime > field.last_resources_check_time + Duration(60 * 1000)) {
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:1562]: this was simply a bug preventing the fileds to be updated resulting in quarries being built without stones in vicinity

File: src/ai/defaultai.cc [hunk 11]
```diff
@@ -1162,7 +1166,7 @@ void DefaultAI::late_initialization() {
 		}
 	}
 
-	// getting list of all fields nearby port space
+	// getting list of all fields nearby port space and a list of outer fields for shipyard priority
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:1168]: all fields around portspaces in a radius of 3 are detected to be blocked for the ai to ensure we can build a port. 
all fields from radius 3 to radius 8 are marked to prefer shipyards.  
this should cure #1006 and is safeguarded by the check for wrong shipyard. good to test with europa 1.2 and black player

File: src/ai/defaultai.cc [hunk 12]
```diff
@@ -1043,7 +1046,8 @@ void DefaultAI::late_initialization() {
 
 	// atlanteans they consider water as a resource
 	// (together with mines, rocks and wood)
-	if (tribe_->name() == "atlanteans") {
+	// TODO(hessenfarmer): this should be moved from hardcoded to configurable / detectable
+	if (tribe_->name() == "atlanteans" || tribe_->name() == "amazons") {
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:1049]: both tribes need a coastline to work

File: src/ai/defaultai.cc [hunk 13]
```diff
@@ -1004,6 +1005,8 @@ void DefaultAI::late_initialization() {
 					verb_log_dbg_time(gametime, "AI %d detected ranger: %s -> %s", player_number(),
 					                  bo.name, lumberjack->name().c_str());
 					bo.set_is(BuildingAttribute::kRanger);
+					rangers_.push_back(bo);
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:1007]: filling the list wit all rangers and initializing the map with the wood_policies for each ranger

File: src/ai/defaultai.cc [hunk 14]
```diff
@@ -981,6 +975,12 @@ void DefaultAI::late_initialization() {
 					bo.critical_building_material.push_back(temp_buildcosts.first);
 				}
 			}
+			for (const auto& temp_buildcosts : train.enhancement_cost()) {
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:977]: here we fill the list of critical buildmaterial for trainingsite enhancements which we need in defaultai_warfare.cc

File: src/ai/defaultai.cc [hunk 15]
```diff
@@ -862,46 +864,38 @@ void DefaultAI::late_initialization() {
...
-						produces_non_construction_material = true;
-					}
-				}
-				if (produces_construction_material) {
-					// TODO(GunChleoc): We should lose the hard distinction between quarry and
-					// lumberjack, so that a building can be both
-					if (prod.supported_by_productionsites().empty()) {
+				// TODO(hessenfarmer): hardcoded strings should be parsed from a definition file
+				for (const auto& attribute : prod.collected_attributes()) {
+					if (attribute.second == Widelands::MapObjectDescr::get_attribute_id("rocks")) {
```
Comment (hessenfarmer) [inline src/ai/defaultai.cc:868]: changed the detection of some special productionsites to check for the collected immovables, as the former logic was based on the assumption that granite and log are used for construction which is not guaranteed for each tribe (e.g. the europeans only used processed log for building)

File: src/ai/ai_help_structs.h [hunk 16]
```diff
@@ -416,7 +416,8 @@ struct BuildableField {
 	ExtendedBool is_portspace;
 	bool port_nearby;  // to increase priority if a port is nearby,
 	// especially for new colonies
-	ExtendedBool portspace_nearby;  // special fields intended for ports
+	ExtendedBool portspace_nearby;    // special fields intended for ports
+	ExtendedBool shipyard_preferred;  // special fields intended for shipyards
```
Comment (hessenfarmer) [inline src/ai/ai_help_structs.h:420]: the new bool is set if a field is near a port field to ensure to the highest extend that we will have ship and port at the same sea

File: src/ai/defaultai.h [hunk 17]
```diff
@@ -79,6 +79,7 @@ struct DefaultAI : ComputerPlayer {
 	enum class WalkSearch : uint8_t { kAnyPlayer, kOtherPlayers, kEnemy };
 	enum class WoodPolicy : uint8_t { kDismantleRangers, kStopRangers, kAllowRangers };
 	enum class NewShip : uint8_t { kBuilt, kFoundOnLoad };
+	enum class FleetStatus : uint8_t { kNeedShip = 0, kEnoughShips = 1, kDoNothing = 2 };
```
Comment (hessenfarmer) [inline src/ai/defaultai.h:82]: this was a local variable from the *.cc which is now needed in a broader context

File: src/ai/defaultai.h [hunk 18]
```diff
@@ -298,14 +299,16 @@ struct DefaultAI : ComputerPlayer {
 	// the purpose is to print out a warning that the game is pacing too fast
 	int32_t scheduler_delay_counter_;
 
-	WoodPolicy wood_policy_;
+	std::map<Widelands::DescriptionIndex, WoodPolicy> wood_policy_;
```
Comment (hessenfarmer) [inline src/ai/defaultai.h:302]: this is now a map to cover for a wood_policy for each ranger building (i.e. one for amazon jungle preservers and a different one for the Rare_tree plantation) to start. stop. build and dismantle each ranger seperatly

File: src/ai/defaultai.h [hunk 19]
```diff
@@ -298,14 +299,16 @@ struct DefaultAI : ComputerPlayer {
...
 	uint16_t trees_nearby_treshold_;
 
 	std::vector<BuildingObserver> buildings_;
+	std::vector<BuildingObserver> rangers_;
 	std::deque<Widelands::FCoords> unusable_fields;
 	std::deque<BuildableField*> buildable_fields;
 	BlockedFields blocked_fields;
 	std::unordered_set<uint32_t> ports_vicinity;
+	std::unordered_set<uint32_t> ports_shipyard_region;
```
Comment (hessenfarmer) [inline src/ai/defaultai.h:311]: this is needed to determine the bool shipyard_preferred

File: src/ai/defaultai.h [hunk 20]
```diff
@@ -392,10 +395,11 @@ struct DefaultAI : ComputerPlayer {
 	   "trident", "tabard", "shield", "mask",    "spear", "warrior"};
 
 	// seafaring related
-	enum { kReprioritize, kStopShipyard, kStapShipyard };
+	enum { kReprioritize, kStopShipyard, kStartShipyard };
 	static Time last_seafaring_check_;
 	// False by default, until Map::allows_seafaring() is true
 	static bool map_allows_seafaring_;
+	bool potential_wrong_shipyard_ = false;
```
Comment (hessenfarmer) [inline src/ai/defaultai.h:402]: needed to cope for the (now more rare) case that a shipyard is built at the wrong sea

File: src/ai/defaultai_seafaring.cc [hunk 21]
```diff
@@ -127,46 +127,27 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
 	uint16_t ports_count = 0;
 	uint16_t shipyards_count = 0;
 	uint16_t expeditions_in_prep = 0;
+	uint16_t expeditions_ready = 0;
 	uint16_t expeditions_in_progress = 0;
 	bool idle_shipyard_stocked = false;
 
-	// goes over all warehouses (these includes ports)
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:133]: this was moved down below the seafaring map check, as doing this check on non seafaring maps makes no sense

File: src/ai/defaultai_seafaring.cc [hunk 22]
```diff
@@ -127,46 +127,27 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
...
-				return false;
-			}
-
-			// counting stocks
-			uint8_t stocked_wares = 0;
-			std::vector<Widelands::InputQueue*> const inputqueues = ps_obs.site->inputqueues();
-			for (Widelands::InputQueue* queue : inputqueues) {
-				if (queue->get_type() == Widelands::wwWARE) {
-					stocked_wares += queue->get_filled();
+				if (!ps_obs.site->get_economy(Widelands::wwWORKER)->warehouses().empty()) {
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:145]: stopping an erroneously existent shipyard is not sufficient so I changed this to dismantle it.

File: src/ai/defaultai_seafaring.cc [hunk 23]
```diff
@@ -127,46 +127,27 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
...
 				verb_log_dbg_time(
 				   game().get_gametime(),
-				   "  %1d: we have working shipyard in a non seafaring ecoomy, stopping it...\n",
+				   "  %1d: we have a shipyard in a non seafaring economy, dismantling it...\n",
 				   player_number());
-				game().send_player_start_stop_building(*ps_obs.site);
-				return false;
-			}
-
-			// counting stocks
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:160]: this was moved down into the shipyard handling  to have all the shipyard decisions in one place

File: src/ai/defaultai_seafaring.cc [hunk 24]
```diff
@@ -212,27 +206,38 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
...
+			for (Widelands::InputQueue* queue : inputqueues) {
+				if (queue->get_type() == Widelands::wwWARE) {
+					stocked_wares += queue->get_filled();
 				}
+			}
+			if (stocked_wares == 16 && ps_obs.site->is_stopped() && ps_obs.site->can_start_working()) {
+				idle_shipyard_stocked = true;
+			}
 
+			if (expeditions_ready > 0 && idle_shipyard_stocked && allships.size() - ports_count == 0) {
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:224]: this is describing the condition when a shipyard potentially is being built in the wrong place. unfortunately we need to wait for at least one ship build there to detect this.
background: if a port exists and a shipyard exists a ship is build as long as the # of available ships is lower then the number of ports. If an expedition is ready a ship is assigned and will move to the port and take the expedition resulting in no expedition rerady at the Protdock (pd). 
so if we have a port, a ship and an expedition ready we either have the ship in the wrong sea or the ship is underway so we repeat the check in 2 consecutive decision intervals and if it persists (determined from the variable "potential_wrong_shipyard" we dismantle the shipyard and sink the ship.

File: src/ai/defaultai_seafaring.cc [hunk 25]
```diff
@@ -212,27 +206,38 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
...
+				if (potential_wrong_shipyard_) {
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:225]: only true if the above condition persisits in 2 consecutive checks

File: src/ai/defaultai_seafaring.cc [hunk 26]
```diff
@@ -212,27 +206,38 @@ bool DefaultAI::marine_main_decisions(const Time& gametime) {
...
+					}
+					game().send_player_sink_ship(*allships.back().ship);
+					allships.pop_back();
+					potential_wrong_shipyard_ = false;
+					return true;
+				}
+				potential_wrong_shipyard_ = true;
+				return false;
+			}
+			if (enough_ships == FleetStatus::kNeedShip && idle_shipyard_stocked) {
```
Comment (hessenfarmer) [inline src/ai/defaultai_seafaring.cc:239]: we need a ship and order this shipyard to build one

File: src/ai/defaultai_warfare.cc [hunk 27]
```diff
@@ -714,19 +714,33 @@ bool DefaultAI::check_trainingsites(const Time& gametime) {
 
 	const Widelands::DescriptionIndex enhancement = ts->descr().enhancement();
 
-	if (enhancement != Widelands::INVALID_INDEX && ts_without_trainers_ == 0 && mines_.size() > 3 &&
+	if (enhancement != Widelands::INVALID_INDEX && ts_without_trainers_ == 0 &&
```
Comment (hessenfarmer) [inline src/ai/defaultai_warfare.cc:717]: removed the check for 3 mines as this was only a mediocre indication for an economy that can sustain enhanced trainingsites and made the enhancement solely dependent on building materials (including gold or other valuable Buildmaterials)
this is the fix for #4669

File: src/ai/defaultai_warfare.cc [hunk 28]
```diff
@@ -714,19 +714,33 @@ bool DefaultAI::check_trainingsites(const Time& gametime) {
...
 		uint16_t current_proportion =
 		   en_bo.total_count() * 100 / (ts_finished_count_ + ts_in_const_count_);
+		en_bo.build_material_shortage = false;
+		uint8_t shortage_counter = 0;
+		// checking we have enough critical material on stock
+		for (uint32_t m = 0; m < en_bo.critical_building_material.size(); ++m) {
+			Widelands::DescriptionIndex wt(
+			   static_cast<size_t>(en_bo.critical_building_material.at(m)));
+			if (calculate_stocklevel(wt) <=
+			    static_cast<unsigned int>(std::abs(management_data.get_military_number_at(19)) / 20)) {
```
Comment (hessenfarmer) [inline src/ai/defaultai_warfare.cc:735]: this results in 5 or lower

File: src/ai/defaultai_warfare.cc [hunk 29]
```diff
@@ -1122,6 +1136,11 @@ BuildingNecessity DefaultAI::check_building_necessity(BuildingObserver& bo, cons
 	                         3)};
 	const uint16_t total_score = scores[0] + scores[1] + scores[2];
 
+	// help variable to determine wood availability in the economy
+	const int32_t stocked_wood_level = calculate_stocklevel(tribe_->safe_ware_index("log")) -
```
Comment (hessenfarmer) [inline src/ai/defaultai_warfare.cc:1140]: this is needed to replace the usage of the old only log based wood policy but will result in the same logical values

**Comment by hessenfarmer** [comment]
ok I added review comments now what has been changed

**Comment by hessenfarmer** [comment]
> 
> 
> [CrashAndSave.zip](https://github.com/widelands/widelands/files/7553684/CrashAndSave.zip)
> 
> @hessenfarmer i played +/- like you suggested but now hit a crash. Please take a look. Attached is my latest autosave, too. Maybe you want to check how the AI did?

the AI did not that bad. If you load this game in master and watch the black AI #1006 will happen instantly

**Comment by MarkMcWire** [comment]
My widelands build with 4911 AI fix crashes frequently. -> https://drive.google.com/file/d/1DDHR-8C1gbCYZ1wkYX_h8Ps45ZcoCs25/view?usp=sharing

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==22933==ERROR: AddressSanitizer: stack-overflow on address 0x7f5a602fdfe8 (pc 0x7f5a77141683 bp 0x7f5a602fe870 sp 0x7f5a602fdff0 T3)
    #0 0x7f5a77141683  (/usr/lib/libasan.so.6+0xaa683)
    #1 0x7f5a77141f96 in __interceptor_memcmp (/usr/lib/libasan.so.6+0xaaf96)
    #2 0x7f5a74d7db8b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (/usr/lib/libstdc++.so.6+0x164b8b)
    #3 0x446a39 in bool std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/11/bits/basic_string.h:6342
    #4 0x4509b4 in std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/c++/11/bits/stl_function.h:386
    #5 0x147f83a in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::_M_lower_bound(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > const*, std::_Rb_tree_node_base const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/c++/11/bits/stl_tree.h:1919
    #6 0x147933c in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/c++/11/bits/stl_tree.h:2534
    #7 0x1476d20 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/c++/11/bits/stl_map.h:1195
    #8 0x1473109 in Widelands::DescriptionMaintainer<Widelands::WorkerDescr>::get_index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (/home/solus/Git/widelands/widelands+0x1473109)
    #9 0x1467f37 in Widelands::Descriptions::worker_index(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/solus/Git/widelands/src/logic/map_objects/descriptions.cc:320
    #10 0x16ba599 in Widelands::WorkerDescr::worker_index() const /home/solus/Git/widelands/src/logic/map_objects/tribes/worker_descr.cc:210
    #11 0x16ba4ab in Widelands::WorkerDescr::can_act_as(unsigned short) const /home/solus/Git/widelands/src/logic/map_objects/tribes/worker_descr.cc:199
    #12 0x1598cb7 in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:641
    #13 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #14 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #15 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #16 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #17 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #18 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #19 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #20 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #21 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #22 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #23 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #24 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #25 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #26 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #27 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #28 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #29 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #30 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #31 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #32 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #33 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #34 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #35 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #36 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #37 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #38 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #39 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #40 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #41 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #42 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #43 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #44 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #45 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #46 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #47 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #48 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #49 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #50 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #51 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #52 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #53 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #54 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #55 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #56 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #57 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #58 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #59 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #60 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #61 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #62 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #63 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #64 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #65 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #66 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #67 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #68 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #69 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #70 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #71 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #72 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #73 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #74 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #75 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #76 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #77 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #78 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #79 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #80 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #81 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #82 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #83 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #84 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #85 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #86 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #87 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #88 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #89 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #90 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #91 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #92 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #93 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #94 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #95 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #96 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #97 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #98 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #99 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #100 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #101 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #102 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #103 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #104 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #105 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #106 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #107 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #108 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #109 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #110 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #111 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #112 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #113 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #114 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #115 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #116 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #117 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #118 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #119 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #120 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #121 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #122 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #123 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #124 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #125 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #126 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #127 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #128 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #129 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #130 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #131 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #132 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #133 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #134 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #135 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #136 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #137 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #138 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #139 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #140 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #141 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #142 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #143 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #144 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #145 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #146 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #147 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #148 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #149 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #150 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #151 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #152 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #153 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #154 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #155 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #156 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #157 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #158 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #159 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #160 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #161 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #162 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #163 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #164 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #165 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #166 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #167 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #168 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #169 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #170 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #171 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #172 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #173 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #174 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #175 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #176 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #177 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #178 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #179 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #180 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #181 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #182 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #183 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #184 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #185 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #186 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #187 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #188 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #189 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #190 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #191 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #192 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #193 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #194 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #195 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #196 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #197 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #198 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #199 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #200 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #201 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #202 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #203 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #204 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #205 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #206 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #207 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #208 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #209 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #210 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #211 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #212 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #213 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #214 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #215 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #216 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #217 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #218 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #219 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #220 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #221 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #222 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #223 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #224 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #225 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #226 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #227 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #228 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #229 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #230 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #231 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #232 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #233 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #234 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #235 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #236 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #237 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #238 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #239 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #240 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #241 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #242 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #243 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #244 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #245 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #246 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #247 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654
    #248 0x15990fc in Widelands::ProductionSite::try_replace_worker(Widelands::Game const*, unsigned short, Widelands::ProductionSite::WorkingPosition*) /home/solus/Git/widelands/src/logic/map_objects/tribes/productionsite.cc:654

SUMMARY: AddressSanitizer: stack-overflow (/usr/lib/libasan.so.6+0xaa683) 
Thread T3 created by T0 here:
    #0 0x7f5a770d7a05 in __interceptor_pthread_create (/usr/lib/libasan.so.6+0x40a05)
    #1 0x7f5a74d04139 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/libstdc++.so.6+0xeb139)
    #2 0x414118 in GameLogicThread /home/solus/Git/widelands/src/wlapplication.cc:227
    #3 0x41e2eb in WLApplication::run() /home/solus/Git/widelands/src/wlapplication.cc:748
    #4 0x412a0b in main /home/solus/Git/widelands/src/main.cc:47
    #5 0x7f5a748ee3a4 in __libc_start_main (/usr/lib/libc.so.6+0x283a4)

==22933==ABORTING
```

**Comment by Noordfrees** [comment]
This looks rather like a side-effect of #5099 @matthiakl

**Comment by hessenfarmer** [comment]
> 
> 
> This looks rather like a side-effect of #5099 @matthiakl

that was my thought as well. tried the game in master and it froze when I tried to end the game.  Nearly froze my whole machine.

**Comment by matthiakl** [comment]
See #5125 

> The problem is, that the reordering does not terminate for the european basic farm, where both slots need the same worker.
This quick fix solves the issue, but I will look, whether there is a better solution.

**Comment by hessenfarmer** [comment]
@MarkMcWire     
Now that the crash has gone. Any further comments on this?
@klaus-halfmann 
did the comments help you understand what is going on?

**Review by klaus-halfmann — APPROVED** [review]
For me its ok, how can we fix the Launchpad Builds now?

**Comment by hessenfarmer** [comment]
> For me its ok, how can we fix the Launchpad Builds now?

If you refer to the failing GCC builds they are not related to this branch. @Noordfrees is working on it, I believe.

**Comment by hessenfarmer** [comment]
@tibor95     
are you still interested in the widelands AI? If the answer is hopefully yes I'd like to hear your opinion as well.

**Comment by hessenfarmer** [comment]
@Noordfrees 
As we got no answer from @tibor95 for a long time now I'd like you to do a final review and merge if you are pleased with the coe

File: src/ai/defaultai.cc [hunk 30]
```diff
@@ -1174,6 +1178,14 @@ void DefaultAI::late_initialization() {
 				ports_vicinity.insert(hash);
 			}
 		} while (mr.advance(map));
+		Widelands::HollowArea<> ha(Widelands::Area<>(map.get_fcoords(c), 8), 3);
+		Widelands::MapHollowRegion<> mhr(map, ha);
+		do {
+			const uint32_t hash = mhr.location().hash();
+			if (!ports_shipyard_region.count(hash)) {
+				ports_shipyard_region.insert(hash);
+			}
```
Comment (Noordfrees) [inline src/ai/defaultai.cc]: Calling `insert()` on a set or unordered_set does nothing if the key is already present
```suggestion
			ports_shipyard_region.insert(hash);
```

File: src/ai/defaultai.cc [hunk 31]
```diff
@@ -1710,7 +1729,8 @@ void DefaultAI::update_buildable_field(BuildableField& field) {
 						continue;
 					}
 				}
-				uint8_t amount = map.find_immovables(
+				uint8_t amount = 0;
+				amount = map.find_immovables(
```
Comment (Noordfrees) [inline src/ai/defaultai.cc]: What's the purpose of splitting declaration and assignment here?

**Review by Noordfrees — APPROVED** [review]
LGTM 
Two small nits, then this can go in.
Great work :)

File: src/ai/defaultai.cc (hunk 30 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: didn't know that. In fact I tend to implement things by "copy + paste + adjust" as this is the same method as a couple of lines above I think I should go over the complete code to clean these things up.  
do I understand this right that the suggested code might be more performant as it gets rid of an if check.

File: src/ai/defaultai.cc (hunk 31 above)
Comment (hessenfarmer) [reply src/ai/defaultai.cc]: Well IIRC this is a leftover of the attempts to fix the bug that quarries are build even when rocks are already depleted. In the first instance I beleived that amount might have not been defined if no immovables are found, but the fix was done some lines above. As I checked that find_immovables will return 0 if no immovables found I'll revert this
