### PR TITLE
Fix statistics button translation

### LINKED ISSUE #3221: Statistics Button inherits tooltip from hosts locale
I was playing my turnamaent game agains GunCheleoc.
I was on english she on gaelic.

After some crash she hosted again and I noticed, that the label
of the statistics button was in gaelic.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2017-11-05T15:05:30Z
 * owner: klaus-halfmann
 * assignee: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1730202

### PR DESCRIPTION
**Pull request by matthiakl**
Fixes #3221 
Dump the lua value untranslated and let C++ do the translation. This was already double translated.

### CODE REVIEW

**Review by gunchleoc — APPROVED** [review]

File: data/scripting/win_conditions/territorial_functions.lua [hunk 1]
```diff
@@ -14,6 +14,12 @@ local team_str = _"Team %i"
 local wc_has_territory = _"%1$s has %2$3.0f%% of the land (%3$i of %4$i)."
 local wc_had_territory = _"%1$s had %2$3.0f%% of the land (%3$i of %4$i)."
 
+local wc_stats = "Territory percentage"
+-- This needs to be exactly like wc_points, but localized, because wc_points
```
Comment (frankystone) [inline data/scripting/win_conditions/territorial_functions.lua]: I guess 'wc_points' should be 'wc_stats' here?

**Review by frankystone — CHANGES_REQUESTED** [review]

File: data/scripting/win_conditions/territorial_functions.lua (hunk 1 above)
Comment (gunchleoc) [reply data/scripting/win_conditions/territorial_functions.lua]: Yes, it should.

File: data/scripting/win_conditions/wood_gnome.lua [hunk 2]
```diff
@@ -19,7 +19,10 @@ local wc_desc = _(
...
 [[your territory than any other player. The game will end after 4 hours of ]] ..
 [[playing. The one with the most trees at that point will win the game.]])
-local wc_trees_owned = _"Trees owned"
+local wc_trees_owned = "Trees owned"
+-- This needs to be exactly like wc_trees_owned, but localized, because wc_trees_owned
+-- will be used as the key to fetch the translation in C++
+local wc_trees_owned_i18n = _"Trees owned"
 
 local r = {
    name = wc_name,
```
Comment (gunchleoc) [inline data/scripting/win_conditions/wood_gnome.lua:28]:
```suggestion
   name = wc_trees_owned,
```

I haven't tested this for all win conditions, looks like we need more changes here

Comment (matthiakl) [reply data/scripting/win_conditions/wood_gnome.lua:28]: This PR focuses on the statistics button mentioned in the issue. Other parts of the win conditions will still be stored translated in the save. This includes the task or win message, which are a bit trickier to translate afterwards. I don't know what your suggestion should change, but I checked the statistics button with all win conditions and it translated fine.

Comment (gunchleoc) [reply data/scripting/win_conditions/wood_gnome.lua:28]: Thanks for confirming it's tested, let's have this branch :)
